import { BangladeshLawRecord } from '../bdcode-architecture';

export const CIVIL_FAMILY_PROPERTY_LAWS: BangladeshLawRecord[] = [
  // 3. CIVIL LAW AND PROCEDURE
  {
    id: 'bd-cpc-1908',
    title: 'The Code of Civil Procedure, 1908',
    titleBn: 'দেওয়ানি কার্যবিধি, ১৯০৮',
    shortTitle: 'CPC (দেওয়ানি কার্যবিধি)',
    alternateTitles: ['Act No. V of 1908', '১৯০৮ সালের ৫ নং আইন', 'Code of Civil Procedure 1908'],
    enactmentYear: 1908,
    actNumber: 'Act No. V of 1908',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 4,
    volumeCitation: 'The Bangladesh Code, Volume IV (1898–1908), Act V of 1908',
    category: 'Civil Law & Procedure',
    categorySlug: 'civil-procedure',
    subcategories: ['Civil Suits & Pleadings', 'Injunctions (Order 39)', 'Mediation & ADR (Sec 89A)', 'Res Judicata', 'Execution of Decrees'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['cpc', 'civil procedure', 'injunction', 'order 39', 'mediation', 'section 89a', 'res judicata', 'section 11', 'দেওয়ানি কার্যবিধি', 'নিষেধাজ্ঞা', 'মধ্যস্থতা'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '21st March 1908',
    commencementDate: '1st January 1909',
    lastAmendedYear: 2017,
    lastAmendmentAct: 'Act No. IX of 2017',
    overview: 'The fundamental procedural statute regulating civil courts in Bangladesh. Governs institution of suits, jurisdiction of courts, temporary injunctions, execution of decrees, alternative dispute resolution (ADR), and appeals.',
    overviewBn: 'বাংলাদেশের দেওয়ানি বিচার ব্যবস্থার মূল কার্যবিধি আইন। দেওয়ানি মোকদ্দমা দায়ের, নিষেধাজ্ঞা, ডিক্রি জারি ও আপিল প্রক্রিয়া নিয়ন্ত্রণ করে।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-86.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/86',
    officialGazetteCitation: 'Legislative Enactment Act V of 1908 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 158,
    relatedLawIds: ['bd-specific-relief-1877', 'bd-limitation-act-1908', 'bd-court-fees-1870'],
    sections: [
      {
        number: 'Section 9',
        title: 'Courts to Try All Civil Suits Unless Barred',
        titleBn: 'আইনত বারিত না থাকিলে সকল দেওয়ানি মোকদ্দমা বিচারের আদালতের এখতিয়ার',
        content: 'The Courts shall (subject to the provisions herein contained) have jurisdiction to try all suits of a civil nature excepting suits of which their cognizance is either expressly or impliedly barred.',
        contentBn: 'সুনির্দিষ্ট বা পরোক্ষ কোনো আইনি নিষেধাজ্ঞা না থাকলে আদালত যেকোনো দেওয়ানি প্রকৃতির বিরোধ বিচারের পূর্ণ এখতিয়ার সংরক্ষণ করে।',
        simpleExplanation: 'Establishes the broad plenary jurisdiction of civil courts over rights to property, office, and contracts.',
      },
      {
        number: 'Section 11',
        title: 'Res Judicata',
        titleBn: 'রেস জুডিকাটা বা দোবারা দোষ',
        content: 'No Court shall try any suit or issue in which the matter directly and substantially in issue has been directly and substantially in issue in a former suit between the same parties, or between parties under whom they or any of them claim, litigating under the same title, in a Court competent to try such subsequent suit or the suit in which such issue has been subsequently raised, and has been heard and finally decided by such Court.',
        contentBn: 'একই পক্ষগণের মধ্যে ইতিপূর্বে কোনো উপযুক্ত আদালত কর্তৃক চূড়ান্তভাবে মীমাংসিত বিষয় পুনরায় নতুন মোকদ্দমায় বিচার করা যাবে না।',
        simpleExplanation: 'Doctrine preventing double litigation: Once a court has finalized a dispute between parties, neither party can sue again on the same issue.',
      },
      {
        number: 'Section 89A',
        title: 'Mediation / Alternative Dispute Resolution (ADR)',
        titleBn: 'মধ্যস্থতা বা বিকল্প বিরোধ নিষ্পত্তি (এডিআর)',
        content: 'Except in a suit under the Artha Rin Adalat Ain, after filing of written statement, the Court shall, by adjourning the hearing of the suit, mediate in order to settle the dispute or disputes in the suit, or refer the dispute or disputes to the engaged pleaders or to an accredited mediator.',
        contentBn: 'জবাব দাখিলের পর আদালত পক্ষগণের সম্মতিতে মামলাটি মধ্যস্থতাকারীর নিকট বা আইনজীবীদের মাধ্যমে আপস নিষ্পত্তির জন্য প্রেরণ করতে পারেন।',
        simpleExplanation: 'Mandates institutional mediation in civil lawsuits to encourage out-of-court settlements and reduce court backlogs.',
      },
      {
        number: 'Order 39, Rule 1',
        title: 'Cases in Which Temporary Injunction May Be Granted',
        titleBn: 'যেসব ক্ষেত্রে অস্থায়ী নিষেধাজ্ঞা মঞ্জুর করা যায়',
        content: 'Where in any suit it is proved by affidavit or otherwise: (a) that any property in dispute in a suit is in danger of being wasted, damaged or alienated by any party to the suit, or wrongfully sold in execution of a decree, or (b) that the defendant threatens, or intends, to remove or dispose of his property with a view to defraud his creditors, the Court may by order grant a temporary injunction.',
        contentBn: 'মোকদ্দমা চলাকালে নালিশি সম্পত্তি যাতে হস্তান্তর, ক্ষতিসাধন বা বেদখল না হয়, তার সুরক্ষায় আদালত অস্থায়ী নিষেধাজ্ঞা জারি করতে পারেন।',
        simpleExplanation: 'Provides urgent court orders to freeze property and preserve the status quo during the pendency of a civil suit.',
      },
    ],
  },
  {
    id: 'bd-specific-relief-1877',
    title: 'The Specific Relief Act, 1877',
    titleBn: 'সুনির্দিষ্ট প্রতিকার আইন, ১৮৭৭',
    shortTitle: 'Specific Relief Act (সুনির্দিষ্ট প্রতিকার আইন)',
    alternateTitles: ['Act No. I of 1877', '১৮৭৭ সালের ১ নং আইন'],
    enactmentYear: 1877,
    actNumber: 'Act No. I of 1877',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 2,
    volumeCitation: 'The Bangladesh Code, Volume II (1872–1882), Act I of 1877',
    category: 'Civil Law & Procedure',
    categorySlug: 'civil-procedure',
    subcategories: ['Recovery of Possession (Sec 8 & 9)', 'Specific Performance (Sec 12)', 'Declaratory Suits (Sec 42)', 'Injunctions (Sec 52-54)'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['specific relief', 'section 9', 'section 42', 'declaratory suit', 'specific performance', 'injunction', 'sunirdishto protikar', 'সুনির্দিষ্ট প্রতিকার', 'ঘোষণামূলক মোকদ্দমা'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '7th February 1877',
    commencementDate: '1st May 1877',
    lastAmendedYear: 2004,
    overview: 'Core civil statute defining equitable civil remedies, including recovery of immovable property, specific performance of land purchase contracts, declaratory judgments of title, and permanent injunctions.',
    overviewBn: 'দেওয়ানি আদালতের ন্যায়সঙ্গত প্রতিকার সংক্রান্ত আইন। চুক্তি কার্যকরকরণ, স্বত্ব ঘোষণা, দখল পুনরুদ্ধার ও চিরতরে নিষেধাজ্ঞা প্রদান করে।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-33.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/33',
    officialGazetteCitation: 'Legislative Enactment Act I of 1877 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 57,
    relatedLawIds: ['bd-cpc-1908', 'bd-transfer-property-1882', 'bd-limitation-act-1908'],
    sections: [
      {
        number: 'Section 8',
        title: 'Recovery of Specific Immovable Property on Title',
        titleBn: 'স্বত্বের ভিত্তিতে সুনির্দিষ্ট স্থাবর সম্পত্তি পুনরুদ্ধার',
        content: 'A person entitled to the possession of specific immovable property may recover it in the manner prescribed by the Code of Civil Procedure, 1908.',
        contentBn: 'কোনো স্থাবর সম্পত্তিতে স্বত্ববান ব্যক্তি দেওয়ানি কার্যবিধির বিধান মোতাবেক দখল পুনরুদ্ধারের মোকদ্দমা করতে পারেন।',
        simpleExplanation: 'Standard ownership suit: Enables rightful title holders to recover physical possession of land within 12 years under Limitation Act.',
      },
      {
        number: 'Section 9',
        title: 'Suit by Person Dispossessed of Immovable Property',
        titleBn: 'স্থাবর সম্পত্তি হতে বেদখলকৃত ব্যক্তি কর্তৃক মোকদ্দমা',
        content: 'If any person is dispossessed without his consent of immovable property otherwise than in due course of law, he or any person claiming through him may, by suit, recover possession thereof, notwithstanding any other title that may be set up in such suit. Such suit must be brought within six months from the date of the dispossession.',
        contentBn: 'আইনি প্রক্রিয়া ব্যতীত বেদখল হলে স্বত্ব প্রমাণের প্রয়োজন ছাড়াই ৬ মাসের মধ্যে দখল পুনরুদ্ধারের মোকদ্দমা করা যায়।',
        simpleExplanation: 'Summary remedy: Allows someone illegally dispossessed of land to regain possession within 6 months without having to prove underlying title.',
      },
      {
        number: 'Section 12',
        title: 'Cases in Which Specific Performance Enforceable',
        titleBn: 'যেসব ক্ষেত্রে চুক্তির সুনির্দিষ্ট কার্যসম্পাদন বাধ্যতামূলক করা যায়',
        content: 'The specific performance of any contract may, in the discretion of the Court, be enforced when there exists no standard for ascertaining the actual damage caused by the non-performance of the act agreed to be done, or when the act agreed to be done is such that pecuniary compensation for its non-performance would not afford adequate relief.',
        contentBn: 'স্থাবর সম্পত্তি বিক্রয়ের বায়না চুক্তি লঙ্ঘিত হলে আর্থিক ক্ষতিপূরণ পর্যাপ্ত না হলে আদালত চুক্তি সম্পাদনের আদেশ দিতে পারেন।',
        simpleExplanation: 'Enforces registered contracts for sale of land (Baina contracts), compelling recalcitrant sellers to execute deeds.',
      },
      {
        number: 'Section 42',
        title: 'Discretion of Court as to Declaration of Status or Right (Declaratory Suit)',
        titleBn: 'মর্যাদা বা অধিকার ঘোষণার ক্ষেত্রে আদালতের সুবিবেচনামূলক ক্ষমতা',
        content: 'Any person entitled to any legal character, or to any right as to any property, may institute a suit against any person denying, or interested to deny, his title to such character or right, and the Court may in its discretion make therein a declaration that he is so entitled.',
        contentBn: 'আইনগত মর্যাদা বা সম্পত্তিতে অধিকার অস্বীকার করা হলে তা বহাল রাখতে ঘোষণামূলক মোকদ্দমা দায়ের করা যায়।',
        simpleExplanation: 'Core foundation for property title suits seeking an authoritative judicial declaration of ownership.',
      },
      {
        number: 'Section 54',
        title: 'Perpetual Injunction When Granted',
        titleBn: 'যেসব ক্ষেত্রে চিরস্থায়ী নিষেধাজ্ঞা মঞ্জুর করা যায়',
        content: 'A perpetual injunction may be granted to the plaintiff to prevent the breach of an obligation existing in his favour, whether expressly or by implication, where the defendant invades or threatens to invade the plaintiff’s right to, or enjoyment of, property.',
        contentBn: 'বাদীর স্বত্ব ও শান্তিপূণ ভোগদখল স্থায়ীভাবে সুরক্ষার জন্য বিবাদীর অবৈধ হস্তক্ষেপ রোধে আদালত চিরস্থায়ী নিষেধাজ্ঞা প্রদান করেন।',
        simpleExplanation: 'Final judicial decree perpetually barring the opposing party from disturbing plaintiff’s peaceful ownership and possession.',
      },
    ],
  },
  {
    id: 'bd-limitation-act-1908',
    title: 'The Limitation Act, 1908',
    titleBn: 'তামাদি আইন, ১৯০৮',
    shortTitle: 'Limitation Act (তামাদি আইন)',
    alternateTitles: ['Act No. IX of 1908', '১৯০৮ সালের ৯ নং আইন'],
    enactmentYear: 1908,
    actNumber: 'Act No. IX of 1908',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 4,
    volumeCitation: 'The Bangladesh Code, Volume IV (1898–1908), Act IX of 1908',
    category: 'Civil Law & Procedure',
    categorySlug: 'civil-procedure',
    subcategories: ['Statutory Deadlines', 'Condonation of Delay (Sec 5)', 'Exclusion of Time (Sec 14)', 'Adverse Possession (Sec 28)'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['limitation act', 'tamadi ain', 'section 5', 'delay condonation', 'statute of limitations', 'section 28', 'তামাদি আইন', 'দেরি মার্জনা'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '7th August 1908',
    commencementDate: '1st January 1909',
    lastAmendedYear: 2012,
    overview: 'Prescribes mandatory statutory periods of limitation for instituting civil suits, appeals, and revision applications in courts of law. Governs condonation of delay and extinguishment of title.',
    overviewBn: 'আদালতে মোকদ্দমা, আপিল বা আবেদন দায়েরের নির্ধারিত সময়সীমা ও তামাদি গণনা সংক্রান্ত মূল আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-88.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/88',
    officialGazetteCitation: 'Legislative Enactment Act IX of 1908 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 32,
    relatedLawIds: ['bd-cpc-1908', 'bd-specific-relief-1877'],
    sections: [
      {
        number: 'Section 3',
        title: 'Dismissal of Suits Instituted After Period of Limitation',
        titleBn: 'তামাদির মেয়াদ অতিক্রান্ত হওয়ার পর দায়েরকৃত মোকদ্দমা খারিজ',
        content: 'Subject to the provisions contained in sections 4 to 25 (inclusive), every suit instituted, appeal preferred, and application made after the period of limitation prescribed therefor by the first schedule shall be dismissed, although limitation has not been set up as a defence.',
        contentBn: 'তামাদির মেয়াদ পার হওয়ার পর দায়েরকৃত যেকোনো মোকদ্দমা, আপিল বা আবেদন আদালত আবশ্যিকভাবে খারিজ করতে বাধ্য।',
        simpleExplanation: 'Statutory deadlines are mandatory; courts must dismiss time-barred cases even if the other party does not object.',
      },
      {
        number: 'Section 5',
        title: 'Extension of Period in Certain Cases (Condonation of Delay)',
        titleBn: 'দেরি মার্জনা বা তামাদির মেয়াদ বৃদ্ধির আবেদন',
        content: 'Any appeal or application for a revision or a review of judgment or for leave to appeal or any other application to which this section may be made applicable by or under any enactment for the time being in force may be admitted after the period of limitation prescribed therefor, when the appellant or applicant satisfies the Court that he had sufficient cause for not preferring the appeal or making the application within such period.',
        contentBn: 'যথাযথ ও যুক্তিসঙ্গত কারণ প্রদর্শন করতে পারলে আপিল বা রিভিশন দায়েরের বিলম্ব আদালত মার্জনা করতে পারেন। (উল্লেখ্য, মূল মোকদ্দমায় ৫ ধারা প্রযোজ্য নয়)।',
        simpleExplanation: 'Permits courts to condone delay in filing appeals and revisions upon showing "sufficient cause" (e.g. medical emergency, fraud).',
      },
    ],
  },
  {
    id: 'bd-court-fees-1870',
    title: 'The Court-fees Act, 1870',
    titleBn: 'কোর্ট-ফিস আইন, ১৮৭০',
    shortTitle: 'Court-fees Act (কোর্ট-ফিস আইন)',
    alternateTitles: ['Act No. VII of 1870', '১৮৭০ সালের ৭ নং আইন'],
    enactmentYear: 1870,
    actNumber: 'Act No. VII of 1870',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 2,
    volumeCitation: 'The Bangladesh Code, Volume II (1872–1882), Act VII of 1870',
    category: 'Civil Law & Procedure',
    categorySlug: 'civil-procedure',
    subcategories: ['Ad Valorem Court Fees', 'Fixed Court Fees', 'Valuation of Suits', 'Fee Exemptions'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['court fees', 'ad valorem', 'valuation', 'court stamp', 'section 7', 'কোর্ট ফি', 'মামলার মূল্যায়ন'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '11th March 1870',
    commencementDate: '1st April 1870',
    lastAmendedYear: 2015,
    overview: 'Regulates statutory court fees and judicial revenue stamps required on plaints, appeals, probate petitions, and applications presented before civil and criminal courts in Bangladesh.',
    overviewBn: 'আদালতে দায়েরকৃত আরজি, আপিল ও নথিপত্রে প্রযোজ্য কোর্ট ফি ও স্ট্যাম্প শুল্ক নির্ধারণ সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-18.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/18',
    officialGazetteCitation: 'Legislative Enactment Act VII of 1870 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 36,
    relatedLawIds: ['bd-cpc-1908', 'bd-specific-relief-1877'],
    sections: [
      {
        number: 'Section 6',
        title: 'Fees on Documents Filed in High Court Division or Subordinate Courts',
        titleBn: 'আদালতে দাখিলকৃত দলিলের উপর প্রদেয় ফি',
        content: 'Except in the cases herein otherwise provided, no document of any of the kinds specified as chargeable in the first or second schedule to this Act annexed shall be filed, exhibited or recorded in any Court of Justice, unless in respect of such document there be paid a fee of an amount not less than that indicated by either of the said schedules.',
        contentBn: 'নির্ধারিত কোর্ট ফি পরিশোধ ব্যতীত কোনো দেওয়ানি আরজি বা আবেদন আদালতে গ্রহণযোগ্য হইবে না।',
        simpleExplanation: 'Mandates payment of statutory court fee stamps prior to registration of any civil plaint.',
      },
      {
        number: 'Section 7',
        title: 'Computation of Fees Payable in Certain Suits (Ad Valorem)',
        titleBn: 'কতিপয় মোকদ্দমায় প্রদেয় কোর্ট ফি গণনা পদ্ধতি',
        content: 'Prescribes the statutory valuation formula for computing ad valorem court fees on suits for money, land possession, declarations, accounts, and partition.',
        contentBn: 'সম্পত্তির বাজারমূল্য বা দাবিকৃত অর্থের ভিত্তিতে শতকরা হারে কোর্ট ফি নির্ধারণের নিয়ম।',
        simpleExplanation: 'Provides rules for calculating valuation-based fees on property disputes and monetary recovery suits.',
      },
    ],
  },
  {
    id: 'bd-arbitration-act-2001',
    title: 'The Arbitration Act, 2001',
    titleBn: 'সালিশ আইন, ২০০১',
    shortTitle: 'Arbitration Act (সালিশ আইন)',
    alternateTitles: ['Act No. I of 2001', '২০০১ সালের ১ নং আইন', 'UNCITRAL Model Law Adaptation'],
    enactmentYear: 2001,
    actNumber: 'Act No. I of 2001',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 33,
    volumeCitation: 'The Bangladesh Code, Volume XXXIII (2001–2002), Act I of 2001',
    category: 'Civil Law & Procedure',
    categorySlug: 'civil-procedure',
    subcategories: ['Commercial Arbitration', 'Enforcement of Foreign Awards', 'Arbitral Tribunals', 'Setting Aside Awards (Sec 42)'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['arbitration', 'salish', 'foreign arbitral award', 'uncitral', 'section 7', 'section 42', 'সালিশ আইন', 'বাণিজ্যিক সালিশ'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '24th January 2001',
    commencementDate: '10th April 2001',
    lastAmendedYear: 2004,
    overview: 'Modern domestic and international commercial arbitration statute modelled on the UNCITRAL Model Law. Governs arbitral agreements, conduct of proceedings, judicial non-intervention, and recognition of foreign arbitral awards in Bangladesh.',
    overviewBn: 'ইউনসিট্রাল মডেল ল এর আদলে প্রণীত আধুনিক বাণিজ্যিক সালিশ ও আন্তর্জাতিক রোয়েদাদ কার্যকরকরণ আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-854.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/854',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 24 January 2001',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 58,
    relatedLawIds: ['bd-cpc-1908', 'bd-contract-act-1872'],
    sections: [
      {
        number: 'Section 7',
        title: 'General Principles and Judicial Non-Intervention',
        titleBn: 'সাধারণ মূলনীতি ও আদালতের হস্তক্ষেপ সীমাবদ্ধকরণ',
        content: 'Notwithstanding anything contained in any other law for the time being in force, in matters governed by this Act, no judicial authority shall intervene except where so provided in this Act.',
        contentBn: 'এই আইনের বিধান ব্যতীত অন্য কোনো ক্ষেত্রে আদালত সালিশ কার্যক্রমে হস্তক্ষেপ করিবে না।',
        simpleExplanation: 'Prohibits courts from interfering in arbitration matters unless explicitly authorized by the Act.',
      },
      {
        number: 'Section 42',
        title: 'Application for Setting Aside Arbitral Award',
        titleBn: 'সালিশি রোয়েদাদ বাতিলের জন্য আদালতে আবেদন',
        content: 'An arbitral award may be set aside by the Court only if the party making the application furnishes proof that a party was under some incapacity, the arbitration agreement is invalid, or the award is in conflict with public policy of Bangladesh.',
        contentBn: 'কেবলমাত্র চুক্তি বাতিল, এখতিয়ার বহির্ভূত আচরণ বা জনস্বার্থ পরিপন্থী হওয়ার সুনির্দিষ্ট কারণে রোয়েদাদ বাতিলের আবেদন করা যায়।',
        simpleExplanation: 'Provides very narrow, exhaustive grounds upon which a court can annul an arbitration award.',
      },
      {
        number: 'Section 45',
        title: 'Enforcement of Foreign Arbitral Awards (New York Convention)',
        titleBn: 'বিদেশি সালিশি রোয়েদাদ কার্যকরকরণ (নিউ ইয়র্ক কনভেনশন)',
        content: 'Any foreign arbitral award which would be enforceable under this Act shall be treated as binding for all purposes on the persons as between whom it was made, and may accordingly be relied on by any of those persons by way of defence, set off or otherwise in any legal proceedings in Bangladesh.',
        contentBn: 'নিউ ইয়র্ক কনভেনশনের আওতায় বিদেশি ট্রাইব্যুনালের প্রদত্ত রোয়েদাদ বাংলাদেশে দেওয়ানি ডিক্রির ন্যায় কার্যকর।',
        simpleExplanation: 'Ensures foreign international arbitration awards are recognized and directly enforced as civil court decrees in Bangladesh.',
      },
    ],
  },

  // 4. FAMILY AND PERSONAL STATUS LAW
  {
    id: 'bd-muslim-family-laws-1961',
    title: 'The Muslim Family Laws Ordinance, 1961',
    titleBn: 'মুসলিম পারিবারিক আইন অধ্যাদেশ, ১৯৬১',
    shortTitle: 'Muslim Family Laws (মুসলিম পারিবারিক আইন)',
    alternateTitles: ['Ordinance No. VIII of 1961', '১৯৬১ সালের ৮ নং অধ্যাদেশ'],
    enactmentYear: 1961,
    actNumber: 'Ordinance No. VIII of 1961',
    actType: 'Ordinance',
    era: 'pakistan-era',
    volumeNumber: 11,
    volumeCitation: 'The Bangladesh Code, Volume XI (1956–1961), Ordinance VIII',
    category: 'Family & Personal Status',
    categorySlug: 'family-personal',
    subcategories: ['Divorce / Talaq Procedure (Sec 7)', 'Polygamy Restrictions (Sec 6)', 'Orphaned Grandchildren Succession (Sec 4)', 'Maintenance (Sec 9)'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['muslim family laws', 'talaq', 'dower', 'denmohor', 'polygamy', 'section 7', 'section 4', 'section 9', 'তালাক', 'দেনমোহর', 'বহুবিবাহ', 'খোরপোষ'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '2nd March 1961',
    commencementDate: '15th July 1961',
    lastAmendedYear: 1986,
    overview: 'Governs Muslim marriage solemnization, registration, Talaq reconciliation procedures, restrictions on polygamy, inheritance rights of predeceased children’s offspring, and spousal maintenance in Bangladesh.',
    overviewBn: 'মুসলিম বিবাহ নিবন্ধন, বহুবিবাহ নিয়ন্ত্রণ, তালাক নোটিশ ও ৯০ দিনের সালিশি কার্যপদ্ধতি, দেনমোহর ও এতিম নাতি-নাতনির উত্তরাধিকার আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-305.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/305',
    officialGazetteCitation: 'Gazette of Pakistan Extraordinary, 2 March 1961 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 13,
    relatedLawIds: ['bd-family-courts-act-2023', 'bd-dowry-prohibition-2018'],
    sections: [
      {
        number: 'Section 4',
        title: 'Succession by Children of Predeceased Son or Daughter',
        titleBn: 'মৃত পুত্র বা কন্যার সন্তানদের উত্তরাধিকার',
        content: 'In the event of the death of any son or daughter of the propositus before the opening of the succession, the children of such son or daughter, if any, living at the time the succession opens, shall per stirpes receive a share equivalent to the share which such son or daughter, as the case may be, would have received if alive.',
        contentBn: 'সম্পত্তির মূল মালিকের মৃত্যুর পূর্বে কোনো সন্তান মারা গেলে, তার জীবিত সন্তানরা (এতিম পৌত্র/পৌত্রী) সেই পরিমাণ অংশ পাবে যা তাদের পিতা বা মাতা বেঁচে থাকলে পেতেন।',
        simpleExplanation: 'Protects orphaned grandchildren, giving them their deceased parent\'s share of inheritance.',
      },
      {
        number: 'Section 6',
        title: 'Polygamy Restrictions and Permission of Arbitration Council',
        titleBn: 'বহুবিবাহের ক্ষেত্রে সালিশি পরিষদের পূর্বানুমতি গ্রহণ',
        content: 'No man, during the subsistence of an existing marriage, shall, except with the previous permission in writing of the Arbitration Council, contract another marriage, nor shall any such marriage contracted without such permission be registered under this Ordinance.',
        contentBn: 'প্রথম স্ত্রী বর্তমান থাকা অবস্থায় দ্বিতীয় বিবাহ করতে হলে সালিশি পরিষদের নিকট লিখিত কারণ দেখিয়ে অনুমতি গ্রহণ বাধ্যতামূলক। অনুমতি ছাড়া বিবাহ করলে কারাদণ্ড ও দেনমোহর তাৎক্ষণিক পরিশোধযোগ্য।',
        simpleExplanation: 'Strictly restricts polygamy: A husband must obtain formal permission from the local Arbitration Council before taking a subsequent wife.',
      },
      {
        number: 'Section 7',
        title: 'Talaq Notice and Ninety-Day Reconciliation Procedure',
        titleBn: 'তালাকের নোটিশ ও ৯০ দিনের সমঝোতা প্রক্রিয়া',
        content: 'Any man who wishes to divorce his wife shall, as soon as may be after the pronouncement of Talaq in any form whatsoever, give the Chairman notice in writing of his having done so, and shall supply a copy thereof to the wife. Talaq shall not be effective until the expiration of ninety days from the day on which notice under sub-section (1) is delivered to the Chairman.',
        contentBn: 'তালাক ঘোষণার পর সংশ্লিষ্ট চেয়ারম্যান এবং স্ত্রীকে লিখিত নোটিশ প্রদান করতে হবে। নোটিশ প্রেরণের ৯০ দিন অতিবাহিত না হওয়া পর্যন্ত তালাক কার্যকর হইবে না।',
        simpleExplanation: 'A Talaq is not legally effective until 90 days after formal written notice is served on the Union Parishad / City Corporation Mayor and the wife.',
      },
      {
        number: 'Section 9',
        title: 'Maintenance of Wife (Khorposh)',
        titleBn: 'স্ত্রীর খোরপোষ বা ভরণপোষণ',
        content: 'If any husband fails to maintain his wife adequately, or where there are more wives than one, fails to maintain them equitably, the wife, or all or any of the wives, may apply to the Chairman who shall constitute an Arbitration Council to issue a certificate specifying the amount of maintenance.',
        contentBn: 'স্বামী স্ত্রীকে যথাযথ ভরণপোষণ না দিলে স্ত্রী সালিশি পরিষদ বা পারিবারিক আদালতে খোরপোষের জন্য আবেদন করতে পারেন।',
        simpleExplanation: 'Statutory right of the wife to receive monthly food, clothing, housing, and medical maintenance from the husband.',
      },
    ],
  },
  {
    id: 'bd-family-courts-act-2023',
    title: 'The Family Courts Act, 2023',
    titleBn: 'পারিবারিক আদালত আইন, ২০২৩',
    shortTitle: 'Family Courts Act (পারিবারিক আদালত আইন)',
    alternateTitles: ['Act No. X of 2023', '২০২৩ সালের ১০ নং আইন', 'Repealed & Replaced Family Courts Ordinance 1985'],
    enactmentYear: 2023,
    actNumber: 'Act No. X of 2023',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 45,
    volumeCitation: 'The Bangladesh Code, Volume XLV (2022–2023), Act X of 2023',
    category: 'Family & Personal Status',
    categorySlug: 'family-personal',
    subcategories: ['Dissolution of Marriage', 'Dower & Maintenance', 'Restitution of Conjugal Rights', 'Child Custody & Guardianship'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['family court', 'paribar adalat', 'dower', 'maintenance', 'custody', 'denmohor', 'section 5', 'পারিবারিক আদালত', 'দেনমোহর', 'খোরপোষ', 'অভিভাবকত্ব'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '15th February 2023',
    commencementDate: '15th February 2023',
    lastAmendedYear: 2023,
    overview: 'Updated 2023 statute consolidating exclusive Family Court jurisdiction over 5 core matters: dissolution of marriage, restitution of conjugal rights, dower (Denmohor), maintenance (Khorposh), and custody and guardianship of children across all religious communities.',
    overviewBn: 'বিবাহ বিচ্ছেদ, দেনমোহর, খোরপোষ, দাম্পত্য অধিকার পুনরুদ্ধার এবং সন্তানের হেফাজত ও অভিভাবকত্ব সংক্রান্ত বিরোধ নিষ্পত্তির একক আদালত।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1418.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1418',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 15 February 2023',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 28,
    relatedLawIds: ['bd-muslim-family-laws-1961', 'bd-guardians-wards-1890', 'bd-dowry-prohibition-2018'],
    sections: [
      {
        number: 'Section 5',
        title: 'Jurisdiction of Family Courts',
        titleBn: 'পারিবারিক আদালতের এখতিয়ার',
        content: 'Subject to the provisions of this Act, a Family Court shall have exclusive jurisdiction to entertain, try and dispose of any suit relating to: (a) dissolution of marriage, (b) restitution of conjugal rights, (c) dower, (d) maintenance, and (e) guardianship and custody of children.',
        contentBn: 'পারিবারিক আদালতের ৫টি সুনির্দিষ্ট এখতিয়ার: (ক) বিবাহ বিচ্ছেদ, (খ) দাম্পত্য অধিকার পুনরুদ্ধার, (গ) দেনমোহর, (ঘ) ভরণপোষণ, এবং (ঙ) সন্তানের অভিভাবকত্ব ও হেফাজত।',
        simpleExplanation: 'Grants exclusive jurisdiction over family disputes to Senior Assistant Judges sitting as Family Courts.',
      },
      {
        number: 'Section 10',
        title: 'Pre-trial Proceeding and Mandatory Reconciliation',
        titleBn: 'বিচার-পূর্ব শুনানি ও সমঝোতার প্রচেষ্টা',
        content: 'When the written statement is filed, the Family Court shall fix a date for pre-trial proceeding. The Court shall examine the plaint, written statement, and documents, and shall endeavor to effect a compromise or reconciliation between the parties.',
        contentBn: 'মূল বিচার শুরুর পূর্বে আদালত উভয় পক্ষকে উপস্থিত রেখে আপস-মীমাংসার সর্বাত্মক চেষ্টা গ্রহণ করবেন।',
        simpleExplanation: 'Mandates court-led reconciliation conferences between spouses before beginning trial.',
      },
      {
        number: 'Section 17',
        title: 'Appeals to District Judge Court',
        titleBn: 'জেলা জজ আদালতে আপিল',
        content: 'An appeal shall lie from a decree or decision passed by a Family Court to the Court of District Judge within thirty days of the passing of the decree or order.',
        contentBn: 'পারিবারিক আদালতের রায়ের বিরুদ্ধে ৩০ দিনের মধ্যে জেলা জজ আদালতে আপিল দায়ের করতে হয়।',
        simpleExplanation: 'Provides appeal rights to the District Judge with a 30-day filing deadline.',
      },
    ],
  },
  {
    id: 'bd-guardians-wards-1890',
    title: 'The Guardians and Wards Act, 1890',
    titleBn: 'অভিভাবক ও প্রতিপাল্য আইন, ১৮৯০',
    shortTitle: 'Guardians & Wards Act (অভিভাবক আইন)',
    alternateTitles: ['Act No. VIII of 1890', '১৮৯০ সালের ৮ নং আইন'],
    enactmentYear: 1890,
    actNumber: 'Act No. VIII of 1890',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 3,
    volumeCitation: 'The Bangladesh Code, Volume III (1882–1897), Act VIII of 1890',
    category: 'Family & Personal Status',
    categorySlug: 'family-personal',
    subcategories: ['Child Welfare Principle (Sec 17)', 'Custody Disputes (Hizanat)', 'Court Appointed Guardians', 'Property Administration'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['guardians and wards', 'custody', 'hizanat', 'child welfare', 'minor property', 'section 17', 'section 25', 'অভিভাবক', 'হেফাজত', 'সন্তানের কল্যাণ'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '21st March 1890',
    commencementDate: '1st July 1890',
    lastAmendedYear: 2012,
    overview: 'Core statute governing appointment of guardians over the person and property of minors. Establishes the paramount principle of the "Welfare of the Child" in all custody adjudications.',
    overviewBn: 'নাবালকের শরীর ও সম্পত্তির অভিভাবক নিয়োগ এবং সন্তানের হেফাজত নির্ধারণে শিশুর সর্বোত্তম কল্যাণের নীতি সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-59.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/59',
    officialGazetteCitation: 'Legislative Enactment Act VIII of 1890 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 53,
    relatedLawIds: ['bd-family-courts-act-2023', 'bd-muslim-family-laws-1961'],
    sections: [
      {
        number: 'Section 17',
        title: 'Matters to Be Considered by Court in Appointing Guardian (Welfare of the Child)',
        titleBn: 'অভিভাবক নিয়োগে আদালতের বিবেচ্য বিষয় (সন্তানের কল্যাণ)',
        content: 'In appointing or declaring the guardian of a minor, the Court shall, subject to the provisions of this section, be guided by what, consistently with the law to which the minor is subject, appears in the circumstances to be for the welfare of the minor.',
        contentBn: 'নাবালকের অভিভাবক নিয়োগে শিশুর বয়স, লিঙ্গ, ধর্ম, নৈতিক চরিত্র এবং শিশুর সামগ্রিক শারীরিক ও মানসিক কল্যাণই আদালতের প্রধান বিবেচ্য।',
        simpleExplanation: 'The welfare and best interest of the child overrides all competing parental claims in custody battles.',
      },
      {
        number: 'Section 25',
        title: 'Title of Guardian to Custody of Ward',
        titleBn: 'নাবালকের হেফাজত লাভে অভিভাবকের অধিকার',
        content: 'If a ward leaves or is removed from the custody of a guardian of his person, the Court, if of opinion that it will be for the welfare of the ward to return to the custody of the guardian, may make an order for his return.',
        contentBn: 'অভিভাবকের হেফাজত হতে নাবালককে অন্যায়ভাবে নিয়ে যাওয়া হলে শিশুর কল্যাণে তাকে ফিরিয়ে দেওয়ার আদেশ প্রদান।',
        simpleExplanation: 'Procedural vehicle used by parents to petition the court for restoration of child custody.',
      },
    ],
  },
  {
    id: 'bd-hindu-marriage-reg-2012',
    title: 'The Hindu Marriage Registration Act, 2012',
    titleBn: 'হিন্দু বিবাহ নিবন্ধন আইন, ২০১২',
    shortTitle: 'Hindu Marriage Registration (হিন্দু বিবাহ নিবন্ধন)',
    alternateTitles: ['Act No. XL of 2012', '২০১২ সালের ৪০ নং আইন'],
    enactmentYear: 2012,
    actNumber: 'Act No. XL of 2012',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 38,
    volumeCitation: 'The Bangladesh Code, Volume XXXVIII (2011–2012), Act XL of 2012',
    category: 'Family & Personal Status',
    categorySlug: 'family-personal',
    subcategories: ['Hindu Marriage Registrars', 'Optional Registration', 'Proof of Marriage', 'Certificate of Marriage'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['hindu marriage', 'marriage registration', 'marriage certificate', 'hindu bibaho', 'হিন্দু বিবাহ', 'নিবন্ধন'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '24th September 2012',
    commencementDate: '24th September 2012',
    lastAmendedYear: 2012,
    overview: 'Statutory framework introducing formal optional registration for Hindu marriages in Bangladesh, providing legal documentation, official marriage certificates, and protection of women’s rights.',
    overviewBn: 'বাংলাদেশে হিন্দু ধর্মাবলম্বীদের বিবাহ ঐচ্ছিক নিবন্ধনের বিধান ও সরকারি সনদ প্রদান সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1104.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1104',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 24 September 2012',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 9,
    relatedLawIds: ['bd-family-courts-act-2023', 'bd-special-marriage-1872'],
    sections: [
      {
        number: 'Section 3',
        title: 'Registration of Hindu Marriage (Optional)',
        titleBn: 'হিন্দু বিবাহ নিবন্ধন (ঐচ্ছিক)',
        content: 'Notwithstanding anything contained in any other law, custom or usage, any Hindu marriage solemnized in accordance with Hindu religious rites may be registered in accordance with the provisions of this Act.',
        contentBn: 'হিন্দু ধর্মীয় রীতি অনুসারে সম্পন্ন যেকোনো বিবাহ এই আইনের অধীনে সরকারিভাবে নিবন্ধন করা যাবে।',
        simpleExplanation: 'Authorizes official government registration of Hindu religious marriages.',
      },
      {
        number: 'Section 6',
        title: 'Evidentiary Value of Hindu Marriage Certificate',
        titleBn: 'হিন্দু বিবাহ সনদের সাক্ষ্যগত মূল্য',
        content: 'A certified copy of an entry in the Hindu Marriage Register signed by the Registrar shall be received in all courts as evidence of the marriage to which it relates.',
        contentBn: 'হিন্দু বিবাহ নিবন্ধক কর্তৃক প্রদত্ত সনদ আদালতে বিবাহের চূড়ান্ত প্রমাণ হিসেবে গণ্য হবে।',
        simpleExplanation: 'Provides conclusive legal evidence of marriage for passport, visa, inheritance, and court proceedings.',
      },
    ],
  },
  {
    id: 'bd-special-marriage-1872',
    title: 'The Special Marriage Act, 1872',
    titleBn: 'বিশেষ বিবাহ আইন, ১৮৭২',
    shortTitle: 'Special Marriage Act (বিশেষ বিবাহ আইন)',
    alternateTitles: ['Act No. III of 1872', '১৮৭২ সালের ৩ নং আইন', 'Civil Marriage Act'],
    enactmentYear: 1872,
    actNumber: 'Act No. III of 1872',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 2,
    volumeCitation: 'The Bangladesh Code, Volume II (1872–1882), Act III of 1872',
    category: 'Family & Personal Status',
    categorySlug: 'family-personal',
    subcategories: ['Inter-Faith Civil Marriage', 'Registrar of Special Marriages', 'Declaration & Witnesses', 'Dissolution of Civil Marriage'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['special marriage', 'civil marriage', 'inter-faith marriage', 'marriage registrar', 'বিশেষ বিবাহ', 'রেজিস্ট্রি বিবাহ'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '18th July 1872',
    commencementDate: '18th July 1872',
    lastAmendedYear: 1984,
    overview: 'Enables civil and inter-faith marriages between parties who do not profess the same traditional religious personal laws (Muslim, Hindu, Christian, Jewish, Buddhist, Sikh, or Parsi).',
    overviewBn: 'বিভিন্ন ধর্মাবলম্বীদের মধ্যে দেওয়ানি বা বিশেষ বিবাহ সম্পাদন ও সরকারি নিবন্ধনের আইনি বিধান।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-25.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/25',
    officialGazetteCitation: 'Legislative Enactment Act III of 1872 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 22,
    relatedLawIds: ['bd-family-courts-act-2023'],
    sections: [
      {
        number: 'Section 2',
        title: 'Conditions Upon Which Marriages Under Act May Be Celebrated',
        titleBn: 'যেসব শর্তাধীনে বিশেষ বিবাহ অনুষ্ঠিত হতে পারে',
        content: 'Marriages may be celebrated under this Act between persons neither of whom professes the Christian, the Jewish, the Hindu, the Muslim, the Parsi, the Buddhist, the Sikh or the Jaina religion, or between persons each of whom professes one or other of those religions.',
        contentBn: 'উভয় পক্ষের বয়স পুরুষ কমপক্ষে ২১ বছর এবং নারী কমপক্ষে ১৮ বছর হতে হবে এবং কোনো পক্ষের পূর্বের বৈধ স্বামী/স্ত্রী জীবিত থাকতে পারবে না।',
        simpleExplanation: 'Sets out legal age and capacity conditions for solemnizing a civil marriage.',
      },
    ],
  },
  {
    id: 'bd-dowry-prohibition-2018',
    title: 'The Dowry Prohibition Act, 2018',
    titleBn: 'যৌতুক নিরোধ আইন, ২০১৮',
    shortTitle: 'Dowry Prohibition Act (যৌতুক নিরোধ আইন)',
    alternateTitles: ['Act No. XXXIX of 2018', '২০১৮ সালের ৩৯ নং আইন', 'Repealed Dowry Prohibition Act 1980'],
    enactmentYear: 2018,
    actNumber: 'Act No. XXXIX of 2018',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 41,
    volumeCitation: 'The Bangladesh Code, Volume XLI (2018–2019), Act XXXIX of 2018',
    category: 'Family & Personal Status',
    categorySlug: 'family-personal',
    subcategories: ['Prohibition of Dowry Demand', 'Giving & Taking Dowry Penalties', 'False Case Safeguards (Sec 6)', 'Summary Magisterial Trials'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['dowry', 'joutuk', 'dowry demand', 'section 3', 'section 4', 'section 6', 'যৌতুক', 'যৌতুক নিরোধ'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '8th October 2018',
    commencementDate: '8th October 2018',
    lastAmendedYear: 2018,
    overview: 'Updated criminal legislation prohibiting the demand, giving, taking, or abetting of dowry in marriage contracts, and prescribing jail sentences for false and malicious dowry accusations.',
    overviewBn: 'বিবাহে প্রত্যক্ষ বা পরোক্ষভাবে যৌতুক দাবি, গ্রহণ বা প্রদান নিষিদ্ধকরণ এবং মিথ্যা মামলার দণ্ড সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1250.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1250',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 8 October 2018',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 10,
    relatedLawIds: ['bd-nari-o-shishu-2000', 'bd-penal-code-1860'],
    sections: [
      {
        number: 'Section 3 & 4',
        title: 'Penalty for Giving, Taking, or Demanding Dowry',
        titleBn: 'যৌতুক দাবি, গ্রহণ বা প্রদানের শাস্তি',
        content: 'If any person gives, takes, abets, or demands dowry directly or indirectly from the bride, groom, or their guardians, such person shall be punished with imprisonment up to five years or fine up to fifty thousand Taka or both.',
        contentBn: 'প্রত্যক্ষ বা পরোক্ষভাবে যৌতুক দাবি, প্রদান বা গ্রহণ করলে অনধিক ৫ বছর কারাদণ্ড বা ৫০,০০০ টাকা অর্থদণ্ড বা উভয় দণ্ডে দণ্ডিত হইবে।',
        simpleExplanation: 'Imposes up to 5 years imprisonment for demanding or taking wedding dowry.',
        penalty: 'Imprisonment up to 5 years or fine up to Tk 50,000 or both',
        isBailable: true,
        isCognizable: true,
      },
      {
        number: 'Section 6',
        title: 'Punishment for Filing False and Malicious Case',
        titleBn: 'মিথ্যা বা হয়রানিমূলক মামলা দায়েরের শাস্তি',
        content: 'If any person institutes a false or frivolous case under this Act with intent to harm the accused, such complainant shall be punished with imprisonment up to five years or fine up to fifty thousand Taka or both.',
        contentBn: 'কোনো ব্যক্তি অসৎ উদ্দেশ্যে হয়রানি করার জন্য মিথ্যা যৌতুকের মামলা দায়ের করলে তাকে ৫ বছর কারাদণ্ড ও ৫০,০০০ টাকা জরিমানার মুখোমুখি হতে হবে।',
        simpleExplanation: 'Criminalizes false and vexatious dowry complaints to protect innocent in-laws.',
        penalty: 'Imprisonment up to 5 years and fine',
      },
    ],
  },

  // 5. PROPERTY AND LAND LAW
  {
    id: 'bd-transfer-property-1882',
    title: 'The Transfer of Property Act, 1882',
    titleBn: 'সম্পত্তি হস্তান্তর আইন, ১৮৮২',
    shortTitle: 'Transfer of Property Act (সম্পত্তি হস্তান্তর আইন)',
    alternateTitles: ['Act No. IV of 1882', '১৮৮২ সালের ৪ নং আইন'],
    enactmentYear: 1882,
    actNumber: 'Act No. IV of 1882',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 2,
    volumeCitation: 'The Bangladesh Code, Volume II (1872–1882), Act IV of 1882',
    category: 'Property & Real Estate',
    categorySlug: 'property-land',
    subcategories: ['Sale of Land (Sec 54)', 'Mortgages (Sec 58)', 'Leases & Tenancies (Sec 105)', 'Lis Pendens (Sec 52)', 'Gifts (Sec 122)'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs / Ministry of Land',
    keywords: ['transfer of property', 'land sale', 'mortgage', 'lis pendens', 'section 52', 'section 54', 'section 53a', 'section 58', 'সম্পত্তি হস্তান্তর', 'বায়না', 'বন্ধক'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '17th February 1882',
    commencementDate: '1st July 1882',
    lastAmendedYear: 2004,
    lastAmendmentAct: 'Act No. XXVI of 2004',
    overview: 'The fundamental substantive enactment regulating the inter vivos transfer of immovable property in Bangladesh. Governs sales of land, mortgages, leases, exchanges, gifts, and doctrine of lis pendens.',
    overviewBn: 'স্থাবর সম্পত্তি বিক্রয়, বন্ধক, ইজারা, দান ও হস্তান্তর সংক্রান্ত মূল সারগর্ভ আইন। বায়না চুক্তি ও রেজিস্ট্রেশন বাধ্যবাধকতা নিয়ন্ত্রণ করে।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-48.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/48',
    officialGazetteCitation: 'Legislative Enactment Act IV of 1882 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 137,
    relatedLawIds: ['bd-registration-act-1908', 'bd-sata-1950', 'bd-land-crime-prevention-2023'],
    sections: [
      {
        number: 'Section 52',
        title: 'Transfer of Property Pending Suit Relating Thereto (Lis Pendens)',
        titleBn: 'মোকদ্দমা চলাকালে সম্পত্তি হস্তান্তরের ফলাফল (লিস পেনডেন্স)',
        content: 'During the pendency in any Court of any suit or proceeding which is not collusive and in which any right to immovable property is directly and specifically in question, the property cannot be transferred or otherwise dealt with by any party to the suit or proceeding so as to affect the rights of any other party thereto under any decree or order which may be made therein.',
        contentBn: 'আদালতে মোকদ্দমা চলাকালীন বিরোধীয় জমি হস্তান্তর করলে তা মামলার চূড়ান্ত রায়ের অধীন হবে এবং ক্রেতা পৃথক স্বত্ব দাবি করতে পারবে না।',
        simpleExplanation: 'Doctrine of Lis Pendens: Transfers of contested property made during an active lawsuit are legally subordinate to the court’s final decree.',
      },
      {
        number: 'Section 53A',
        title: 'Part Performance of Contract for Transfer of Immovable Property',
        titleBn: 'স্থাবর সম্পত্তি হস্তান্তর চুক্তির আংশিক কার্যকরকরণ',
        content: 'Where any person contracts to transfer for consideration any immovable property by writing signed by him or on his behalf from which the terms necessary to constitute the transfer can be ascertained with reasonable certainty, and the transferee has, in part performance of the contract, taken possession of the property, the transferor is debarred from enforcing against the transferee any right in respect of the property.',
        contentBn: 'বায়না চুক্তির অধীনে দখল গ্রহণকারী ক্রেতার অধিকারের সুরক্ষা। (২০০৪ সালের সংশোধনী অনুসারে বায়না চুক্তি ও দখল হস্তান্তরের ক্ষেত্রে বাধ্যতামূলক রেজিস্ট্রি আবশ্যক)।',
        simpleExplanation: 'Shields a buyer who took physical possession and paid consideration under a written contract against being ousted by the seller.',
      },
      {
        number: 'Section 54',
        title: 'Sale Defined and Mandatory Registered Instrument Requirement',
        titleBn: 'বিক্রয়ের সংজ্ঞা ও দলিল রেজিস্ট্রেশন বাধ্যবাধকতা',
        content: 'Sale is a transfer of ownership in exchange for a price paid or promised or part-paid and part-promised. Such transfer, in the case of tangible immovable property of the value of one hundred Taka and upwards, can be made only by a registered instrument.',
        contentBn: '১০০ টাকা বা তদূর্ধ্ব মূল্যের যেকোনো স্থাবর জমি বিক্রয় কেবল নিবন্ধিত দলিলের মাধ্যমেই বৈধভাবে কার্যকর হতে পারে। মৌখিক বা নোটারি চুক্তি বাতিল।',
        simpleExplanation: 'All land sales in Bangladesh must be executed through an officially registered deed; verbal or unnotarized sales are legally void.',
      },
      {
        number: 'Section 58',
        title: 'Mortgage, Mortgagor, Mortgagee, Mortgage-Money and Mortgage-Deed Defined',
        titleBn: 'বন্ধক, বন্ধকদাতা, বন্ধকগ্রহীতা ও বন্ধকি দলিলের সংজ্ঞা',
        content: 'Defines simple mortgage, mortgage by conditional sale, usufructuary mortgage, English mortgage, mortgage by deposit of title-deeds, and anomalous mortgage.',
        contentBn: 'ঋণ বা দায়ের জামানত হিসেবে জমি বন্ধক রাখার বিভিন্ন প্রকারভেদ এবং ব্যাংকিং বন্ধক সংক্রান্ত বিধিবিধান।',
        simpleExplanation: 'Defines statutory classifications of mortgages used by financial institutions and private lenders.',
      },
    ],
  },
  {
    id: 'bd-registration-act-1908',
    title: 'The Registration Act, 1908',
    titleBn: 'রেজিস্ট্রেশন আইন, ১৯০৮',
    shortTitle: 'Registration Act (রেজিস্ট্রেশন আইন)',
    alternateTitles: ['Act No. XVI of 1908', '১৯০৮ সালের ১৬ নং আইন'],
    enactmentYear: 1908,
    actNumber: 'Act No. XVI of 1908',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 4,
    volumeCitation: 'The Bangladesh Code, Volume IV (1898–1908), Act XVI of 1908',
    category: 'Property & Real Estate',
    categorySlug: 'property-land',
    subcategories: ['Compulsory Registration (Sec 17)', 'Sub-Registry Offices', 'Unregistered Documents Invalidity (Sec 49)', 'Land Sale Deeds'],
    ministry: 'Directorate of Registration / Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['registration act', 'sub registry', 'deed registration', 'section 17', 'section 49', 'dolil', 'রেজিস্ট্রেশন আইন', 'সাব কবলা দলিল', 'হেবা দলিল'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '18th December 1908',
    commencementDate: '1st January 1909',
    lastAmendedYear: 2004,
    lastAmendmentAct: 'Act No. XXV of 2004',
    overview: 'Regulates the compulsory and optional registration of land deeds, gift instruments (Heba), mortgages, leases, and powers of attorney in Sub-Registry offices throughout Bangladesh.',
    overviewBn: 'সাব-রেজিস্ট্রি অফিসে জমি বিক্রয়, হেবা, বন্ধক, আমমোক্তারনামা ও সাফ-কবলা দলিলের বাধ্যতামূলক নিবন্ধন সংক্রান্ত মূল আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-93.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/93',
    officialGazetteCitation: 'Legislative Enactment Act XVI of 1908 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 93,
    relatedLawIds: ['bd-transfer-property-1882', 'bd-land-crime-prevention-2023'],
    sections: [
      {
        number: 'Section 17',
        title: 'Documents of Which Registration Is Compulsory',
        titleBn: 'যেসব দলিল নিবন্ধন করা বাধ্যতামূলক',
        content: 'The following documents shall be registered: (a) instruments of gift of immovable property, (b) other non-testamentary instruments which purport or operate to create, declare, assign, limit or extinguish any right, title or interest of the value of one hundred Taka and upwards, to or in immovable property, (c) contract for sale (Baina-Patra), and (d) instruments of mortgage.',
        contentBn: 'স্থাবর সম্পত্তির দানপত্র (হেবা সহ), বিক্রয় চুক্তি (বায়না), সাফ-কবলা ও বন্ধকি দলিল সাব-রেজিস্ট্রার অফিসে বাধ্যতামূলকভাবে রেজিস্ট্রি করতে হবে।',
        simpleExplanation: 'Strictly mandates that land transfers, gifts, and sale contracts must be registered to have any legal validity.',
      },
      {
        number: 'Section 49',
        title: 'Effect of Non-Registration of Documents Required to Be Registered',
        titleBn: 'বাধ্যতামূলক নিবন্ধনযোগ্য দলিল রেজিস্ট্রি না করার ফলাফল',
        content: 'No document required by section 17 or by any provision of the Transfer of Property Act, 1882 to be registered shall affect any immovable property comprised therein, or be received as evidence of any transaction affecting such property, unless it has been registered.',
        contentBn: 'আইনত বাধ্যতামূলক দলিল রেজিস্ট্রি করা না হলে তা সম্পত্তিতে কোনো স্বত্ব সৃষ্টি করবে না এবং আদালতে সাক্ষ্য হিসেবে গ্রহণযোগ্য হবে না।',
        simpleExplanation: 'Unregistered land documents transfer no legal title and are inadmissible in court as evidence of ownership.',
      },
    ],
  },
  {
    id: 'bd-sata-1950',
    title: 'The State Acquisition and Tenancy Act, 1950',
    titleBn: 'রাষ্ট্রীয় অধিগ্রহণ ও প্রজাস্বত্ব আইন, ১৯৫০',
    shortTitle: 'SATA 1950 (প্রজাস্বত্ব আইন)',
    alternateTitles: ['East Bengal Act No. XXVIII of 1951', '১৯৫০ সালের ২৮ নং আইন', 'Tenancy Act'],
    enactmentYear: 1950,
    actNumber: 'East Bengal Act No. XXVIII of 1951',
    actType: 'Act of Parliament',
    era: 'pakistan-era',
    volumeNumber: 9,
    volumeCitation: 'The Bangladesh Code, Volume IX (1947–1950), Act XXVIII',
    category: 'Property & Real Estate',
    categorySlug: 'property-land',
    subcategories: ['Abolition of Zamindari', 'Right of Pre-emption (Sec 96)', 'Alluvion & Diluvion (Sec 86/87)', 'Land Records & Khatian (Sec 143/144)'],
    ministry: 'Ministry of Land',
    keywords: ['sata', 'tenancy act', 'pre-emption', 'section 96', 'khatian', 'namjari', 'mutation', 'zamindari abolition', 'প্রজাস্বত্ব আইন', 'অগ্রক্রয়', 'নামজারি'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '16th February 1951',
    commencementDate: '16th February 1951',
    lastAmendedYear: 2006,
    overview: 'Landmark land reform statute abolishing the colonial Zamindari system, vesting agricultural land ownership in raiyats, regulating statutory pre-emption rights, alluvion/diluvion river erosion, and preparation of land records (Khatian and mutation).',
    overviewBn: 'জমিদারি প্রথা বিলোপকারী ও প্রজাস্বত্ব প্রতিষ্ঠা সংক্রান্ত ঐতিহাসিক ভূমি আইন। অগ্রক্রয় (Pre-emption), নামজারি ও খতিয়ান সংশোধন নিয়ন্ত্রণ করে।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-241.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/241',
    officialGazetteCitation: 'Dacca Gazette Extraordinary, 16 May 1951 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 152,
    relatedLawIds: ['bd-transfer-property-1882', 'bd-registration-act-1908', 'bd-land-crime-prevention-2023'],
    sections: [
      {
        number: 'Section 86 & 87',
        title: 'Abatement of Rent and Re-vesting of Land on Diluvion and Alluvion',
        titleBn: 'নদী সিকস্তি (বিলীন) ও পয়স্তি (জাগ্রত) জমির স্বত্ব',
        content: 'If the holding of a raiyat is lost by river diluvion, rent is abated. When such land reappears (alluvion) within thirty years, the former owner has the right to reclaim it subject to payment of rent.',
        contentBn: 'নদী ভাঙনে জমি বিলীন হলে খাজনা মওকুফ এবং ৩০ বছরের মধ্যে নদী চর হিসেবে পুনরায় জেগে উঠলে পূর্বের মালিকের মালিকানা পুনঃপ্রতিষ্ঠা।',
        simpleExplanation: 'Protects river erosion victims by granting a 30-year statutory right to reclaim alluvial lands that resurface.',
      },
      {
        number: 'Section 96',
        title: 'Right of Pre-emption of Co-sharer Tenants and Contiguous Land Owners',
        titleBn: 'সহ-শরিক ও সংলগ্ন জমির মালিকের অগ্রক্রয়াধিকার (Pre-emption)',
        content: 'If a portion or share of a holding of a raiyat is sold to a stranger, any co-sharer tenant in the holding by inheritance may apply to the Court for the purchase of the said portion or share within two months of the service of notice or within two months of knowledge of sale.',
        contentBn: 'উত্তরাধিকারসূত্রে সহ-শরিকের অংশ বাইরের কারো নিকট বিক্রি করা হলে অপর শরিকরা আদালতে টাকা জমা দিয়ে জমিটি পূর্বে ক্রয়ের অধিকার দাবি করতে পারেন।',
        simpleExplanation: 'Allows ancestral co-sharers to repurchase family land sold to outsiders by filing a pre-emption petition within statutory deadlines.',
      },
    ],
  },
  {
    id: 'bd-land-crime-prevention-2023',
    title: 'The Land Crime Prevention and Redress Act, 2023',
    titleBn: 'ভূমি অপরাধ প্রতিরোধ ও প্রতিকার আইন, ২০২৩',
    shortTitle: 'Land Crime Prevention Act (ভূমি অপরাধ প্রতিরোধ আইন)',
    alternateTitles: ['Act No. XXVIII of 2023', '২০২৩ সালের ২৮ নং আইন', 'Bhumi Oporadh Protirodh Ain 2023'],
    enactmentYear: 2023,
    actNumber: 'Act No. XXVIII of 2023',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 45,
    volumeCitation: 'The Bangladesh Code, Volume XLV (2022–2023), Act XXVIII of 2023',
    category: 'Property & Real Estate',
    categorySlug: 'property-land',
    subcategories: ['Forged Deeds & Fake Records', 'Illegal Land Grabbing', 'Unauthorized Encroachment', 'Summary Administrative Eviction'],
    ministry: 'Ministry of Land / Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['land crime', 'fake deed', 'land grab', 'illegal possession', 'forgery', 'section 4', 'section 7', 'ভূমি অপরাধ', 'জাল দলিল', 'জমি দখল'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '18th September 2023',
    commencementDate: '18th September 2023',
    lastAmendedYear: 2023,
    overview: 'Landmark reform criminalizing fraudulent land practices, counterfeit deed creation, deceptive mutation records, illegal land grabbing, and coercive dispossession of genuine title-holders. Empowers Executive Magistrates and Judicial Magistrates with summary redress powers.',
    overviewBn: 'জাল দলিল তৈরি, প্রতারণামূলক নামজারি, জোরপূর্বক জমি দখল এবং ভূমি প্রতারণা প্রতিরোধে কঠোর ফৌজদারি দণ্ড ও দ্রুত প্রতিকারের ঐতিহাসিক আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1431.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1431',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 18 September 2023',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 26,
    relatedLawIds: ['bd-transfer-property-1882', 'bd-registration-act-1908', 'bd-penal-code-1860'],
    sections: [
      {
        number: 'Section 4',
        title: 'Punishment for Forging Land Deeds and Creating Fake Records',
        titleBn: 'জাল দলিল তৈরি ও মিথ্যা রেকর্ড সৃষ্টির শাস্তি',
        content: 'Whoever makes or executes any false, forged or fabricated land deed, power of attorney, mutation record, or court decree with intent to fraudulently claim ownership of land shall be punished with imprisonment for a term up to seven years and fine.',
        contentBn: 'জমি আত্মসাতের উদ্দেশ্যে জাল সাফ-কবলা, ভুয়া আমমোক্তারনামা বা ভুয়া নামজারি খতিয়ান তৈরি করিলে অনধিক ৭ বছর কারাদণ্ড এবং অর্থদণ্ডে দণ্ডিত হইবে।',
        simpleExplanation: 'Imposes up to 7 years imprisonment for fabricating forged title deeds or fraudulent mutation documents.',
        penalty: 'Imprisonment up to 7 years and fine',
        isBailable: false,
        isCognizable: true,
      },
      {
        number: 'Section 7',
        title: 'Punishment for Illegal Land Grabbing and Coercive Possession',
        titleBn: 'অবৈধভাবে জমি দখল ও জোরপূর্বক দখলের শাস্তি',
        content: 'Whoever enters upon, dispossesses, or unlawfully occupies any land without legal title and against the consent of the lawful owner shall be punished with imprisonment up to two years and fine.',
        contentBn: 'বৈধ স্বত্ব ব্যতিরেকে জোরপূর্বক অন্যের জমি দখল বা বেদখল করিলে অনধিক ২ বছর কারাদণ্ড ও অর্থদণ্ড প্রদেয়।',
        simpleExplanation: 'Directly criminalizes illegal land grabbing and coercive trespassing.',
        penalty: 'Imprisonment up to 2 years and fine',
      },
      {
        number: 'Section 15',
        title: 'Summary Recovery of Possession by Executive Authority',
        titleBn: 'প্রশাসনিক কর্তৃপক্ষ কর্তৃক দ্রুত দখল পুনরুদ্ধার ও উচ্ছেদ',
        content: 'Empowers District Magistrates, Additional District Magistrates, and Upazila Nirbahi Officers (UNO) upon police enquiry to summarily evict unauthorized occupants and restore land possession to genuine recorded owners.',
        contentBn: 'জেলা প্রশাসক ও উপজেলা নির্বাহী অফিসারকে প্রাথমিক তদন্তের ভিত্তিতে অবৈধ দখলদারকে দ্রুত উচ্ছেদ করে প্রকৃত মালিককে জমি বুঝিয়ে দেওয়ার ক্ষমতা প্রদান।',
        simpleExplanation: 'Provides rapid administrative eviction of land grabbers without waiting for years of civil litigation.',
      },
    ],
  },
];
