import { BangladeshLawRecord } from '../bdcode-architecture';

export const COMMERCIAL_BANKING_TAX_LAWS: BangladeshLawRecord[] = [
  // 6. LABOUR AND EMPLOYMENT LAW
  {
    id: 'bd-labour-act-2006',
    title: 'The Bangladesh Labour Act, 2006',
    titleBn: 'বাংলাদেশ শ্রম আইন, ২০০৬',
    shortTitle: 'Labour Act (শ্রম আইন)',
    alternateTitles: ['Act No. XLII of 2006', '২০০৬ সালের ৪২ নং আইন', 'Bangladesh Labor Act 2006'],
    enactmentYear: 2006,
    actNumber: 'Act No. XLII of 2006',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 35,
    volumeCitation: 'The Bangladesh Code, Volume XXXV (2005–2006), Act XLII of 2006',
    category: 'Labor & Employment',
    categorySlug: 'labor-employment',
    subcategories: ['Working Hours & Overtime', 'Termination & Severance (Sec 26)', 'Maternity Welfare (Sec 46)', 'Trade Unions & Collective Bargaining', 'Labour Courts (Sec 214)'],
    ministry: 'Ministry of Labour and Employment',
    keywords: ['labour act', 'shrom ain', 'termination', 'overtime', 'maternity benefit', 'trade union', 'section 26', 'section 100', 'section 108', 'labour court', 'শ্রম আইন', 'ওভারটাইম', 'প্রসূতি কল্যাণ'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '11th October 2006',
    commencementDate: '11th October 2006',
    lastAmendedYear: 2018,
    lastAmendmentAct: 'Act No. XL of 2018',
    overview: 'Comprehensive statutory code consolidating the rights and conditions of service for workers in commercial and industrial establishments in Bangladesh. Regulates worker classifications, severance benefits, maternity leave (16 weeks), working hours (48h/week), double overtime, factory health and safety, trade unions, and Labour Court jurisdiction.',
    overviewBn: 'শ্রমিকদের কর্মসংস্থান, ছুটি, মজুরি, প্রসূতি কল্যাণ, ওভারটাইম, ট্রেড ইউনিয়ন এবং শ্রম আদালতের বিচার পদ্ধতি সংক্রান্ত সমন্বিত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-957.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/957',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 11 October 2006',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 354,
    relatedLawIds: ['bd-epz-labour-2019', 'bd-contract-act-1872'],
    sections: [
      {
        number: 'Section 4',
        title: 'Classification of Workers and Period of Probation',
        titleBn: 'শ্রমিকদের শ্রেণিবিন্যাস ও শিক্ষানবিশী কাল',
        content: 'Workers employed in any establishment shall be classified into: (a) apprentice, (b) badli, (c) casual, (d) temporary, (e) probationer, (f) permanent, and (g) seasonal. The period of probation for a worker whose function is of clerical nature shall be six months and for other workers three months.',
        contentBn: 'প্রতিষ্ঠানে কর্মরত শ্রমিকদের ৭টি শ্রেণিতে বিভক্ত করা হয়েছে এবং কেরানি পদের জন্য ৬ মাস ও অন্যান্য পদের জন্য ৩ মাস শিক্ষানবিসকাল নির্ধারিত।',
        simpleExplanation: 'Categorizes workers and defines the statutory probation duration before permanent tenure.',
      },
      {
        number: 'Section 26',
        title: 'Termination of Employment by Employer Otherwise Than by Dismissal',
        titleBn: 'বরখাস্ত ব্যতীত অন্যভাবে মালিক কর্তৃক শ্রমিকের চাকরি অবসান',
        content: 'The employment of a permanent worker may be terminated by the employer upon giving 120 days notice in writing for rated workers, or 60 days notice for other workers, or by paying wages in lieu of notice. The worker is entitled to compensation at the rate of 30 days wages for every completed year of service.',
        contentBn: 'স্থায়ী শ্রমিককে চাকরি থেকে অব্যাহতি দিলে ১২০ দিন বা ৬০ দিনের লিখিত নোটিশ বা সমপরিমাণ মজুরি এবং প্রতি পূর্ণ কর্মবছরের জন্য ৩০ দিনের মূল মজুরি সমপরিমাণ ক্ষতিপূরণ প্রদান বাধ্যতামূলক।',
        simpleExplanation: 'Mandates advance written notice and statutory severance gratuity (30 days wages per service year) for no-fault terminations.',
      },
      {
        number: 'Section 46',
        title: 'Payment of Maternity Benefit',
        titleBn: 'প্রসূতি কল্যাণ সুবিধা পরিশোধের বাধ্যবাধকতা',
        content: 'Every woman employed in an establishment who has worked for not less than six months immediately preceding the day of delivery shall be entitled to the payment of maternity benefit for eight weeks preceding and eight weeks following delivery (total 16 weeks) with full average daily wages.',
        contentBn: 'সন্তান প্রসবের পূর্বে ৮ সপ্তাহ এবং প্রসবের পরে ৮ সপ্তাহ (মোট ১৬ সপ্তাহ) পূর্ণ মজুরিসহ প্রসূতি ছুটি ও কল্যাণ সুবিধা প্রদান করতে হবে।',
        simpleExplanation: 'Provides 16 weeks of fully paid statutory maternity leave to female employees.',
      },
      {
        number: 'Section 100',
        title: 'Daily Working Hours',
        titleBn: 'দৈনিক কাজের কর্মঘণ্টা',
        content: 'No adult worker shall ordinarily be required or allowed to work in an establishment for more than eight hours in any day: Provided that, subject to the provisions of section 108, any such worker may work in an establishment not exceeding ten hours in any day.',
        contentBn: 'সাধারণভাবে কোনো প্রাপ্তবয়স্ক শ্রমিককে দিনে ৮ ঘণ্টার অধিক কাজ করতে বাধ্য করা যাবে না; তবে ওভারটাইম সহ দিনে সর্বোচ্চ ১০ ঘণ্টা পর্যন্ত কাজ করা যেতে পারে।',
        simpleExplanation: 'Standard working day is 8 hours, capped at 10 hours including statutory overtime.',
      },
      {
        number: 'Section 108',
        title: 'Extra Allowance for Overtime',
        titleBn: 'অতিরিক্ত কাজের জন্য অতিরিক্ত ভাতা (ওভারটাইম দ্বিগুণ মজুরি)',
        content: 'Where a worker works in an establishment on any day for more than nine hours or for more than forty-eight hours in any week, he shall, in respect of overtime work, be entitled to allowance at the rate of twice his ordinary rate of basic wage and dearness allowance.',
        contentBn: 'দৈনিক ৮ ঘণ্টার অতিরিক্ত বা সপ্তাহে ৪৮ ঘণ্টার বেশি কাজ করলে প্রতি ঘণ্টার জন্য মূল মজুরির দ্বিগুণ (Double Rate) হারে ওভারটাইম ভাতা প্রদান বাধ্যতামূলক।',
        simpleExplanation: 'Requires employers to compensate overtime work at twice the standard hourly basic wage rate.',
      },
      {
        number: 'Section 214',
        title: 'Establishment of Labour Courts',
        titleBn: 'শ্রম আদালত প্রতিষ্ঠা ও বিচারিক এখতিয়ার',
        content: 'The Government may, by notification in the official Gazette, establish as many Labour Courts as it considers necessary to adjudicate industrial disputes, wage claims, illegal dismissals, and unfair labour practices.',
        contentBn: 'শ্রমিক ও মালিকের মধ্যকার বিরোধ নিষ্পত্তি, বকেয়া মজুরি আদায় এবং বেআইনি চাকরিচ্যুতির বিরুদ্ধে দ্রুত বিচারের জন্য শ্রম আদালত প্রতিষ্ঠা।',
        simpleExplanation: 'Provides dedicated judicial tribunals (Chaired by a District Judge with worker and employer members) for labour dispute adjudication.',
      },
    ],
  },
  {
    id: 'bd-epz-labour-2019',
    title: 'The Bangladesh EPZ Labour Act, 2019',
    titleBn: 'বাংলাদেশ ইপিজেড শ্রম আইন, ২০১৯',
    shortTitle: 'EPZ Labour Act (ইপিজেড শ্রম আইন)',
    alternateTitles: ['Act No. I of 2019', '২০১৯ সালের ১ নং আইন'],
    enactmentYear: 2019,
    actNumber: 'Act No. I of 2019',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 41,
    volumeCitation: 'The Bangladesh Code, Volume XLI (2018–2019), Act I of 2019',
    category: 'Labor & Employment',
    categorySlug: 'labor-employment',
    subcategories: ['Export Processing Zones', 'Workers Welfare Associations', 'EPZ Labour Tribunals', 'BEPZA Regulations'],
    ministry: 'Prime Minister’s Office / BEPZA',
    keywords: ['epz labour', 'bepza', 'workers welfare association', 'export processing zone', 'ইপিজেড', 'শ্রম আইন'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '28th February 2019',
    commencementDate: '28th February 2019',
    lastAmendedYear: 2019,
    overview: 'Specialized employment legislation governing industrial units situated within Bangladesh Export Processing Zones (EPZs). Regulates Workers Welfare Associations (WWA), EPZ dispute resolution, and dedicated EPZ Labour Tribunals.',
    overviewBn: 'রপ্তানি প্রক্রিয়াকরণ অঞ্চলে (ইপিজেড) কর্মরত শ্রমিকদের অধিকার, কল্যাণ সমিতি গঠন ও বিরোধ নিষ্পত্তির বিশেষ আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1273.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1273',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 28 February 2019',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 209,
    relatedLawIds: ['bd-labour-act-2006', 'bd-companies-act-1994'],
    sections: [
      {
        number: 'Section 95',
        title: 'Constitution of Workers Welfare Association (WWA)',
        titleBn: 'শ্রমিক কল্যাণ সমিতি গঠন',
        content: 'Workers in an EPZ industrial enterprise have the statutory right to form and register a Workers Welfare Association (WWA) to act as collective bargaining agent (CBA).',
        contentBn: 'ইপিজেডের কারখানায় কর্মরত শ্রমিকদের ট্রেড ইউনিয়নের সমতুল্য শ্রমিক কল্যাণ সমিতি গঠনের আইনি অধিকার।',
        simpleExplanation: 'Authorizes collective worker representation within export processing industrial zones.',
      },
    ],
  },

  // 7. COMMERCIAL, CORPORATE, AND CONTRACT LAW
  {
    id: 'bd-contract-act-1872',
    title: 'The Contract Act, 1872',
    titleBn: 'চুক্তি আইন, ১৮৭২',
    shortTitle: 'Contract Act (চুক্তি আইন)',
    alternateTitles: ['Act No. IX of 1872', '১৮৭২ সালের ৯ নং আইন'],
    enactmentYear: 1872,
    actNumber: 'Act No. IX of 1872',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 2,
    volumeCitation: 'The Bangladesh Code, Volume II (1872–1882), Act IX of 1872',
    category: 'Commercial & Corporate Law',
    categorySlug: 'commercial-contract',
    subcategories: ['Offer & Acceptance', 'Breach of Contract & Damages (Sec 73)', 'Indemnity & Guarantee', 'Bailment & Pledge', 'Agency'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['contract act', 'chukti ain', 'offer acceptance', 'consideration', 'breach of contract', 'section 73', 'damages', 'guarantee', 'চুক্তি আইন', 'ক্ষতিপূরণ'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '25th April 1872',
    commencementDate: '1st September 1872',
    lastAmendedYear: 2012,
    overview: 'The fundamental statute governing creation, performance, and enforcement of legal agreements and commercial contracts in Bangladesh. Governs offer, acceptance, lawful consideration, void contracts, indemnity, guarantees, and contractual breach remedies.',
    overviewBn: 'বাংলাদেশে চুক্তি প্রণয়ন, কার্যকারিতা, জামানত, প্রতিনিধিত্ব এবং চুক্তি ভঙ্গের ক্ষতিপূরণ সংক্রান্ত মূল বাণিজ্যিক আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-26.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/26',
    officialGazetteCitation: 'Legislative Enactment Act IX of 1872 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 238,
    relatedLawIds: ['bd-companies-act-1994', 'bd-sale-of-goods-1930', 'bd-specific-relief-1877'],
    sections: [
      {
        number: 'Section 10',
        title: 'What Agreements Are Contracts',
        titleBn: 'কোন চুক্তিগুলো আইনত বলবৎযোগ্য চুক্তি',
        content: 'All agreements are contracts if they are made by the free consent of parties competent to contract, for a lawful consideration and with a lawful object, and are not hereby expressly declared to be void.',
        contentBn: 'চুক্তি সম্পাদনে সক্ষম পক্ষগণের স্বাধীন সম্মতি, আইনসম্মত প্রতিদান এবং বৈধ উদ্দেশ্যে সম্পাদিত সকল সম্মতিই আইনত বলবৎযোগ্য চুক্তি।',
        simpleExplanation: 'Sets the foundational criteria for a legally binding contract in Bangladesh.',
      },
      {
        number: 'Section 73',
        title: 'Compensation for Loss or Damage Caused by Breach of Contract',
        titleBn: 'চুক্তি ভঙ্গের কারণে ক্ষতি বা লোকসানের ক্ষতিপূরণ',
        content: 'When a contract has been broken, the party who suffers by such breach is entitled to receive, from the party who has broken the contract, compensation for any loss or damage caused to him thereby, which naturally arose in the usual course of things from such breach.',
        contentBn: 'চুক্তি ভঙ্গকারী পক্ষের নিকট থেকে ক্ষতিগ্রস্ত পক্ষ চুক্তিভঙ্গের ফলে স্বাভাবিকভাবে সৃষ্ট প্রকৃত ক্ষতির আর্থিক ক্ষতিপূরণ পাওয়ার অধিকারী।',
        simpleExplanation: 'Codifies the rule in Hadley v Baxendale: Injured parties can claim direct, foreseeable damages for breach of contract.',
      },
    ],
  },
  {
    id: 'bd-companies-act-1994',
    title: 'The Companies Act, 1994',
    titleBn: 'কোম্পানি আইন, ১৯৯৪',
    shortTitle: 'Companies Act (কোম্পানি আইন)',
    alternateTitles: ['Act No. XVIII of 1994', '১৯৯৪ সালের ১৮ নং আইন'],
    enactmentYear: 1994,
    actNumber: 'Act No. XVIII of 1994',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 28,
    volumeCitation: 'The Bangladesh Code, Volume XXVIII (1993–1994), Act XVIII of 1994',
    category: 'Commercial & Corporate Law',
    categorySlug: 'commercial-contract',
    subcategories: ['Incorporation & RJSC', 'One Person Company (OPC)', 'Directors Duties & AGM', 'Minority Protection (Sec 233)', 'Winding Up & Liquidation'],
    ministry: 'Ministry of Commerce / RJSC',
    keywords: ['companies act', 'rjsc', 'corporate governance', 'one person company', 'opc', 'shareholder', 'section 233', 'section 81', 'board of directors', 'কোম্পানি আইন', 'শেয়ারহোল্ডার'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '11th September 1994',
    commencementDate: '1st January 1995',
    lastAmendedYear: 2020,
    lastAmendmentAct: 'Act No. XIX of 2020 (One Person Company Amendment)',
    overview: 'The primary corporate statute regulating the incorporation, operation, governance, share issuance, management, minority shareholder protection, and liquidation of private, public, and One Person Companies (OPC) registered with the Registrar of Joint Stock Companies and Firms (RJSC) in Bangladesh.',
    overviewBn: 'বাংলাদেশে কোম্পানি গঠন, আরজেএসসি নিবন্ধন, পরিচালনা পর্ষদ, বার্ষিক সাধারণ সভা, এক ব্যক্তি কোম্পানি (ওপিসি) ও অবসায়ন সংক্রান্ত মূল কোম্পানি আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-766.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/766',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 11 September 1994',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 404,
    relatedLawIds: ['bd-contract-act-1872', 'bd-bank-company-1991'],
    sections: [
      {
        number: 'Section 5',
        title: 'Mode of Forming Incorporated Company (Including One Person Company)',
        titleBn: 'কোম্পানি গঠনের পদ্ধতি (এক ব্যক্তি কোম্পানি সহ)',
        content: 'Any seven or more persons in the case of a public company, or two or more persons in the case of a private company, or one natural person in the case of a One Person Company (OPC), may form an incorporated company with limited liability.',
        contentBn: 'পাবলিক কোম্পানির ক্ষেত্রে কমপক্ষে ৭ জন, প্রাইভেট কোম্পানিতে ২ জন এবং এক ব্যক্তি কোম্পানিতে ১ জন ব্যক্তি কোম্পানি গঠন করতে পারেন।',
        simpleExplanation: 'Defines rules for establishing private, public, and One Person Companies (OPCs).',
      },
      {
        number: 'Section 81',
        title: 'Annual General Meeting (AGM)',
        titleBn: 'বার্ষিক সাধারণ সভা (এজিএম)',
        content: 'Every company shall in each year hold in addition to any other meetings a general meeting as its annual general meeting and shall specify the meeting as such in the notices calling it; and not more than fifteen months shall elapse between the date of one annual general meeting and that of the next.',
        contentBn: 'প্রতিটি কোম্পানিকে প্রতি বছর বাধ্যতামূলকভাবে এজিএম করতে হবে এবং এক এজিএম হতে পরবর্তী এজিএমের ব্যবধান ১৫ মাসের বেশি হতে পারবে না।',
        simpleExplanation: 'Requires every company to convene an Annual General Meeting of shareholders at least once every 15 months.',
      },
      {
        number: 'Section 233',
        title: 'Alternative Remedy to Winding Up in Cases of Oppression or Prejudice to Minorities',
        titleBn: 'সংখ্যালঘু শেয়ারহোল্ডারদের ওপর নিপীড়ন বা বৈষম্যের বিরুদ্ধে আদালতে প্রতিকার',
        content: 'Any member or members holding not less than one-tenth of the issued share capital of a company may apply to the High Court Division on the ground that the affairs of the company are being conducted in a manner prejudicial to one or more members or in a manner oppressive to the minority.',
        contentBn: 'কোম্পানিতে সংখ্যালঘু শেয়ারহোল্ডারদের অধিকার ক্ষুণ্ন করা হলে ১০% শেয়ারধারীরা হাইকোর্ট বিভাগে প্রতিকারের জন্য আবেদন করতে পারেন।',
        simpleExplanation: 'Protects minority shareholders holding 10%+ shares against unfair oppression or mismanagement by controlling directors.',
      },
    ],
  },
  {
    id: 'bd-sale-of-goods-1930',
    title: 'The Sale of Goods Act, 1930',
    titleBn: 'পণ্য বিক্রয় আইন, ১৯৩০',
    shortTitle: 'Sale of Goods Act (পণ্য বিক্রয় আইন)',
    alternateTitles: ['Act No. III of 1930', '১৯৩০ সালের ৩ নং আইন'],
    enactmentYear: 1930,
    actNumber: 'Act No. III of 1930',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 7,
    volumeCitation: 'The Bangladesh Code, Volume VII (1930–1939), Act III of 1930',
    category: 'Commercial & Corporate Law',
    categorySlug: 'commercial-contract',
    subcategories: ['Conditions and Warranties', 'Caveat Emptor Doctrine', 'Transfer of Title', 'Unpaid Seller Remedies (Sec 45)'],
    ministry: 'Ministry of Commerce / Ministry of Law',
    keywords: ['sale of goods', 'goods', 'caveat emptor', 'unpaid seller', 'warranty', 'condition', 'পণ্য বিক্রয়', 'ওয়ারেন্টি'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '15th March 1930',
    commencementDate: '1st July 1930',
    lastAmendedYear: 2012,
    overview: 'Regulates commercial contracts for the purchase and sale of movable goods, express and implied warranties, passage of property title, risk of loss, Caveat Emptor doctrine, and unpaid seller’s statutory lien.',
    overviewBn: 'অস্থাবর পণ্য বিক্রয়, শর্ত ও ওয়ারেন্টি, স্বত্ব হস্তান্তর এবং পণ্যের মূল্য পরিশোধ না হলে বিক্রেতার অধিকার সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-151.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/151',
    officialGazetteCitation: 'Legislative Enactment Act III of 1930 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 66,
    relatedLawIds: ['bd-contract-act-1872'],
    sections: [
      {
        number: 'Section 16',
        title: 'Implied Conditions as to Quality or Fitness (Caveat Emptor)',
        titleBn: 'পণ্যের গুণাগুণ ও কার্যোপযোগিতা সম্পর্কিত শর্ত (ক্রেতা সাবধান নীতি)',
        content: 'Subject to the provisions of this Act, there is no implied warranty or condition as to the quality or fitness for any particular purpose of goods supplied under a contract of sale, except where buyer makes known the particular purpose relying on seller’s skill or judgment.',
        contentBn: 'ক্রেতা সাবধান (Caveat Emptor) মূলনীতি: ক্রেতাকে পণ্য যাচাই করে কিনতে হবে; তবে সুনির্দিষ্ট উদ্দেশ্যের কথা জানালে উপযুক্ত পণ্য সরবরাহের বাধ্যবাধকতা থাকবে।',
        simpleExplanation: 'Codifies Caveat Emptor (Buyer Beware) with exceptions for merchantable quality and sample fitness.',
      },
    ],
  },
  {
    id: 'bd-partnership-act-1932',
    title: 'The Partnership Act, 1932',
    titleBn: 'অংশীদারি আইন, ১৯৩২',
    shortTitle: 'Partnership Act (অংশীদারি আইন)',
    alternateTitles: ['Act No. IX of 1932', '১৯৩২ সালের ৯ নং আইন'],
    enactmentYear: 1932,
    actNumber: 'Act No. IX of 1932',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 7,
    volumeCitation: 'The Bangladesh Code, Volume VII (1930–1939), Act IX of 1932',
    category: 'Commercial & Corporate Law',
    categorySlug: 'commercial-contract',
    subcategories: ['Partnership Deeds', 'Mutual Rights & Duties', 'Dissolution of Firms', 'Registration of Firms (Sec 69)'],
    ministry: 'Ministry of Commerce / RJSC',
    keywords: ['partnership act', 'partnership firm', 'partner liability', 'dissolution', 'section 69', 'অংশীদারি কারবার', 'অংশীদার'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '8th April 1932',
    commencementDate: '1st October 1932',
    lastAmendedYear: 2012,
    overview: 'Defines the legal relationship between business partners who agree to share profits of a business carried on by all or any of them acting for all. Governs firm registration with RJSC and consequences of non-registration.',
    overviewBn: 'ব্যবসায়িক অংশীদারি ফার্ম গঠন, অংশীদারদের পারস্পরিক দায়িত্ব-কর্তব্য, ফার্ম নিবন্ধন ও অংশীদারি বিলোপ সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-157.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/157',
    officialGazetteCitation: 'Legislative Enactment Act IX of 1932 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 74,
    relatedLawIds: ['bd-contract-act-1872', 'bd-companies-act-1994'],
    sections: [
      {
        number: 'Section 69',
        title: 'Effect of Non-Registration of Partnership Firm',
        titleBn: 'অংশীদারি ফার্ম নিবন্ধন না করার আইনি ফলাফল',
        content: 'No suit to enforce a right arising from a contract or conferred by this Act shall be instituted in any Court by or on behalf of any person suing as a partner in a firm against the firm or any person alleged to be or to have been a partner in the firm unless the firm is registered.',
        contentBn: 'অনিবন্ধিত অংশীদারি ফার্ম অন্য কোনো ব্যক্তি বা অন্য অংশীদারের বিরুদ্ধে চুক্তিভিত্তিক অধিকার দাবি করে আদালতে মোকদ্দমা দায়ের করতে পারে না।',
        simpleExplanation: 'Unregistered partnership firms cannot sue third parties or enforce contractual rights in court.',
      },
    ],
  },
  {
    id: 'bd-ni-act-1881',
    title: 'The Negotiable Instruments Act, 1881',
    titleBn: 'হস্তান্তরযোগ্য দলিল আইন, ১৮৮১',
    shortTitle: 'NI Act (এনআই অ্যাক্ট)',
    alternateTitles: ['Act No. XXVI of 1881', '১৮৮১ সালের ২৬ নং আইন', 'Cheque Dishonour Act'],
    enactmentYear: 1881,
    actNumber: 'Act No. XXVI of 1881',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 2,
    volumeCitation: 'The Bangladesh Code, Volume II (1872–1882), Act XXVI of 1881',
    category: 'Commercial & Corporate Law',
    categorySlug: 'commercial-contract',
    subcategories: ['Cheque Dishonour (Sec 138)', 'Promissory Notes', 'Bills of Exchange', 'Endorsement & Holder in Due Course', 'Corporate Liability (Sec 141)'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs / Ministry of Finance',
    keywords: ['ni act', 'section 138', 'cheque bounce', 'dishonour of cheque', 'promissory note', 'চেক ডিজঅনার', 'চেক বাউন্স', 'হস্তান্তরযোগ্য দলিল'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '9th December 1881',
    commencementDate: '1st March 1882',
    lastAmendedYear: 2006,
    lastAmendmentAct: 'Act No. III of 2006',
    overview: 'Regulates negotiable financial instruments (promissory notes, bills of exchange, and bank cheques). Contains the pivotal Section 138 criminalizing cheque dishonour due to insufficient bank funds.',
    overviewBn: 'ব্যাংক চেক, প্রমিশরি নোট ও বিল অফ এক্সচেঞ্জ সংক্রান্ত আইন। পর্যাপ্ত তহবিলের অভাবে ব্যাংক চেক ডিজঅনারের জন্য ১৩৮ ধারায় কারাদণ্ড ও জরিমানার বিধান।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-43.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/43',
    officialGazetteCitation: 'Legislative Enactment Act XXVI of 1881 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 141,
    relatedLawIds: ['bd-bank-company-1991', 'bd-money-loan-court-2003', 'bd-contract-act-1872'],
    sections: [
      {
        number: 'Section 138',
        title: 'Dishonour of Cheque for Insufficiency of Funds in the Account',
        titleBn: 'অ্যাকাউন্টে পর্যাপ্ত তহবিল না থাকার কারণে চেক ডিজঅনার ও তার দণ্ড',
        content: 'Where any cheque drawn by a person on an account maintained by him with a banker for payment of any amount of money to another person from out of that account is returned by the bank unpaid, either because of the amount of money standing to the credit of that account is insufficient, such person shall be punished with imprisonment for a term which may extend to one year, or with fine which may extend to thrice the amount of the cheque, or with both.',
        contentBn: 'ব্যাংকে পর্যাপ্ত টাকা না থাকার কারণে চেক প্রত্যাখ্যাত হলে চেক প্রদানকারীকে ১ বছর পর্যন্ত কারাদণ্ড বা চেকের মূল্যের ৩ গুণ পর্যন্ত অর্থদণ্ডে দণ্ডিত করা যাবে। (শর্ত: ৩০ দিনের মধ্যে লিগ্যাল নোটিশ প্রদান আবশ্যক)।',
        simpleExplanation: 'Provides up to 1 year imprisonment and up to 3x fine for bouncing a cheque, subject to serving formal 30-day legal notice.',
        penalty: 'Imprisonment up to 1 year or fine up to 3 times the cheque amount or both',
        isBailable: true,
        isCognizable: false,
      },
      {
        number: 'Section 141',
        title: 'Offences by Companies',
        titleBn: 'কোম্পানি কর্তৃক অপরাধ সংঘটন',
        content: 'If the person committing an offence under section 138 is a company, every person who, at the time the offence was committed, was in charge of, and was responsible to the company for the conduct of the business of the company, as well as the company, shall be deemed to be guilty of the offence.',
        contentBn: 'কোম্পানি কর্তৃক চেক ডিজঅনার হলে কোম্পানির পাশাপাশি সংশ্লিষ্ট ব্যবস্থাপনা পরিচালক ও দায়িত্বশীল পরিচালকদের বিরুদ্ধেও ব্যক্তিগত দায় বর্তাবে।',
        simpleExplanation: 'Extends personal criminal liability for bounced company cheques to managing directors and authorized signatories.',
      },
    ],
  },

  // 8. BANKING AND FINANCE LAW
  {
    id: 'bd-bank-company-1991',
    title: 'The Bank Company Act, 1991',
    titleBn: 'ব্যাংক-কোম্পানী আইন, ১৯৯১',
    shortTitle: 'Bank Company Act (ব্যাংক কোম্পানি আইন)',
    alternateTitles: ['Act No. XIV of 1991', '১৯৯১ সালের ১৪ নং আইন'],
    enactmentYear: 1991,
    actNumber: 'Act No. XIV of 1991',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 26,
    volumeCitation: 'The Bangladesh Code, Volume XXVI (1990–1991), Act XIV of 1991',
    category: 'Banking & Financial Services',
    categorySlug: 'banking-finance',
    subcategories: ['Bangladesh Bank Oversight', 'Banking Licenses', 'Director Loan Limits', 'Willful Default Classification', 'Board Removal Powers'],
    ministry: 'Financial Institutions Division, Ministry of Finance / Bangladesh Bank',
    keywords: ['bank company', 'bangladesh bank', 'willful defaulter', 'banking license', 'director loan', 'ব্যাংক কোম্পানি', 'বাংলাদেশ ব্যাংক', 'ইচ্ছাকৃত খেলাপি'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '4th May 1991',
    commencementDate: '4th May 1991',
    lastAmendedYear: 2023,
    lastAmendmentAct: 'Act No. XVIII of 2023 (Willful Default Amendment)',
    overview: 'Primary banking regulatory statute empowering Bangladesh Bank to license commercial banks, enforce capital adequacy (BASEL III), restrict insider loans to directors, classify willful loan defaulters, and supersede commercial bank boards.',
    overviewBn: 'বাংলাদেশে তফসিলি বাণিজ্যিক ব্যাংকসমূহের লাইসেন্সিং, পরিচালনা পর্ষদ নিয়ন্ত্রণ, ইচ্ছাকৃত ঋণখেলাপিদের তালিকাভুক্তি ও বাংলাদেশ ব্যাংকের তদারকি আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-740.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/740',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 4 May 1991',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 124,
    relatedLawIds: ['bd-financial-institutions-1993', 'bd-money-loan-court-2003', 'bd-money-laundering-2012'],
    sections: [
      {
        number: 'Section 27',
        title: 'Restrictions on Loans and Advances to Bank Directors and Related Parties',
        titleBn: 'ব্যাংক পরিচালকদের ঋণ ও অগ্রিম গ্রহণের উপর বিধিনিষেধ',
        content: 'No banking company shall grant any loan or advance to any of its directors or to any firm or company in which any of its directors is interested as partner or director beyond the statutory limits prescribed by Bangladesh Bank.',
        contentBn: 'ব্যাংকের কোনো পরিচালককে জামানতবিহীন ঋণ প্রদান সম্পূর্ণ নিষিদ্ধ এবং সংশ্লিষ্ট প্রতিষ্ঠানে ঋণ প্রদানে কঠোর সীমা আরোপিত।',
        simpleExplanation: 'Strictly limits inside lending and prohibits unsecured loans to bank board directors and family businesses.',
      },
      {
        number: 'Section 45',
        title: 'Power of Bangladesh Bank to Give Directions and Supersede Bank Management',
        titleBn: 'ব্যাংক ব্যবস্থাপনায় বাংলাদেশ ব্যাংকের দিকনির্দেশনা প্রদান ও পর্ষদ ভেঙে দেওয়ার ক্ষমতা',
        content: 'Where Bangladesh Bank is satisfied that in the public interest or to prevent the affairs of any banking company being conducted in a manner detrimental to depositors, it may issue binding directions or remove directors/MDs and appoint an Administrator.',
        contentBn: 'আমানতকারীদের স্বার্থ সুরক্ষা ও আর্থিক স্থিতিশীলতা রক্ষায় কেন্দ্রীয় ব্যাংক যেকোনো বাণিজ্যিক ব্যাংকে প্রশাসক নিয়োগ বা পরিচালক অপসারণ করতে পারে।',
        simpleExplanation: 'Central bank powers to intervene in failing banks, remove incompetent executives, and appoint official administrators.',
      },
    ],
  },
  {
    id: 'bd-financial-institutions-1993',
    title: 'The Financial Institutions Act, 1993',
    titleBn: 'আর্থিক প্রতিষ্ঠান আইন, ১৯৯৩',
    shortTitle: 'Financial Institutions Act (আর্থিক প্রতিষ্ঠান আইন)',
    alternateTitles: ['Act No. XXVII of 1993', '১৯৯৩ সালের ২৭ নং আইন', 'NBFI Regulation Act'],
    enactmentYear: 1993,
    actNumber: 'Act No. XXVII of 1993',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 28,
    volumeCitation: 'The Bangladesh Code, Volume XXVIII (1993–1994), Act XXVII of 1993',
    category: 'Banking & Financial Services',
    categorySlug: 'banking-finance',
    subcategories: ['Non-Bank Financial Institutions (NBFIs)', 'Leasing & Housing Finance', 'Central Bank Inspections', 'Reserve Funds'],
    ministry: 'Financial Institutions Division / Bangladesh Bank',
    keywords: ['nbfi', 'financial institutions', 'leasing', 'reserve fund', 'non bank', 'আর্থিক প্রতিষ্ঠান', 'লিজিং'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '26th September 1993',
    commencementDate: '26th September 1993',
    lastAmendedYear: 2023,
    overview: 'Regulatory enactment for Non-Bank Financial Institutions (NBFIs) in Bangladesh, governing leasing, hire-purchase financing, merchant banking, merchant credit, and central bank prudential guidelines.',
    overviewBn: 'বাংলাদেশে ব্যাংক-বহির্ভূত আর্থিক প্রতিষ্ঠান (এনবিএফআই), লিজিং ও গৃহায়ন অর্থায়ন নিয়ন্ত্রণ সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-757.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/757',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 26 September 1993',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 52,
    relatedLawIds: ['bd-bank-company-1991', 'bd-money-loan-court-2003'],
    sections: [
      {
        number: 'Section 4',
        title: 'Licensing of Financial Institutions',
        titleBn: 'আর্থিক প্রতিষ্ঠানের লাইসেন্স গ্রহণ',
        content: 'No person shall carry on financial business in Bangladesh without obtaining a license from Bangladesh Bank under this Act.',
        contentBn: 'বাংলাদেশ ব্যাংকের লাইসেন্স ব্যতিরেকে দেশে কোনো আর্থিক প্রতিষ্ঠান বা লিজিং ব্যবসা পরিচালনা করা যাবে না।',
        simpleExplanation: 'Mandates central bank license before offering non-bank commercial credit or leasing.',
      },
    ],
  },
  {
    id: 'bd-money-loan-court-2003',
    title: 'The Money Loan Court Act, 2003',
    titleBn: 'অর্থ ঋণ আদালত আইন, ২০০৩',
    shortTitle: 'Money Loan Court Act (অর্থ ঋণ আদালত আইন)',
    alternateTitles: ['Artha Rin Adalat Ain, 2003', 'Act No. VIII of 2003', '২০০৩ সালের ৮ নং আইন'],
    enactmentYear: 2003,
    actNumber: 'Act No. VIII of 2003',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 34,
    volumeCitation: 'The Bangladesh Code, Volume XXXIV (2003–2004), Act VIII of 2003',
    category: 'Banking & Financial Services',
    categorySlug: 'banking-finance',
    subcategories: ['Exclusive Bank Debt Recovery', 'Pre-suit Auction (Sec 12)', 'Civil Imprisonment (Sec 34)', 'Deposit for Appeal (Sec 41)'],
    ministry: 'Financial Institutions Division / Ministry of Law',
    keywords: ['artha rin adalat', 'money loan court', 'default loan', 'bank recovery', 'mortgage auction', 'section 12', 'section 34', 'অর্থ ঋণ আদালত', 'খেলাপি ঋণ'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '10th March 2003',
    commencementDate: '1st May 2003',
    lastAmendedYear: 2010,
    lastAmendmentAct: 'Act No. XVI of 2010',
    overview: 'Specialized judicial enactment establishing dedicated Money Loan Courts (Artha Rin Adalat) with exclusive jurisdiction for the summary recovery of defaulted loans, mortgages, and commercial credits by banks and financial institutions.',
    overviewBn: 'ব্যাংক ও আর্থিক প্রতিষ্ঠানের খেলাপি ঋণ ও বন্ধকি সম্পত্তি নিলাম বিক্রয়ের মাধ্যমে দ্রুত অর্থ আদায়ের জন্য বিশেষ অর্থ ঋণ আদালত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-894.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/894',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 10 March 2003',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 60,
    relatedLawIds: ['bd-bank-company-1991', 'bd-ni-act-1881', 'bd-cpc-1908'],
    sections: [
      {
        number: 'Section 12',
        title: 'Sale of Mortgaged Property Prior to Filing Suit',
        titleBn: 'মামলা দায়েরের পূর্বে বন্ধকি সম্পত্তি নিলাম বিক্রয়',
        content: 'No financial institution shall institute a suit for recovery of loan secured by mortgage of immovable property or hypothecation of movable property without first publishing auction notice and attempting sale under this section.',
        contentBn: 'অর্থ ঋণ আদালতে মামলা করার পূর্বে ব্যাংককে আবশ্যিকভাবে পত্রিকায় বিজ্ঞপ্তি দিয়ে বন্ধকি সম্পত্তি নিলামে বিক্রয়ের চেষ্টা করতে হবে।',
        simpleExplanation: 'Requires banks to auction off collateral assets before dragging debtors to the Money Loan Court.',
      },
      {
        number: 'Section 34',
        title: 'Detention in Civil Prison for Non-Satisfaction of Decree',
        titleBn: 'ডিক্রিকৃত অর্থ পরিশোধ না করায় দেওয়ানি কারাবাস',
        content: 'Where the judgment debtor fails to pay the decreed amount, the Court may order the detention of the judgment debtor in civil prison for a period not exceeding six months.',
        contentBn: 'ডিক্রি জারির পরও ঋণ পরিশোধ না করলে আদালত খেলাপি ঋণগ্রহীতাকে অনধিক ৬ মাসের দেওয়ানি কারাদণ্ডে প্রেরণ করতে পারেন।',
        simpleExplanation: 'Provides up to 6 months of civil detention for willful failure to satisfy an Artha Rin judgment debt.',
      },
      {
        number: 'Section 41',
        title: 'Appeals and Mandatory 50% Deposit Condition',
        titleBn: 'আপিল ও ৫০% অর্থ জমা দেওয়ার বাধ্যবাধকতা',
        content: 'No appeal preferred by a judgment-debtor shall be admitted unless the judgment-debtor deposits fifty percent of the decreed amount with the financing institution or with the Court.',
        contentBn: 'অর্থ ঋণ আদালতের ডিক্রির বিরুদ্ধে আপিল করতে হলে ঋণগ্রহীতাকে ডিক্রিকৃত অর্থের ৫০% নগদ জমা দিতে হবে।',
        simpleExplanation: 'Requires debtors to deposit 50% of the decreed debt amount in cash as a condition precedent to filing an appeal.',
      },
    ],
  },
  {
    id: 'bd-money-laundering-2012',
    title: 'The Money Laundering Prevention Act, 2012',
    titleBn: 'মানি লন্ডারিং প্রতিরোধ আইন, ২০১২',
    shortTitle: 'Money Laundering Act (মানি লন্ডারিং প্রতিরোধ আইন)',
    alternateTitles: ['Act No. V of 2012', '২০১২ সালের ৫ নং আইন', 'Anti-Money Laundering Act'],
    enactmentYear: 2012,
    actNumber: 'Act No. V of 2012',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 38,
    volumeCitation: 'The Bangladesh Code, Volume XXXVIII (2011–2012), Act V of 2012',
    category: 'Banking & Financial Services',
    categorySlug: 'banking-finance',
    subcategories: ['BFIU Intelligence', 'Predicate Offenses', 'Asset Freezing & Confiscation', 'Hawala & Hundi Prohibition'],
    ministry: 'Financial Institutions Division / BFIU / Bangladesh Bank',
    keywords: ['money laundering', 'bfiu', 'hundi', 'hawala', 'asset freeze', 'predicate offense', 'section 4', 'মানি লন্ডারিং', 'হুন্ডি', 'সম্পদ জব্দ'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '20th February 2012',
    commencementDate: '16th January 2012',
    lastAmendedYear: 2015,
    lastAmendmentAct: 'Act No. XIV of 2015',
    overview: 'Statutory framework to detect and penalize money laundering, illicit cross-border capital flight, Hawala/Hundi remittance channels, and predicate financial crimes. Establishes the Bangladesh Financial Intelligence Unit (BFIU).',
    overviewBn: 'অবৈধ অর্থ পাচার, হুন্ডি, বিদেশে অর্থ পাচার এবং মানি লন্ডারিং প্রতিরোধে বিএফআইইউ গঠন ও কঠোর সাজার আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1088.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1088',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 20 February 2012',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 31,
    relatedLawIds: ['bd-acc-act-2004', 'bd-bank-company-1991'],
    sections: [
      {
        number: 'Section 4',
        title: 'Punishment for Offence of Money Laundering',
        titleBn: 'মানি লন্ডারিং অপরাধের শাস্তি',
        content: 'Any person who commits the offence of money laundering shall be punished with imprisonment for a term which shall not be less than four years but may extend to twelve years, and shall also be liable to fine amounting to twice the value of the property involved in the offence or ten lakh Taka, whichever is higher, and the property shall be confiscated.',
        contentBn: 'মানি লন্ডারিংয়ে দোষী সাব্যস্ত হলে ৪ হতে ১২ বছর কারাদণ্ড এবং সংশ্লিষ্ট সম্পত্তির দ্বিগুণ অর্থদণ্ড বা ১০ লক্ষ টাকা অর্থদণ্ডে দণ্ডিত হইবে এবং পাচারকৃত সম্পত্তি বাজেয়াপ্ত হবে।',
        simpleExplanation: 'Mandates 4 to 12 years imprisonment, double asset penalty, and complete property confiscation for money laundering.',
        penalty: 'Imprisonment from 4 to 12 years and fine of twice the property value, plus asset confiscation',
        isBailable: false,
        isCognizable: true,
      },
    ],
  },
  {
    id: 'bd-bankruptcy-act-1997',
    title: 'The Bankruptcy Act, 1997',
    titleBn: 'দেউলিয়া বিষয়ক আইন, ১৯৯৭',
    shortTitle: 'Bankruptcy Act (দেউলিয়া আইন)',
    alternateTitles: ['Act No. X of 1997', '১৯৯৭ সালের ১০ নং আইন'],
    enactmentYear: 1997,
    actNumber: 'Act No. X of 1997',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 30,
    volumeCitation: 'The Bangladesh Code, Volume XXX (1997–1998), Act X of 1997',
    category: 'Banking & Financial Services',
    categorySlug: 'banking-finance',
    subcategories: ['Acts of Bankruptcy', 'Adjudication Orders', 'Official Receiver', 'Disqualification of Bankrupts'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs / Ministry of Finance',
    keywords: ['bankruptcy', 'deulia', 'insolvency', 'official receiver', 'debtor', 'দেউলিয়া আইন', 'ঋণ দেউলিয়া'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '24th March 1997',
    commencementDate: '24th March 1997',
    lastAmendedYear: 2012,
    overview: 'Regulates insolvency and bankruptcy proceedings for commercial debtors unable to discharge their financial obligations. Governs vesting of assets in Official Receivers and disqualification from public holding and corporate directorships.',
    overviewBn: 'ব্যক্তি ও ব্যবসায়িক প্রতিষ্ঠানের দেউলিয়া ঘোষণা, দেনা পরিশোধের অসমর্থতা ও দেউলিয়ার সম্পদ হস্তান্তর সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-815.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/815',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 24 March 1997',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 105,
    relatedLawIds: ['bd-companies-act-1994', 'bd-money-loan-court-2003'],
    sections: [
      {
        number: 'Section 12',
        title: 'Courts Having Jurisdiction in Bankruptcy',
        titleBn: 'দেউলিয়া বিষয়ক আদালত ও তার এখতিয়ার',
        content: 'Bankruptcy Courts constituted under this Act shall have exclusive jurisdiction to entertain insolvency petitions and make orders of adjudication.',
        contentBn: 'দেউলিয়া আদালত দেউলিয়াত্বের আবেদন গ্রহণ ও দেউলিয়া ঘোষণার আদেশ প্রদানের একক এখতিয়ার সংরক্ষণ করে।',
        simpleExplanation: 'Establishes dedicated Bankruptcy Courts presided over by District Judges.',
      },
    ],
  },

  // 9. TAX AND REVENUE LAW
  {
    id: 'bd-income-tax-act-2023',
    title: 'The Income Tax Act, 2023',
    titleBn: 'আয়কর আইন, ২০২৩',
    shortTitle: 'Income Tax Act (আয়কর আইন)',
    alternateTitles: ['Act No. XII of 2023', '২০২৩ সালের ১২ নং আইন', 'Repealed & Replaced Income Tax Ordinance 1984'],
    enactmentYear: 2023,
    actNumber: 'Act No. XII of 2023',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 45,
    volumeCitation: 'The Bangladesh Code, Volume XLV (2022–2023), Act XII of 2023',
    category: 'Tax & Revenue Law',
    categorySlug: 'tax-revenue',
    subcategories: ['Heads of Income', 'TIN & Return of Income (Sec 166)', 'Withholding Tax (TDS)', 'Corporate Tax', 'Taxes Appellate Tribunal'],
    ministry: 'Internal Resources Division (IRD) / National Board of Revenue (NBR)',
    keywords: ['income tax', 'nbr', 'tin', 'tax return', 'tds', 'section 166', 'corporate tax', 'আয়কর আইন', 'রিটার্ন দাখিল', 'কর অঞ্চল'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '22nd June 2023',
    commencementDate: '1st July 2023',
    lastAmendedYear: 2024,
    overview: 'Modern tax legislation replacing the 1984 Ordinance. Regulates direct income taxation across personal and corporate income heads, mandatory return filing proofs (PSR), universal self-assessments, advance tax payments, and transfer pricing in Bangladesh.',
    overviewBn: 'বাংলাদেশে প্রত্যক্ষ আয়কর নির্ধারণ, রিটার্ন দাখিলের বাধ্যবাধকতা, উৎস কর ও কর্পোরেট ট্যাক্স সংক্রান্ত মূল আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1420.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1420',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 22 June 2023',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 345,
    relatedLawIds: ['bd-vat-sd-act-2012', 'bd-customs-act-2023'],
    sections: [
      {
        number: 'Section 22',
        title: 'Heads of Income',
        titleBn: 'আয়ের খাতসমূহ',
        content: 'Income shall be classified under the following heads: (a) Employment income, (b) Rent from house property, (c) Agricultural income, (d) Income from business, (e) Capital gains, (f) Financial assets income, and (g) Income from other sources.',
        contentBn: 'করযোগ্য আয়ের ৭টি প্রধান খাত: চাকরি হতে আয়, গৃহ-সম্পত্তির ভাড়া, কৃষি আয়, ব্যবসা হতে আয়, মূলধনি লাভ, আর্থিক পরিসম্পদ হতে আয় এবং অন্যান্য উৎস।',
        simpleExplanation: 'Defines statutory taxable categories for personal and corporate income.',
      },
      {
        number: 'Section 166',
        title: 'Mandatory Submission of Return of Income',
        titleBn: 'আয়কর রিটার্ন দাখিলের বাধ্যবাধকতা',
        content: 'Every person whose total income exceeds the minimum threshold or who holds a TIN or operates in specified commercial sectors must submit an annual return of income on or before Tax Day (30th November).',
        contentBn: 'করমুক্ত আয়ের সীমার অতিরিক্ত আয়ধারী সকল ব্যক্তি ও নির্দিষ্ট পেশাজীবীদের জন্য কর দিবসের মধ্যে আয়কর রিটার্ন দাখিল বাধ্যতামূলক।',
        simpleExplanation: 'Mandates annual income tax return submission before official Tax Day deadlines.',
      },
    ],
  },
  {
    id: 'bd-vat-sd-act-2012',
    title: 'The Value Added Tax and Supplementary Duty Act, 2012',
    titleBn: 'মূল্য সংযোজন কর ও সম্পূরক শুল্ক আইন, ২০১২',
    shortTitle: 'VAT Act (মূসক আইন)',
    alternateTitles: ['Act No. XLVII of 2012', '২০১২ সালের ৪৭ নং আইন', 'VAT & SD Act 2012'],
    enactmentYear: 2012,
    actNumber: 'Act No. XLVII of 2012',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 38,
    volumeCitation: 'The Bangladesh Code, Volume XXXVIII (2011–2012), Act XLVII of 2012',
    category: 'Tax & Revenue Law',
    categorySlug: 'tax-revenue',
    subcategories: ['VAT Registration & BIN (Sec 4)', 'Standard 15% VAT & Slabs', 'Supplementary Duty (SD)', 'Mushak-6.3 Invoicing (Sec 86)'],
    ministry: 'National Board of Revenue (NBR)',
    keywords: ['vat act', 'mushak', 'bin', 'supplementary duty', 'input tax credit', 'section 4', 'section 86', 'মূসক', 'ভ্যাট আইন', 'চালান'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '10th December 2012',
    commencementDate: '1st July 2019',
    lastAmendedYear: 2023,
    overview: 'The primary indirect tax legislation of Bangladesh. Imposes Value Added Tax (standard 15% and reduced slabs) on goods and services, supplementary duties, input tax credits, Business Identification Number (BIN) mandates, and electronic fiscal devices (EFD).',
    overviewBn: 'পণ্য ও সেবায় মূল্য সংযোজন কর (ভ্যাট), সম্পূরক শুল্ক, মূসক চালান ও বিন (BIN) নিবন্ধন সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1108.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1108',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 10 December 2012',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 139,
    relatedLawIds: ['bd-income-tax-act-2023', 'bd-customs-act-2023'],
    sections: [
      {
        number: 'Section 4',
        title: 'Mandatory VAT Registration and Business Identification Number (BIN)',
        titleBn: 'বাধ্যতামূলক মূসক নিবন্ধন ও ব্যবসায় শনাক্তকরণ সংখ্যা (বিন)',
        content: 'Every person carrying on taxable economic activity exceeding statutory turnover limits must obtain a Business Identification Number (BIN) registration.',
        contentBn: 'নির্দিষ্ট টার্নওভারের অতিরিক্ত ব্যবসা পরিচালনা করলে মূসক নিবন্ধন বা ৯ সংখ্যার বিন (BIN) গ্রহণ বাধ্যতামূলক।',
        simpleExplanation: 'Requires all commercial traders and service providers to maintain an active VAT registration BIN.',
      },
      {
        number: 'Section 86',
        title: 'Tax Invoice Requirements (Mushak-6.3)',
        titleBn: 'কর চালানপত্র (মূসক-৬.৩) জারির বাধ্যবাধকতা',
        content: 'Every registered supplier of taxable goods or services shall issue a tax invoice in Form Mushak-6.3 at the time of supply.',
        contentBn: 'পণ্য সরবরাহের সাথে ক্রেতাকে আবশ্যিকভাবে সরকারি ফরমের মূসক-৬.৩ চালানপত্র প্রদান করতে হবে।',
        simpleExplanation: 'Mandates issuance of statutory Mushak-6.3 tax invoices on all commercial sales.',
      },
    ],
  },
  {
    id: 'bd-customs-act-2023',
    title: 'The Customs Act, 2023',
    titleBn: 'কাস্টমস আইন, ২০২৩',
    shortTitle: 'Customs Act (কাস্টমস আইন)',
    alternateTitles: ['Act No. LVII of 2023', '২০২৩ সালের ৫৭ নং আইন', 'Repealed Customs Act 1969'],
    enactmentYear: 2023,
    actNumber: 'Act No. LVII of 2023',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 45,
    volumeCitation: 'The Bangladesh Code, Volume XLV (2022–2023), Act LVII of 2023',
    category: 'Tax & Revenue Law',
    categorySlug: 'tax-revenue',
    subcategories: ['Import & Export Tariffs', 'Bill of Entry & ASYCUDA', 'Anti-Smuggling Seizures', 'Customs Appellate Tribunal'],
    ministry: 'National Board of Revenue (NBR) / Ministry of Finance',
    keywords: ['customs act', 'import tariff', 'export duty', 'bill of entry', 'smuggling', 'customs station', 'কাস্টমস আইন', 'শুল্ক', 'আমদানি শুল্ক'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '13th November 2023',
    commencementDate: '6th June 2024',
    lastAmendedYear: 2024,
    overview: 'Updated 2023 statute consolidating customs procedures, automated port clearances (National Single Window), import-export tariffs, bonded warehouse monitoring, and anti-smuggling seizures across land, sea, and air ports in Bangladesh.',
    overviewBn: 'আন্তর্জাতিক বাণিজ্য, আমদানি-রপ্তানি শুল্কায়ন, বন্দর খালাস ও চোরাচালান প্রতিরোধে আধুনিকায়িত কাস্টমস আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1447.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1447',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 13 November 2023',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 269,
    relatedLawIds: ['bd-vat-sd-act-2012', 'bd-income-tax-act-2023'],
    sections: [
      {
        number: 'Section 18',
        title: 'Levy of Customs Duties on Imported and Exported Goods',
        titleBn: 'আমদানি ও রপ্তানিকৃত পণ্যের ওপর কাস্টমস শুল্ক আরোপ',
        content: 'Customs duties shall be levied at such rates as may be prescribed under the Customs Tariff on goods imported into, or exported from, Bangladesh.',
        contentBn: 'জাতীয় রাজস্ব বোর্ডের নির্ধারিত ট্যারিফ শিডিউল মোতাবেক আমদানি ও রপ্তানি পণ্যের ওপর শুল্ক ধার্য করা হবে।',
        simpleExplanation: 'Grants statutory authority to levy tariffs and duties on international cargo.',
      },
    ],
  },

  // 10. INTELLECTUAL PROPERTY LAW
  {
    id: 'bd-trademarks-act-2009',
    title: 'The Trademarks Act, 2009',
    titleBn: 'ট্রেডমার্ক আইন, ২০০৯',
    shortTitle: 'Trademarks Act (ট্রেডমার্ক আইন)',
    alternateTitles: ['Act No. XIX of 2009', '২০০৯ সালের ১৯ নং আইন'],
    enactmentYear: 2009,
    actNumber: 'Act No. XIX of 2009',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 36,
    volumeCitation: 'The Bangladesh Code, Volume XXXVI (2007–2009), Act XIX of 2009',
    category: 'Intellectual Property Law',
    categorySlug: 'intellectual-property',
    subcategories: ['Brand Registration (DPDT)', 'Infringement & Passing-Off (Sec 67)', 'Criminal Counterfeiting (Sec 73)', 'Nice Classification'],
    ministry: 'Ministry of Industries / DPDT',
    keywords: ['trademark', 'brand', 'dpdt', 'counterfeiting', 'passing off', 'infringement', 'section 67', 'ট্রেডমার্ক', 'ব্র্যান্ড সুরক্ষা'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '29th March 2009',
    commencementDate: '29th March 2009',
    lastAmendedYear: 2015,
    overview: 'Regulates the registration, exclusive trademark rights, protection of brand logos, and civil and criminal remedies against counterfeiters and passing-off in Bangladesh through the Department of Patents, Designs and Trademarks (DPDT).',
    overviewBn: 'ব্র্যান্ডের নাম, লোগো ও ট্রেডমার্ক নিবন্ধন এবং নকল পণ্য প্রস্তুতকারকদের বিরুদ্ধে দেওয়ানি ও ফৌজদারি প্রতিকার সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1014.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1014',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 29 March 2009',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 131,
    relatedLawIds: ['bd-copyright-act-2023', 'bd-patent-act-2023'],
    sections: [
      {
        number: 'Section 24',
        title: 'Exclusive Rights Conferred by Registration of Trademark',
        titleBn: 'ট্রেডমার্ক নিবন্ধনের ফলে অর্জিত একক স্বত্ব',
        content: 'The registration of a trade mark shall give to the registered proprietor the exclusive right to the use of the trade mark in relation to the goods or services in respect of which the trade mark is registered.',
        contentBn: 'নিবন্ধিত ট্রেডমার্কের মালিক সংশ্লিষ্ট পণ্য বা সেবায় উক্ত মার্ক এককভাবে ব্যবহারের আইনগত অধিকার লাভ করেন।',
        simpleExplanation: 'Provides exclusive monopoly rights over registered brand names and product logos.',
      },
      {
        number: 'Section 67',
        title: 'Infringement of Registered Trademarks and Injunction Remedies',
        titleBn: 'ট্রেডমার্ক লঙ্ঘন ও নিষেধাজ্ঞা প্রতিকার',
        content: 'A registered trade mark is infringed by any person who, not being a registered proprietor, uses in the course of trade a mark which is identical with, or deceptively similar to, the trade mark.',
        contentBn: 'অনুমতি ছাড়া নকল বা বিভ্রান্তিকরভাবে অনুরূপ ব্র্যান্ড লোগো ব্যবহার করলে দেওয়ানি আদালতে নিষেধাজ্ঞা ও ক্ষতিপূরণ দাবি করা যায়।',
        simpleExplanation: 'Enables brand owners to sue for court injunctions, impoundment of counterfeit stock, and damages.',
      },
    ],
  },
  {
    id: 'bd-copyright-act-2023',
    title: 'The Copyright Act, 2023',
    titleBn: 'কপিরাইট আইন, ২০২৩',
    shortTitle: 'Copyright Act (কপিরাইট আইন)',
    alternateTitles: ['Act No. XLVI of 2023', '২০২৩ সালের ৪৬ নং আইন', 'Repealed Copyright Act 2000'],
    enactmentYear: 2023,
    actNumber: 'Act No. XLVI of 2023',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 45,
    volumeCitation: 'The Bangladesh Code, Volume XLV (2022–2023), Act XLVI of 2023',
    category: 'Intellectual Property Law',
    categorySlug: 'intellectual-property',
    subcategories: ['Literary, Musical & Artistic Works', 'Software & Digital Copyright', '60-Year Term of Protection', 'Anti-Piracy Enforcement (Sec 82)'],
    ministry: 'Ministry of Cultural Affairs / Copyright Office Bangladesh',
    keywords: ['copyright', 'piracy', 'software copyright', 'author rights', 'royalties', 'section 14', 'section 71', 'কপিরাইট', 'পাইরেসি', 'সফটওয়্যার স্বত্বাধিকার'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '19th October 2023',
    commencementDate: '19th October 2023',
    lastAmendedYear: 2023,
    overview: 'Updated 2023 copyright statute modernizing protections for authors, software engineers, musicians, and artists. Extends statutory copyright over computer programs, digital databases, online streaming, and provides criminal penalties for piracy.',
    overviewBn: 'সাহিত্য, চলচ্চিত্র, সঙ্গীত, সফটওয়্যার কোড ও ডিজিটাল কনটেন্টের কপিরাইট সুরক্ষা ও পাইরেসি প্রতিরোধে আধুনিকায়িত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1440.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1440',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 19 October 2023',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 110,
    relatedLawIds: ['bd-trademarks-act-2009', 'bd-patent-act-2023', 'bd-cyber-security-act-2023'],
    sections: [
      {
        number: 'Section 14',
        title: 'Meaning of Copyright (Exclusive Rights)',
        titleBn: 'কপিরাইটের সংজ্ঞা ও স্বত্বাধিকার',
        content: 'Copyright means the exclusive right to do or authorize the doing of reproduction, issuance of copies, public performance, translation, and adaptation of literary, musical, dramatic, artistic works, and computer software.',
        contentBn: 'লেখক বা প্রোগ্রামারের লিখিত রচনা, সঙ্গীত, শিল্পকর্ম ও সফটওয়্যার প্রকাশ, অনুলিপি ও বাণিজ্যিকভাবে ব্যবহারের একক অধিকার।',
        simpleExplanation: 'Grants creators exclusive commercial rights over their software, artistic, and literary output.',
      },
      {
        number: 'Section 24',
        title: 'Term of Copyright (Author’s Lifetime + 60 Years)',
        titleBn: 'কপিরাইটের মেয়াদ (জীবদ্দশা + ৬০ বছর)',
        content: 'Copyright shall subsist in any literary, dramatic, musical or artistic work published within the lifetime of the author until sixty years from the beginning of the calendar year next following the year in which the author dies.',
        contentBn: 'কপিরাইটের মেয়াদ রচয়িতার জীবদ্দশা এবং মৃত্যুর পরবর্তী পঞ্জিকাবর্ষ হতে ৬০ বছর পর্যন্ত বলবৎ থাকিবে।',
        simpleExplanation: 'Statutory copyright lasts for the author\'s entire life plus 60 additional years.',
      },
    ],
  },
  {
    id: 'bd-patent-act-2023',
    title: 'The Bangladesh Patent Act, 2023',
    titleBn: 'বাংলাদেশ পেটেন্ট আইন, ২০২৩',
    shortTitle: 'Patent Act (পেটেন্ট আইন)',
    alternateTitles: ['Act No. XXIV of 2023', '২০২৩ সালের ২৪ নং আইন', 'Repealed Patents & Designs Act 1911'],
    enactmentYear: 2023,
    actNumber: 'Act No. XXIV of 2023',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 45,
    volumeCitation: 'The Bangladesh Code, Volume XLV (2022–2023), Act XXIV of 2023',
    category: 'Intellectual Property Law',
    categorySlug: 'intellectual-property',
    subcategories: ['Patentable Inventions', '20-Year Protection Term', 'Compulsory Licensing (Sec 48)', 'TRIPS Pharma Exceptions'],
    ministry: 'Ministry of Industries / DPDT',
    keywords: ['patent', 'invention', 'novelty', 'trips', 'compulsory license', 'dpdt', 'পেটেন্ট আইন', 'উদ্ভাবন'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '11th September 2023',
    commencementDate: '11th September 2023',
    lastAmendedYear: 2023,
    overview: 'Updated patent statute compliant with the WTO-TRIPS framework. Grants 20-year patent protection for novel technological inventions with industrial applicability, while preserving compulsory licensing provisions for essential medicines.',
    overviewBn: 'উদ্ভাবনের স্বীকৃতি, নতুন প্রযুক্তি পেটেন্ট নিবন্ধন, ২০ বছরের মেয়াদ এবং ট্রিপস অনুবর্তী পেটেন্ট সুরক্ষা সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1428.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1428',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 11 September 2023',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 98,
    relatedLawIds: ['bd-trademarks-act-2009', 'bd-copyright-act-2023', 'bd-gi-goods-act-2013'],
    sections: [
      {
        number: 'Section 6',
        title: 'Patentable Inventions (Novelty & Industrial Applicability)',
        titleBn: 'পেটেন্টযোগ্য উদ্ভাবন (নতুনত্ব ও শিল্পে প্রয়োগযোগ্যতা)',
        content: 'An invention is patentable if it is new, involves an inventive step, and is capable of industrial application.',
        contentBn: 'যেকোনো প্রযুক্তিগত উদ্ভাবন যাতে নতুনত্ব, উদ্ভাবনী কৌশল এবং শিল্পক্ষেত্রে বাণিজ্যিক প্রয়োগযোগ্যতা বিদ্যমান, তা পেটেন্টযোগ্য।',
        simpleExplanation: 'Sets out the 3 international criteria for patent eligibility in Bangladesh.',
      },
    ],
  },
  {
    id: 'bd-gi-goods-act-2013',
    title: 'The Geographical Indication of Goods (Registration and Protection) Act, 2013',
    titleBn: 'ভৌগোলিক নির্দেশক পণ্য (নিবন্ধন ও সুরক্ষা) আইন, ২০১৩',
    shortTitle: 'GI Goods Act (জিআই পণ্য আইন)',
    alternateTitles: ['Act No. LIV of 2013', '২০১৩ সালের ৫৪ নং আইন'],
    enactmentYear: 2013,
    actNumber: 'Act No. LIV of 2013',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 39,
    volumeCitation: 'The Bangladesh Code, Volume XXXIX (2013–2014), Act LIV of 2013',
    category: 'Intellectual Property Law',
    categorySlug: 'intellectual-property',
    subcategories: ['GI Registration', 'Jamdani & Hilsa GI Tags', 'Authorized User Certificates', 'Infringement Injunctions'],
    ministry: 'Ministry of Industries / DPDT',
    keywords: ['geographical indication', 'gi tag', 'jamdani', 'hilsa', 'dpdt', 'ভৌগোলিক নির্দেশক', 'জিআই ট্যাগ', 'জামদানি'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '10th November 2013',
    commencementDate: '10th November 2013',
    lastAmendedYear: 2013,
    overview: 'Specialized IP statute safeguarding unique geographical heritage goods of Bangladesh (such as Jamdani Sari, Padma Hilsa, Khirsapat Mango, Bagda Chingri, Tangail Sari) from commercial misappropriation.',
    overviewBn: 'বাংলাদেশের ঐতিহ্যবাহী স্থানীয় পণ্য যেমন জামদানি, ইলিশ ও অন্যান্য ভৌগোলিক পণ্যের জিআই ট্যাগ নিবন্ধন ও সুরক্ষার আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1123.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1123',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 10 November 2013',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 34,
    relatedLawIds: ['bd-trademarks-act-2009', 'bd-patent-act-2023'],
    sections: [
      {
        number: 'Section 8',
        title: 'Registration of Geographical Indications',
        titleBn: 'ভৌগোলিক নির্দেশক নিবন্ধন',
        content: 'Any association of persons or producers representing the interest of producers of goods may apply to the Registrar for registration of a Geographical Indication.',
        contentBn: 'ঐতিহ্যবাহী উৎপাদকদের সমিতি জিআই নিবন্ধনের জন্য আবেদন করতে পারে।',
        simpleExplanation: 'Empowers local artisan collectives to register and protect Bangladesh\'s geographical heritage brands.',
      },
    ],
  },
];
