import { BangladeshLawRecord } from '../bdcode-architecture';

export const CONSTITUTIONAL_CRIMINAL_LAWS: BangladeshLawRecord[] = [
  // 1. CONSTITUTIONAL LAW
  {
    id: 'bd-constitution-1972',
    title: 'The Constitution of the People’s Republic of Bangladesh',
    titleBn: 'গণপ্রজাতন্ত্রী বাংলাদেশের সংবিধান',
    shortTitle: 'Constitution (সংবিধান)',
    alternateTitles: ['Constitution of 1972', 'গণপ্রজাতন্ত্রী বাংলাদেশের সর্বোচ্চ আইন', 'Supreme Law of Bangladesh'],
    enactmentYear: 1972,
    actNumber: 'Adopted 4 November 1972',
    actType: 'Constitutional Amendment',
    era: 'bangladesh-era',
    volumeNumber: 15,
    volumeCitation: 'The Bangladesh Code, Volume XV (1971–1973), Supreme Enactment',
    category: 'Constitutional & Fundamental Rights',
    categorySlug: 'constitutional-law',
    subcategories: ['Fundamental Rights', 'Writ Petitions (Art. 102)', 'Fundamental Principles of State Policy', 'Judiciary', 'Executive'],
    ministry: 'Legislative and Parliamentary Affairs Division',
    keywords: ['constitution', 'fundamental rights', 'article 102', 'article 27', 'article 31', 'article 32', 'writ', 'habeas corpus', 'সংবিধান', 'মৌলিক অধিকার', 'রিট'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '4th November 1972',
    commencementDate: '16th December 1972',
    lastAmendedYear: 2018,
    lastAmendmentAct: 'Constitution (Seventeenth Amendment) Act, 2018',
    overview: 'The supreme charter of the People\'s Republic of Bangladesh. Establishes the supremacy of the constitution, declares unconstitutional any inconsistent statute under Article 7, guarantees enforceable fundamental human rights under Part III, and empowers the High Court Division with writ jurisdiction under Article 102.',
    overviewBn: 'গণপ্রজাতন্ত্রী বাংলাদেশের সর্বোচ্চ আইন। সংবিধানের ৭ অনুচ্ছেদ অনুযায়ী সকল আইনের উপর সংবিধানের প্রাধান্য এবং তৃতীয় ভাগে মৌলিক অধিকার নিশ্চিত করা হয়েছে।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-367.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/367',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 14 December 1972',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    checksumSha256: '99bc45de82903ab10283e7489201cbde81938a9201948201948291039849201a',
    totalSectionsCount: 153,
    relatedLawIds: ['bd-crpc-1898', 'bd-cpc-1908', 'bd-penal-code-1860'],
    sections: [
      {
        number: 'Article 7',
        title: 'Supremacy of the Constitution',
        titleBn: 'সংবিধানের প্রাধান্য',
        content: '(1) All powers in the Republic belong to the people, and their exercise on behalf of the people shall be effected only under, and by the authority of, this Constitution. (2) This Constitution is, as the solemn expression of the will of the people, the supreme law of the Republic, and if any other law is inconsistent with this Constitution that other law shall, to the extent of the inconsistency, be void.',
        contentBn: '(১) প্রজাতন্ত্রের সকল ক্ষমতার মালিক জনগণ; এবং জনগণের পক্ষে সেই ক্ষমতার প্রয়োগ কেবল এই সংবিধানের অধীন ও কর্তৃত্বে কার্যকর হইবে। (২) জনগণের অভিপ্রায়ের পরম অভিব্যক্তিরূপে এই সংবিধান প্রজাতন্ত্রের সর্বোচ্চ আইন এবং অন্য কোন আইন যদি এই সংবিধানের সহিত অসামঞ্জস্য হয়, তাহা হইলে সেই আইনের যতখানি অসামঞ্জস্যপূর্ণ, ততখানি বাতিল হইবে।',
        simpleExplanation: 'Constitutional supremacy: The Constitution is the supreme law of Bangladesh; any statute or action conflicting with it is null and void.',
      },
      {
        number: 'Article 27',
        title: 'Equality before Law',
        titleBn: 'আইনের দৃষ্টিতে সমতা',
        content: 'All citizens are equal before law and are entitled to equal protection of law.',
        contentBn: 'সকল নাগরিক আইনের দৃষ্টিতে সমান এবং আইনের সমান আশ্রয় লাভের অধিকারী।',
        simpleExplanation: 'Guarantees that state organs cannot discriminate arbitrarily and must apply laws equally to all citizens.',
      },
      {
        number: 'Article 31',
        title: 'Right to Protection of Law',
        titleBn: 'আইনের আশ্রয়লাভের অধিকার',
        content: 'To enjoy the protection of the law, and to be treated in accordance with law, and only in accordance with law, is the inalienable right of every citizen, wherever he may be, and of every other person for the time being within Bangladesh, and in particular no action detrimental to the life, liberty, body, reputation or property of any person shall be taken except in accordance with law.',
        contentBn: 'আইনের আশ্রয়লাভ এবং আইনানুযায়ী ব্যবহার লাভ প্রত্যেক নাগরিকের অবিচ্ছেদ্য অধিকার। জীবন, স্বাধীনতা, দেহ, সুনাম বা সম্পত্তিতে হস্তক্ষেপ কেবল আইনানুগভাবেই করা যাইবে।',
        simpleExplanation: 'Fundamental guarantee of due process and legality in every state action affecting citizens.',
      },
      {
        number: 'Article 32',
        title: 'Protection of Right to Life and Personal Liberty',
        titleBn: 'জীবন ও ব্যক্তি-স্বাধীনতার অধিকার রক্ষণ',
        content: 'No person shall be deprived of life or personal liberty save in accordance with law.',
        contentBn: 'আইনানুযায়ী ব্যতীত জীবন ও ব্যক্তি-স্বাধীনতা হইতে কোন ব্যক্তিকে বঞ্চিত করা যাইবে না।',
        simpleExplanation: 'Fundamental guarantee protecting human life, physical freedom, and personal liberty against extra-legal executive action.',
      },
      {
        number: 'Article 39',
        title: 'Freedom of Thought, Conscience and Speech',
        titleBn: 'চিন্তা, বিবেক ও বাক-স্বাধীনতা',
        content: '(1) Freedom of thought and conscience is guaranteed. (2) Subject to any reasonable restrictions imposed by law in the interests of the security of the State, friendly relations with foreign states, public order, decency or morality, or in relation to contempt of court, defamation or incitement to an offence: (a) the right of every citizen to freedom of speech and expression; and (b) freedom of the press, are guaranteed.',
        contentBn: '(১) চিন্তা ও বিবেকের স্বাধীনতার নিশ্চয়তাদান করা হইল। (২) রাষ্ট্রের নিরাপত্তা, আইন-শৃঙ্খলা ও শালীনতার স্বার্থে যুক্তিসঙ্গত বাধানিষেধ সাপেক্ষে বাক-স্বাধীনতা ও সংবাদক্ষেত্রের স্বাধীনতা নিশ্চিত করা হইল।',
        simpleExplanation: 'Protects the citizen\'s freedom of expression, opinions, and independent press reporting.',
      },
      {
        number: 'Article 102',
        title: 'Powers of High Court Division to Issue Certain Orders and Directions (Writ Jurisdiction)',
        titleBn: 'কতিপয় আদেশ ও নির্দেশ ইত্যাদি দানের ক্ষেত্রে হাইকোর্ট বিভাগের ক্ষমতা (রিট এখতিয়ার)',
        content: '(1) The High Court Division on the application of any person aggrieved may give such directions or orders to any person or authority, including any person performing any function in connection with the affairs of the Republic, as may be appropriate for the enforcement of any of the fundamental rights conferred by Part III of this Constitution. (2) The High Court Division may, if satisfied that no other equally efficacious remedy is provided by law, issue writs in the nature of Prohibition, Mandamus, Certiorari, Habeas Corpus, and Quo Warranto.',
        contentBn: 'মৌলিক অধিকার বলবৎকরণ ও ন্যায়বিচার নিশ্চিতকরণে হাইকোর্ট বিভাগ কর্তৃক হেবিয়াস কর্পাস, ম্যান্ডামাস, সার্টিওরায়রি, প্রহিবিশন ও কো-ওয়ারেন্টো রিট জারির ক্ষমতা।',
        simpleExplanation: 'Enforces fundamental rights through constitutional writ petitions against unlawful government actions, illegal detentions, and jurisdictional excesses.',
      },
    ],
  },

  // 2. CRIMINAL LAW & PROCEDURE
  {
    id: 'bd-penal-code-1860',
    title: 'The Penal Code, 1860',
    titleBn: 'দণ্ডবিধি, ১৮৬০',
    shortTitle: 'Penal Code (দণ্ডবিধি)',
    alternateTitles: ['Act No. XLV of 1860', '১৮৬০ সালের ৪৫ নং আইন', 'Indian Penal Code 1860 (Bangladesh Adaptation)'],
    enactmentYear: 1860,
    actNumber: 'Act No. XLV of 1860',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 1,
    volumeCitation: 'The Bangladesh Code, Volume I (1836–1871), Act XLV',
    category: 'Criminal & Penal Law',
    categorySlug: 'criminal-law',
    subcategories: ['Homicide', 'Offenses Against Property', 'Defamation', 'Conspiracy & Joint Liability', 'General Exceptions'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['penal code', 'dondobidhi', 'murder', 'theft', 'robbery', 'extortion', 'section 302', 'section 34', 'section 420', 'mens rea', 'দণ্ডবিধি', 'খুন', 'চুরি', 'প্রতারণা'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '6th October 1860',
    commencementDate: '1st May 1862',
    lastAmendedYear: 2004,
    lastAmendmentAct: 'Act No. XXII of 2004',
    overview: 'The primary substantive criminal law statute of Bangladesh. Codifies general criminal liability, statutory offenses against the human body, property, state security, and public tranquility.',
    overviewBn: 'বাংলাদেশের প্রধান সারগর্ভ ফৌজদারি আইন। অপরাধের দায়দায়িত্ব, মানবদেহ, সম্পত্তি ও রাষ্ট্রীয় নিরাপত্তার বিরুদ্ধে অপরাধের দণ্ড নির্ধারণ করে।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-11.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/11',
    officialGazetteCitation: 'Legislative Enactment Act XLV of 1860 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    checksumSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    totalSectionsCount: 511,
    relatedLawIds: ['bd-crpc-1898', 'bd-evidence-act-1872', 'bd-nari-o-shishu-2000'],
    sections: [
      {
        number: 'Section 34',
        title: 'Acts Done by Several Persons in Furtherance of Common Intention',
        titleBn: 'সাধারণ অভিপ্রায় বাস্তবায়নে একাধিক ব্যক্তি কর্তৃক কৃত কার্য',
        content: 'When a criminal act is done by several persons in furtherance of the common intention of all, each of such persons is liable for that act in the same manner as if it were done by him alone.',
        contentBn: 'যখন একাধিক ব্যক্তি সকলের সাধারণ অভিপ্রায় বাস্তবায়নে একটি অপরাধমূলক কাজ সম্পাদন করে, তখন তাদের প্রত্যেকের উক্ত কাজের জন্য এমনভাবে দায়ী করা হবে যেন কাজটি সে একাই করেছে।',
        simpleExplanation: 'Joint criminal liability doctrine: if two or more people share a pre-arranged plan and participate together, each is punished as the primary actor.',
        isBailable: false,
        isCognizable: true,
      },
      {
        number: 'Section 300',
        title: 'Murder',
        titleBn: 'খুন',
        content: 'Except in the cases hereinafter excepted, culpable homicide is murder, if the act by which the death is caused is done with the intention of causing death, or with the intention of causing such bodily injury as the offender knows to be likely to cause the death.',
        contentBn: 'ব্যতিক্রমসমূহ ব্যতীত, অপরাধজনক নরহত্যাকে খুন গণ্য করা হবে যদি কাজটি মৃত্যু ঘটানোর অভিপ্রায়ে করা হয়, অথবা এমন শারীরিক আঘাত করার অভিপ্রায়ে করা হয় যা অপরাধীর জানা মতে মৃত্যু ঘটাতে পারে।',
        simpleExplanation: 'Defines intentional killing as murder, establishing the high Mens Rea threshold versus culpable homicide not amounting to murder.',
        isBailable: false,
        isCognizable: true,
      },
      {
        number: 'Section 302',
        title: 'Punishment for Murder',
        titleBn: 'খুনের শাস্তি',
        content: 'Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine.',
        contentBn: 'যে ব্যক্তি খুন করে, সে ব্যক্তি মৃত্যুদণ্ডে বা যাবজ্জীবন কারাদণ্ডে দণ্ডিত হবে এবং তদুপরি অর্থদণ্ডেও দণ্ডিত হবে।',
        simpleExplanation: 'Mandates either capital punishment (death) or life imprisonment alongside a statutory fine for murder convictions.',
        penalty: 'Death penalty or Life Imprisonment, plus fine',
        isBailable: false,
        isCognizable: true,
      },
      {
        number: 'Section 378',
        title: 'Theft',
        titleBn: 'চুরি',
        content: 'Whoever, intending to take dishonestly any movable property out of the possession of any person without that person\'s consent, moves that property in order to such taking, is said to commit theft.',
        contentBn: 'যে ব্যক্তি কোনো ব্যক্তির দখল হতে তার সম্মতি ব্যতীত কোনো অস্থাবর সম্পত্তি অসদুপায়ে নেওয়ার অভিপ্রায়ে উক্ত সম্পত্তি স্থানান্তর করে, সে ব্যক্তি চুরি করেছে বলে গণ্য হয়।',
        simpleExplanation: 'Moving movable property out of another\'s possession with dishonest intention and without consent constitutes theft.',
        isBailable: false,
        isCognizable: true,
      },
      {
        number: 'Section 420',
        title: 'Cheating and Dishonestly Inducing Delivery of Property',
        titleBn: 'প্রতারণা এবং অসদুপায়ে সম্পত্তি হস্তান্তরে প্ররোচিত করা',
        content: 'Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.',
        contentBn: 'যে ব্যক্তি প্রতারণা করে এবং প্রতারিত ব্যক্তিকে কোনো সম্পত্তি হস্তান্তর করতে অসদুপায়ে প্ররোচিত করে, সে ব্যক্তি অনধিক সাত বছর মেয়াদের যে কোনো বর্ণনার কারাদণ্ডে এবং অর্থদণ্ডেও দণ্ডিত হবে।',
        simpleExplanation: 'Fraudulent inducement causing someone to transfer valuable assets or money is punishable with up to 7 years imprisonment.',
        penalty: 'Imprisonment up to 7 years and fine',
        isBailable: true,
        isCognizable: true,
      },
    ],
  },
  {
    id: 'bd-crpc-1898',
    title: 'The Code of Criminal Procedure, 1898',
    titleBn: 'ফৌজদারি কার্যবিধি, ১৮৯৮',
    shortTitle: 'CrPC (ফৌজদারি কার্যবিধি)',
    alternateTitles: ['Act No. V of 1898', '১৮৯৮ সালের ৫ নং আইন', 'Code of Criminal Procedure 1898'],
    enactmentYear: 1898,
    actNumber: 'Act No. V of 1898',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 4,
    volumeCitation: 'The Bangladesh Code, Volume IV (1898–1908), Act V',
    category: 'Criminal & Penal Law',
    categorySlug: 'criminal-law',
    subcategories: ['Arrest & Bail', 'Investigation & FIR', 'Trial Procedure', 'Magisterial Powers', 'Revision & Appeal'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['crpc', 'criminal procedure', 'bail', 'fir', 'investigation', 'section 497', 'section 144', 'section 154', 'section 164', 'জামিন', 'এফআইআর', 'তদন্ত'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '22nd March 1898',
    commencementDate: '1st July 1898',
    lastAmendedYear: 2009,
    lastAmendmentAct: 'Act No. XXXII of 2009',
    overview: 'The primary procedural code governing criminal justice in Bangladesh. Regulates police investigation machinery, FIR registration, arrest safeguards, bail conditions, trials before Magistrates and Sessions Courts, and appellate remedies.',
    overviewBn: 'বাংলাদেশের প্রধান ফৌজদারি কার্যপদ্ধতি বিষয়ক আইন। এজাহার, গ্রেপ্তার, রিমান্ড, জামিন, তদন্ত ও বিচার প্রক্রিয়া নিয়ন্ত্রণ করে।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-75.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/75',
    officialGazetteCitation: 'Legislative Enactment Act V of 1898 (Reorganized via Ordinance No. XXIV of 1982 & Act XXXII of 2009)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    checksumSha256: 'a12bc9382fa084cb9348e3a2b0e9102c9182a3948e91823ab02938491029384e',
    totalSectionsCount: 565,
    relatedLawIds: ['bd-penal-code-1860', 'bd-evidence-act-1872', 'bd-constitution-1972'],
    sections: [
      {
        number: 'Section 54',
        title: 'When Police May Arrest Without Warrant',
        titleBn: 'পুলিশ যখন পরোয়ানা ব্যতিরেকে গ্রেপ্তার করতে পারে',
        content: 'Any police-officer may, without an order from a Magistrate and without a warrant, arrest any person who has been concerned in any cognizable offence, or against whom a reasonable complaint has been made, or credible information has been received, or a reasonable suspicion exists.',
        contentBn: 'যেকোনো পুলিশ অফিসার ম্যাজিস্ট্রেটের আদেশ বা পরোয়ানা ব্যতীত এমন ব্যক্তিকে গ্রেপ্তার করতে পারেন যে আমলযোগ্য অপরাধে জড়িত বা যার বিরুদ্ধে যুক্তিসঙ্গত অভিযোগ বা বিশ্বাসযোগ্য তথ্য রয়েছে।',
        simpleExplanation: 'Specifies circumstances where police officers can arrest without a warrant, subject to the protective guidelines in Blast v. Bangladesh.',
        isBailable: false,
        isCognizable: true,
      },
      {
        number: 'Section 154',
        title: 'Information in Cognizable Cases (FIR)',
        titleBn: 'আমলযোগ্য মামলার ক্ষেত্রে সংবাদ (এজাহার বা এফআইআর)',
        content: 'Every information relating to the commission of a cognizable offence if given orally to an officer in charge of a police-station, shall be reduced to writing by him or under his direction, and be read over to the informant; and every such information, whether given in writing or reduced to writing as aforesaid, shall be signed by the person giving it, and the substance thereof shall be entered in a book to be kept by such officer in such form as the Government may prescribe in this behalf.',
        contentBn: 'আমলযোগ্য অপরাধের সংবাদ মৌখিকভাবে থানায় দেওয়া হলে তা লিপিবদ্ধ করতে হবে, তথ্যদাতাকে পড়ে শোনাতে হবে এবং রেজিস্টারে এন্ট্রি করতে হবে।',
        simpleExplanation: 'Statutory basis for First Information Report (FIR). Mandates police to register reports of cognizable offenses without delay.',
        isBailable: true,
        isCognizable: true,
      },
      {
        number: 'Section 167',
        title: 'Procedure When Investigation Cannot Be Completed in Twenty-Four Hours (Remand)',
        titleBn: 'তদন্ত ২৪ ঘণ্টায় সমাপ্ত না হইলে পদ্ধতি ও রিমান্ড',
        content: 'Whenever any person is arrested and detained in custody, and it appears that the investigation cannot be completed within the period of twenty-four hours, the officer in charge of the police-station shall forward the accused to the nearest Magistrate. The Magistrate may authorize the detention of the accused in such custody as such Magistrate thinks fit, for a term not exceeding fifteen days in the whole.',
        contentBn: '২৪ ঘণ্টার মধ্যে তদন্ত সমাপ্ত না হলে আসামিকে ম্যাজিস্ট্রেটের নিকট হাজির করতে হবে এবং আদালত যুক্তিসঙ্গত কারণে সর্বোচ্চ ১৫ দিন পর্যন্ত রিমান্ড বা পুলিশ হেফাজতে প্রেরণের আদেশ দিতে পারেন।',
        simpleExplanation: 'Governs remand and magisterial custody, capping total police custody at 15 days under strict judicial oversight.',
        isBailable: false,
        isCognizable: true,
      },
      {
        number: 'Section 497',
        title: 'When Bail May Be Taken in Case of Non-Bailable Offence',
        titleBn: 'অজামিনযোগ্য অপরাধের ক্ষেত্রে যখন জামিন মঞ্জুর করা যেতে পারে',
        content: 'When any person accused of or suspected of the commission of any non-bailable offence is arrested or detained without warrant by an officer in charge of a police-station, or appears or is brought before a Court, he may be released on bail, but he shall not be so released if there appear reasonable grounds for believing that he has been guilty of an offence punishable with death or imprisonment for life: Provided that the Court may direct that any person under the age of sixteen years or any woman or any sick or infirm person accused of such an offence be released on bail.',
        contentBn: 'অজামিনযোগ্য অপরাধের অভিযুক্ত ব্যক্তি আদালত কর্তৃক জামিনে মুক্তি পেতে পারে, তবে মৃত্যুদণ্ড বা যাবজ্জীবন কারাদণ্ডযোগ্য অপরাধের যুক্তিসঙ্গত কারণ থাকলে জামিন পাবে না। ব্যতিক্রম: ১৬ বছরের কম বয়সী, নারী, অসুস্থ বা অক্ষম ব্যক্তি।',
        simpleExplanation: 'Core judicial bail discretion for non-bailable offenses, containing statutory exceptions for minors, women, and the sick.',
      },
      {
        number: 'Section 498',
        title: 'Power to Direct Admission to Bail or Reduction of Bail (Anticipatory Bail)',
        titleBn: 'জামিন মঞ্জুর বা জামিনের শর্ত শিথিলের বিষয়ে হাইকোর্ট ও দায়রা আদালতের ক্ষমতা',
        content: 'The High Court Division or Court of Session may, in any case, whether there be an appeal on conviction or not, direct that any person be admitted to bail, or that the bail required by a police-officer or Magistrate be reduced.',
        contentBn: 'হাইকোর্ট বিভাগ বা দায়রা জজ আদালত যেকোনো পরিস্থিতিতে জামিন মঞ্জুর বা আগাম জামিন (Anticipatory Bail) প্রদান করতে পারে।',
        simpleExplanation: 'Empowers higher courts to grant anticipatory bail to protect individuals facing imminent arrest on politically motivated or frivolous accusations.',
      },
    ],
  },
  {
    id: 'bd-evidence-act-1872',
    title: 'The Evidence Act, 1872',
    titleBn: 'সাক্ষ্য আইন, ১৮৭২',
    shortTitle: 'Evidence Act (সাক্ষ্য আইন)',
    alternateTitles: ['Act No. I of 1872', '১৮৭২ সালের ১ নং আইন'],
    enactmentYear: 1872,
    actNumber: 'Act No. I of 1872',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 2,
    volumeCitation: 'The Bangladesh Code, Volume II (1872–1882), Act I',
    category: 'Criminal & Penal Law',
    categorySlug: 'criminal-law',
    subcategories: ['Admissibility of Evidence', 'Digital & Electronic Evidence', 'Burden of Proof', 'Witness Examination'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['evidence act', 'sakho ain', 'confession', 'digital evidence', 'section 114', 'burden of proof', 'section 101', 'সাক্ষ্য আইন', 'ডিজিটাল প্রমাণ', 'স্বীকারোক্তি'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '15th March 1872',
    commencementDate: '1st September 1872',
    lastAmendedYear: 2022,
    lastAmendmentAct: 'Act No. XXI of 2022 (Digital Evidence Amendment)',
    overview: 'Governs the admissibility, relevancy, and weight of evidence in civil and criminal proceedings. Modernized by the 2022 amendment to recognize digital records, forensic electronic signatures, and biometric data.',
    overviewBn: 'দেওয়ানি ও ফৌজদারি আদালতে প্রমাণের প্রাসঙ্গিকতা, গ্রহণযোগ্যতা ও ডিজিটাল সাক্ষ্যের স্বীকৃতি প্রদানকারী আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-24.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/24',
    officialGazetteCitation: 'Legislative Enactment Act I of 1872 (Amended via Act XXI of 2022)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    checksumSha256: '44cd901234ef5678901234bc5678901234de5678901234fa5678901234567890',
    totalSectionsCount: 167,
    relatedLawIds: ['bd-crpc-1898', 'bd-cpc-1908', 'bd-penal-code-1860'],
    sections: [
      {
        number: 'Section 24',
        title: 'Confession Caused by Inducement, Threat or Promise, When Irrelevant in Criminal Proceeding',
        titleBn: 'প্ররোচনা, হুমকি বা প্রতিশ্রুতির কারণে প্রদত্ত স্বীকারোক্তির অপ্রাসঙ্গিকতা',
        content: 'A confession made by an accused person is irrelevant in a criminal proceeding, if the making of the confession appears to the Court to have been caused by any inducement, threat or promise proceed from a person in authority.',
        contentBn: 'ক্ষমতাপ্রাপ্ত ব্যক্তির হুমকি, প্ররোচনা বা প্রলোভনে প্রদত্ত কোনো স্বীকারোক্তি আদালতে অপ্রাসঙ্গিক এবং গ্রহণযোগ্য নয়।',
        simpleExplanation: 'Confessions obtained through police coercion, intimidation, or false promises are legally inadmissible.',
      },
      {
        number: 'Section 65B',
        title: 'Admissibility of Electronic Records and Digital Data',
        titleBn: 'ইলেকট্রনিক রেকর্ড ও ডিজিটাল তথ্যের গ্রহণযোগ্যতা',
        content: 'Any information contained in an electronic record which is printed on a paper, stored, recorded or copied in optical or magnetic media produced by a computer shall be deemed to be also a document and shall be admissible in any proceedings, without further proof or production of the original.',
        contentBn: 'কম্পিউটার বা ডিজিটাল মাধ্যমে সংরক্ষিত তথ্য, ইমেল, ভিডিও বা ইলেকট্রনিক রেকর্ড যথাযথ সনদসহ মূল দলিলের ন্যায় গ্রহণযোগ্য।',
        simpleExplanation: 'Inserted by 2022 amendment: Recognizes CCTV footage, emails, chat transcripts, and digital files as direct evidence.',
      },
      {
        number: 'Section 101',
        title: 'Burden of Proof',
        titleBn: 'প্রমাণের দায়িত্ব',
        content: 'Whoever desires any Court to give judgment as to any legal right or liability dependent on the existence of facts which he asserts, must prove that those facts exist. When a person is bound to prove the existence of any fact, it is said that the burden of proof lies on that person.',
        contentBn: 'যে ব্যক্তি আদালতের নিকট কোনো আইনি অধিকার বা দায়ের বিষয়ে রায় প্রার্থনা করে, ঘটনার সত্যতা প্রমাণের দায়িত্ব তার উপর বর্তায়।',
        simpleExplanation: 'The party who makes a positive legal claim or criminal accusation bears the burden of proving it in court.',
      },
    ],
  },
  {
    id: 'bd-nari-o-shishu-2000',
    title: 'The Nari O Shishu Nirjatan Daman Ain, 2000',
    titleBn: 'নারী ও শিশু নির্যাতন দমন আইন, ২০০০',
    shortTitle: 'Nari O Shishu Ain (নারী ও শিশু আইন)',
    alternateTitles: ['Act No. VIII of 2000', '২০০০ সালের ৮ নং আইন', 'Women and Children Repression Prevention Act 2000'],
    enactmentYear: 2000,
    actNumber: 'Act No. VIII of 2000',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 32,
    volumeCitation: 'The Bangladesh Code, Volume XXXII (1999–2000), Act VIII',
    category: 'Criminal & Penal Law',
    categorySlug: 'criminal-law',
    subcategories: ['Crimes Against Women & Children', 'Dowry Death', 'Special Tribunals', 'In Camera Trial'],
    ministry: 'Ministry of Law, Justice and Parliamentary Affairs',
    keywords: ['nari o shishu', 'women and children', 'dowry', 'sexual violence', 'special tribunal', 'section 9', 'section 11', 'নারী ও শিশু', 'যৌতুক', 'ট্রাইব্যুনাল'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '14th February 2000',
    commencementDate: '14th February 2000',
    lastAmendedYear: 2020,
    lastAmendmentAct: 'Act No. XIX of 2020',
    overview: 'Specialized penal enactment establishing dedicated Nari O Shishu Nirjatan Daman Tribunals for the expeditious trial of sexual violence, trafficking, abduction, acid violence, and dowry-related deaths.',
    overviewBn: 'নারী ও শিশুদের প্রতি সহিংসতা, ধর্ষণ, যৌতুক দাবি ও এসিড নিক্ষেপের মতো গুরুতর অপরাধের দ্রুত বিচারের জন্য বিশেষ ট্রাইব্যুনাল সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-835.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/835',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 14 February 2000',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    checksumSha256: '88ab345678ef9012345678ab9012345678cd9012345678ef9012345678901234',
    totalSectionsCount: 34,
    relatedLawIds: ['bd-penal-code-1860', 'bd-crpc-1898', 'bd-evidence-act-1872'],
    sections: [
      {
        number: 'Section 9(1)',
        title: 'Punishment for Rape',
        titleBn: 'ধর্ষণের শাস্তি',
        content: 'Whoever commits rape on a woman or a child shall be punished with death or imprisonment for life and shall also be liable to fine.',
        contentBn: 'যদি কোনো পুরুষ কোনো নারী বা শিশুকে ধর্ষণ করে, তবে সে মৃত্যুদণ্ডে বা যাবজ্জীবন সশ্রম কারাদণ্ডে দণ্ডনীয় হবে এবং অর্থদণ্ডেও দণ্ডনীয় হবে।',
        simpleExplanation: 'Provides capital punishment or life imprisonment for rape convictions following the 2020 amendment.',
        penalty: 'Death or Rigorous Life Imprisonment, plus fine',
        isBailable: false,
        isCognizable: true,
      },
      {
        number: 'Section 11',
        title: 'Punishment for Causing Death or Grievous Hurt for Dowry',
        titleBn: 'যৌতুকের জন্য মৃত্যু ঘটানো বা অঙ্গহানির শাস্তি',
        content: 'If the husband of a woman, or the father, mother, guardian, relative or any other person on behalf of the husband, causes death of a woman for dowry, he shall be punished with death or life imprisonment and fine.',
        contentBn: 'যৌতুকের দাবিতে কোনো নারীর মৃত্যু ঘটালে সংশ্লিষ্ট ব্যক্তি মৃত্যুদণ্ডে বা যাবজ্জীবন কারাদণ্ডে এবং অর্থদণ্ডে দণ্ডিত হবে।',
        simpleExplanation: 'Severe statutory liability for dowry extortion and fatal domestic violence against wives.',
      },
      {
        number: 'Section 17',
        title: 'Punishment for Filing False Complaint or Case',
        titleBn: 'মিথ্যা মামলা বা অভিযোগ দায়েরের শাস্তি',
        content: 'If any person brings a false or vexatious complaint or information against any person under this Act with the intent to harm, such person shall be punished with imprisonment up to seven years and fine.',
        contentBn: 'ক্ষতিসাধনের উদ্দেশ্যে এই আইনের অধীন কোনো মিথ্যা বা হয়রানিমূলক মামলা দায়ের করিলে অনধিক ৭ বছর কারাদণ্ড এবং অর্থদণ্ড প্রদেয়।',
        simpleExplanation: 'Strict criminal penalties against malicious or fabricated accusations under this special statute.',
      },
    ],
  },
  {
    id: 'bd-acc-act-2004',
    title: 'The Anti-Corruption Commission Act, 2004',
    titleBn: 'দুর্নীতি দমন কমিশন আইন, ২০০৪',
    shortTitle: 'ACC Act (দুদক আইন)',
    alternateTitles: ['Act No. XXIII of 2004', '২০০৪ সালের ২৩ নং আইন', 'Dudok Ain 2004'],
    enactmentYear: 2004,
    actNumber: 'Act No. XXIII of 2004',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 34,
    volumeCitation: 'The Bangladesh Code, Volume XXXIV (2003–2004), Act XXIII',
    category: 'Criminal & Penal Law',
    categorySlug: 'criminal-law',
    subcategories: ['Anti-Corruption', 'Illicit Enrichment', 'Special Court Trials', 'Asset Declaration'],
    ministry: 'Cabinet Division / Anti-Corruption Commission',
    keywords: ['acc', 'dudok', 'anti corruption', 'bribery', 'illicit enrichment', 'asset declaration', 'section 26', 'section 27', 'দুর্নীতি দমন কমিশন'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '23rd February 2004',
    commencementDate: '9th May 2004',
    lastAmendedYear: 2016,
    lastAmendmentAct: 'Act No. XX of 2016',
    overview: 'Statutory framework establishing the independent Anti-Corruption Commission (ACC/দুদক) of Bangladesh. Empowers the commission to investigate bribery, abuse of official power, money laundering predicates, and illicit wealth accumulation by public servants and citizens.',
    overviewBn: 'দুর্নীতি দমন, প্রতিরোধ ও অনুসন্ধানের লক্ষ্যে স্বাধীন দুর্নীতি দমন কমিশন প্রতিষ্ঠা এবং অবৈধ সম্পদ অর্জনের বিচার সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-918.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/918',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 23 February 2004',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 38,
    relatedLawIds: ['bd-penal-code-1860', 'bd-crpc-1898', 'bd-money-laundering-2012'],
    sections: [
      {
        number: 'Section 17',
        title: 'Functions and Powers of the Commission',
        titleBn: 'কমিশনের কার্যাবলি ও ক্ষমতা',
        content: 'The Commission shall inquire into and conduct investigations of offenses specified in the Schedule, file cases before the Special Judge Court, and undertake preventive anti-corruption advocacy.',
        contentBn: 'তফসিলভুক্ত অপরাধসমূহের অনুসন্ধান ও তদন্ত পরিচালনা, মামলা দায়ের এবং দুর্নীতি প্রতিরোধে জনসচেতনতা সৃষ্টি কমিশনের মূল দায়িত্ব।',
        simpleExplanation: 'Defines the statutory powers of the ACC to investigate bribery and public graft.',
      },
      {
        number: 'Section 26',
        title: 'Declaration of Assets and Properties',
        titleBn: 'সম্পদের হিসাব বা বিবরণী দাখিলের নোটিশ',
        content: 'If the Commission is satisfied that any person or any other person on his behalf possesses wealth or property disproportionate to his known sources of income, the Commission may issue an order directing such person to submit a written statement of his assets and liabilities.',
        contentBn: 'জ্ঞাত আয়ের উৎসের সাথে অসঙ্গতিপূর্ণ সম্পদের তথ্য পাওয়া গেলে কমিশন সংশ্লিষ্ট ব্যক্তিকে সম্পদের হিসাব দাখিলের নোটিশ প্রদান করতে পারে।',
        simpleExplanation: 'Empowers ACC to demand formal sworn statements of wealth from individuals suspected of unexplained enrichment.',
      },
      {
        number: 'Section 27',
        title: 'Possession of Disproportionate Assets (Illicit Wealth)',
        titleBn: 'জ্ঞাত আয়ের বহির্ভূত সম্পদ অর্জনের দণ্ড',
        content: 'If any person possesses in his own name or in the name of any other person on his behalf any property, movable or immovable, which is disproportionate to his known sources of income, he shall be punished with imprisonment for a term up to ten years and fine, and such property shall be liable to confiscation.',
        contentBn: 'জ্ঞাত আয়ের উৎসের সহিত অসঙ্গতিপূর্ণ সম্পদ অর্জন বা ভোগদখল করলে অনধিক ১০ বছর কারাদণ্ড ও অর্থদণ্ড এবং উক্ত অবৈধ সম্পত্তি বাজেয়াপ্ত হবে।',
        simpleExplanation: 'Criminalizes possession of unexplained assets, carrying up to 10 years imprisonment and full confiscation of wealth by the state.',
        penalty: 'Imprisonment up to 10 years, fine, and confiscation of assets',
        isBailable: false,
        isCognizable: true,
      },
    ],
  },
  {
    id: 'bd-special-powers-1974',
    title: 'The Special Powers Act, 1974',
    titleBn: 'বিশেষ ক্ষমতা আইন, ১৯৭৪',
    shortTitle: 'Special Powers Act (বিশেষ ক্ষমতা আইন)',
    alternateTitles: ['Act No. XIV of 1974', '১৯৭৪ সালের ১৪ নং আইন'],
    enactmentYear: 1974,
    actNumber: 'Act No. XIV of 1974',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 16,
    volumeCitation: 'The Bangladesh Code, Volume XVI (1974–1975), Act XIV',
    category: 'Criminal & Penal Law',
    categorySlug: 'criminal-law',
    subcategories: ['Preventive Detention', 'Anti-Smuggling', 'Adulteration & Black Marketing', 'Special Tribunals'],
    ministry: 'Ministry of Home Affairs',
    keywords: ['special powers act', 'preventive detention', 'smuggling', 'adulteration', 'section 3', 'special tribunal', 'বিশেষ ক্ষমতা আইন', 'কালোবাজারি'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '9th February 1974',
    commencementDate: '9th February 1974',
    lastAmendedYear: 2014,
    overview: 'Statute enacted to provide special measures for preventing anti-state activities, hoarding, black-marketing, smuggling, currency counterfeiting, food adulteration, and maintaining essential supplies.',
    overviewBn: 'রাষ্ট্রবিরোধী কার্যকলাপ, চোরাচালান, মজুদদারি, কালোবাজারি এবং খাদ্য ভেজাল প্রতিরোধের বিশেষ আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-472.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/472',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 9 February 1974',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 36,
    relatedLawIds: ['bd-crpc-1898', 'bd-penal-code-1860', 'bd-constitution-1972'],
    sections: [
      {
        number: 'Section 3',
        title: 'Power to Make Orders Detaining or Restricting Movements of Certain Persons',
        titleBn: 'কতিপয় ব্যক্তির আটক বা চলাফেরা নিয়ন্ত্রণের আদেশ দানের ক্ষমতা',
        content: 'The Government may, if satisfied with respect to any person that with a view to preventing him from doing any prejudicial act it is necessary so to do, make an order directing that such person be detained.',
        contentBn: 'ক্ষতিকর কাজ প্রতিরোধে সরকারকে কোনো ব্যক্তিকে নিবর্তনমূলক আটক (Preventive Detention) করার ক্ষমতা প্রদান করে।',
        simpleExplanation: 'Provides preventive detention powers, subject to constitutional safeguards under Article 33 and Advisory Board review.',
      },
      {
        number: 'Section 25B',
        title: 'Penalty for Smuggling',
        titleBn: 'চোরাচালানের শাস্তি',
        content: 'Whoever smuggles any goods into or out of Bangladesh in contravention of any law shall be punished with death or imprisonment for life or rigorous imprisonment up to fourteen years and fine.',
        contentBn: 'আইন লঙ্ঘন করিয়া কোনো পণ্য চোরাচালান করিলে সংশ্লিষ্ট ব্যক্তি মৃত্যুদণ্ড বা যাবজ্জীবন কারাদণ্ড বা অনধিক ১৪ বছর সশ্রম কারাদণ্ডে দণ্ডিত হইবে।',
        simpleExplanation: 'Imposes severe penalties up to capital punishment for cross-border smuggling of goods and currency.',
        penalty: 'Death, Life Imprisonment, or Rigorous Imprisonment up to 14 years',
      },
    ],
  },
  {
    id: 'bd-narcotics-control-2018',
    title: 'The Narcotics Control Act, 2018',
    titleBn: 'মাদকদ্রব্য নিয়ন্ত্রণ আইন, ২০১৮',
    shortTitle: 'Narcotics Control Act (মাদকদ্রব্য নিয়ন্ত্রণ আইন)',
    alternateTitles: ['Act No. LXIII of 2018', '২০১৮ সালের ৬৩ নং আইন'],
    enactmentYear: 2018,
    actNumber: 'Act No. LXIII of 2018',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 41,
    volumeCitation: 'The Bangladesh Code, Volume XLI (2018–2019), Act LXIII',
    category: 'Criminal & Penal Law',
    categorySlug: 'criminal-law',
    subcategories: ['Drug Trafficking', 'Yaba & Synthetic Drugs', 'Department of Narcotics Control (DNC)', 'Rehabilitation'],
    ministry: 'Security Services Division, Ministry of Home Affairs',
    keywords: ['narcotics control', 'dnc', 'yaba', 'heroin', 'drug trafficking', 'section 36', 'মাদকদ্রব্য নিয়ন্ত্রণ', 'ইয়াবা'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '27th December 2018',
    commencementDate: '27th December 2018',
    lastAmendedYear: 2020,
    overview: 'Comprehensive penal framework for preventing drug abuse, illicit trafficking, manufacture, and distribution of narcotics and psychotropic substances (including Yaba, Ice, and synthetic opioids) in Bangladesh.',
    overviewBn: 'মাদকদ্রব্য অপব্যবহার, চোরাচালান, ইয়াবা ও সিন্থেটিক মাদক পাচার রোধে প্রণীত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1264.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1264',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 27 December 2018',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 70,
    relatedLawIds: ['bd-crpc-1898', 'bd-penal-code-1860'],
    sections: [
      {
        number: 'Section 9',
        title: 'Prohibition on Cultivation, Production, and Transportation of Narcotics',
        titleBn: 'মাদকদ্রব্যের চাষাবাদ, উৎপাদন ও পরিবহন নিষিদ্ধকরণ',
        content: 'No person shall cultivate, produce, manufacture, possess, transport, import, export, sell, purchase or use any narcotic substance without a statutory license.',
        contentBn: 'আইনসম্মত লাইসেন্স ব্যতীত কোনো ব্যক্তি কোনো মাদকদ্রব্য চাষ, উৎপাদন, পরিবহন বা সংরক্ষণ করিতে পারিবে না।',
        simpleExplanation: 'Complete statutory ban on unauthorized narcotics handling.',
      },
      {
        number: 'Section 36',
        title: 'Penalties for Offenses Relating to Narcotics Substances',
        titleBn: 'মাদকদ্রব্য সম্পর্কিত অপরাধের দণ্ডসমূহ',
        content: 'Prescribes statutory table of sentences ranging from 6 months imprisonment up to death penalty or life imprisonment depending on the quantity of seized narcotics (e.g. over 200 grams of heroin or over 100 grams of Yaba/Amphetamine).',
        contentBn: 'হেরোইন, ইয়াবা বা কোকেনের মতো বিপজ্জনক মাদকের নির্ধারিত পরিমাণের অতিরিক্ত মজুদের ক্ষেত্রে মৃত্যুদণ্ড বা যাবজ্জীবন কারাদণ্ডের বিধান।',
        simpleExplanation: 'Prescribes graded punishments, including capital punishment for commercial-scale drug cartels.',
        penalty: 'Graded from 1 year imprisonment up to Death Penalty for high volume trafficking',
        isBailable: false,
        isCognizable: true,
      },
    ],
  },
];

export const CONSTITUTIONAL_AND_CRIMINAL_LAWS = CONSTITUTIONAL_CRIMINAL_LAWS;
