import { BangladeshLawRecord } from '../bdcode-architecture';

export const ENVIRONMENT_ADMIN_LOCAL_CYBER_LAWS: BangladeshLawRecord[] = [
  // 11. ENVIRONMENTAL LAW
  {
    id: 'bd-environment-conservation-1995',
    title: 'The Bangladesh Environment Conservation Act, 1995',
    titleBn: 'বাংলাদেশ পরিবেশ সংরক্ষণ আইন, ১৯৯৫',
    shortTitle: 'Environment Conservation Act (পরিবেশ সংরক্ষণ আইন)',
    alternateTitles: ['Act No. I of 1995', '১৯৯৫ সালের ১ নং আইন', 'ECA 1995'],
    enactmentYear: 1995,
    actNumber: 'Act No. I of 1995',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 29,
    volumeCitation: 'The Bangladesh Code, Volume XXIX (1995–1996), Act I of 1995',
    category: 'Environmental & Energy Law',
    categorySlug: 'environmental-law',
    subcategories: ['Environmental Clearance (ECC)', 'Ecologically Critical Areas (ECA)', 'Polythene Prohibition (Sec 6A)', 'Pollution Penalties (Sec 15)'],
    ministry: 'Ministry of Environment, Forest and Climate Change / DoE',
    keywords: ['environment conservation', 'doe', 'ecc', 'pollution', 'polythene ban', 'section 12', 'পরিবেশ সংরক্ষণ', 'পরিবেশ ছাড়পত্র', 'পলিথিন নিষিদ্ধ'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '16th February 1995',
    commencementDate: '16th February 1995',
    lastAmendedYear: 2010,
    lastAmendmentAct: 'Act No. L of 2010',
    overview: 'The principal environmental statute of Bangladesh. Empowers the Department of Environment (DoE) to control industrial pollution, declare Ecologically Critical Areas (ECA), mandate Environmental Clearance Certificates (ECC) for factories, and penalize environmental polluters.',
    overviewBn: 'পরিবেশ দূষণ নিয়ন্ত্রণ, শিল্প-কারখানার জন্য পরিবেশগত ছাড়পত্র (ইসিসি) গ্রহণ, পলিথিন নিষিদ্ধকরণ ও প্রতিবেশগত সংকটাপন্ন এলাকা ঘোষণা সংক্রান্ত মূল আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-791.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/791',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 16 February 1995',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 22,
    relatedLawIds: ['bd-environment-court-2010', 'bd-forest-act-1927', 'bd-water-act-2013'],
    sections: [
      {
        number: 'Section 6A',
        title: 'Prohibition on Manufacture, Import, and Marketing of Polythene Shopping Bags',
        titleBn: 'পলিথিন শপিং ব্যাগ উৎপাদন, আমদানি ও বাজারজাতকরণ নিষিদ্ধকরণ',
        content: 'The Government may, by notification in the official Gazette, impose an absolute ban or restriction on the manufacture, import, marketing, sale, display for sale, stocking, distribution, commercial transportation or commercial use of polythene shopping bags.',
        contentBn: 'পরিবেশ সুরক্ষায় পলিথিন শপিং ব্যাগ উৎপাদন, পরিবহন, মজুদ ও বিক্রয় সম্পূর্ণ নিষিদ্ধ।',
        simpleExplanation: 'Statutory basis for the national ban on thin polythene plastic bags in Bangladesh.',
      },
      {
        number: 'Section 12',
        title: 'Environmental Clearance Certificate (ECC)',
        titleBn: 'পরিবেশগত ছাড়পত্র (ইসিসি) গ্রহণের বাধ্যবাধকতা',
        content: 'No industrial unit or project shall be established or undertaken without obtaining, in the manner prescribed by the rules, an Environmental Clearance Certificate from the Director General.',
        contentBn: 'পরিবেশ অধিদপ্তরের মহাপরিচালক হতে নির্ধারিত পদ্ধতিতে পরিবেশগত ছাড়পত্র গ্রহণ ব্যতীত কোনো শিল্প কারখানা স্থাপন করা যাবে না।',
        simpleExplanation: 'Mandates prior Environmental Impact Assessment (EIA) and DoE clearance for all factories and infrastructure projects.',
      },
    ],
  },
  {
    id: 'bd-environment-court-2010',
    title: 'The Environment Court Act, 2010',
    titleBn: 'পরিবেশ আদালত আইন, ২০১০',
    shortTitle: 'Environment Court Act (পরিবেশ আদালত আইন)',
    alternateTitles: ['Act No. LVI of 2010', '২০১০ সালের ৫৬ নং আইন'],
    enactmentYear: 2010,
    actNumber: 'Act No. LVI of 2010',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 37,
    volumeCitation: 'The Bangladesh Code, Volume XXXVII (2010), Act LVI of 2010',
    category: 'Environmental & Energy Law',
    categorySlug: 'environmental-law',
    subcategories: ['Special Environmental Courts', 'Environmental Damage Compensation', 'Appellate Environment Court'],
    ministry: 'Ministry of Environment / Ministry of Law',
    keywords: ['environment court', 'poribesh adalat', 'pollution compensation', 'doe', 'পরিবেশ আদালত', 'ক্ষতিপূরণ'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '5th October 2010',
    commencementDate: '5th October 2010',
    lastAmendedYear: 2010,
    overview: 'Specialized judicial framework establishing Environment Courts and an Environment Appellate Court in every division to try offenses under environmental laws and award financial compensation for ecological damage.',
    overviewBn: 'পরিবেশ দূষণজনিত অপরাধের দ্রুত বিচার এবং পরিবেশগত ক্ষতির আর্থিক ক্ষতিপূরণ আদায়ের জন্য বিশেষ পরিবেশ আদালত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1057.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1057',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 5 October 2010',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 22,
    relatedLawIds: ['bd-environment-conservation-1995'],
    sections: [
      {
        number: 'Section 4',
        title: 'Establishment of Environment Courts',
        titleBn: 'পরিবেশ আদালত প্রতিষ্ঠা',
        content: 'The Government shall establish one or more Environment Courts in each division to try environmental offenses and award compensation.',
        contentBn: 'পরিবেশ সংক্রান্ত অপরাধের বিচারার্থে প্রতিটি বিভাগে এক বা একাধিক পরিবেশ আদালত গঠিত হবে।',
        simpleExplanation: 'Provides dedicated courts headed by Joint District Judges to adjudicate environmental damage.',
      },
    ],
  },
  {
    id: 'bd-forest-act-1927',
    title: 'The Forest Act, 1927',
    titleBn: 'বন আইন, ১৯২৭',
    shortTitle: 'Forest Act (বন আইন)',
    alternateTitles: ['Act No. XVI of 1927', '১৯২৭ সালের ১৬ নং আইন'],
    enactmentYear: 1927,
    actNumber: 'Act No. XVI of 1927',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 6,
    volumeCitation: 'The Bangladesh Code, Volume VI (1920–1929), Act XVI of 1927',
    category: 'Environmental & Energy Law',
    categorySlug: 'environmental-law',
    subcategories: ['Reserved Forests', 'Protected Forests', 'Illegal Logging Penalties (Sec 26)', 'Seizure of Timber (Sec 52)'],
    ministry: 'Forest Department / Ministry of Environment, Forest and Climate Change',
    keywords: ['forest act', 'reserved forest', 'sundarbans', 'illegal logging', 'timber', 'বন আইন', 'সংরক্ষিত বন', 'সুন্দরবন', 'গাছ কাটা'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '21st September 1927',
    commencementDate: '21st September 1927',
    lastAmendedYear: 2000,
    overview: 'Regulates state forest management, declaration of Reserved and Protected Forests (including the Sundarbans mangrove), penalties for illegal logging, wildlife habitat destruction, and timber transit rules in Bangladesh.',
    overviewBn: 'সংরক্ষিত বন ঘোষণা, সুন্দরবন সহ জাতীয় বনভূমি সুরক্ষা, অবৈধ বৃক্ষনিধন ও কাঠ পাচার প্রতিরোধ সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-140.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/140',
    officialGazetteCitation: 'Legislative Enactment Act XVI of 1927 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 86,
    relatedLawIds: ['bd-environment-conservation-1995'],
    sections: [
      {
        number: 'Section 26',
        title: 'Acts Prohibited in Reserved Forests',
        titleBn: 'সংরক্ষিত বনে নিষিদ্ধ কার্যাবলি ও তার দণ্ড',
        content: 'Any person who makes any fresh clearing, sets fire, fells, girdles, lops, or damages any tree, or hunts, shoots, or fishes in a reserved forest shall be punished with imprisonment up to five years and fine.',
        contentBn: 'সংরক্ষিত বনাঞ্চলে অনধিকার প্রবেশ, গাছ কাটা, আগুন লাগানো বা শিকার করা কঠোর শাস্তিযোগ্য অপরাধ।',
        simpleExplanation: 'Prohibits unauthorized tree felling and encroachment in protected forest reserves.',
      },
    ],
  },
  {
    id: 'bd-water-act-2013',
    title: 'The Bangladesh Water Act, 2013',
    titleBn: 'বাংলাদেশ পানি আইন, ২০১৩',
    shortTitle: 'Water Act (পানি আইন)',
    alternateTitles: ['Act No. XIV of 2013', '২০১৩ সালের ১৪ নং আইন'],
    enactmentYear: 2013,
    actNumber: 'Act No. XIV of 2013',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 39,
    volumeCitation: 'The Bangladesh Code, Volume XXXIX (2013–2014), Act XIV of 2013',
    category: 'Environmental & Energy Law',
    categorySlug: 'environmental-law',
    subcategories: ['Right to Potable Water', 'Water Stress Areas', 'Aquifer Protection', 'Effluent Discharge Limits'],
    ministry: 'Ministry of Water Resources / WARPO',
    keywords: ['water act', 'drinking water', 'groundwater', 'aquifer', 'warpo', 'পানি আইন', 'ভূগর্ভস্থ পানি'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '2nd May 2013',
    commencementDate: '2nd May 2013',
    lastAmendedYear: 2013,
    overview: 'Consolidates governance over integrated water resources management, state ownership of water bodies, right to safe drinking water, groundwater extraction regulation, and wetland protection.',
    overviewBn: 'নিরাপদ খাবার পানির অধিকার, ভূগর্ভস্থ পানির অপচয় রোধ ও দেশের সামগ্রিক পানি সম্পদ ব্যবস্থাপনা আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1114.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1114',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 2 May 2013',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 39,
    relatedLawIds: ['bd-environment-conservation-1995'],
    sections: [
      {
        number: 'Section 3',
        title: 'Right to Safe Drinking Water and State Custodianship of Water Resources',
        titleBn: 'নিরাপদ খাবার পানির মৌলিক অধিকার ও পানির ওপর রাষ্ট্রের মালিকানা',
        content: 'All water within Bangladesh belongs to the people, and the Government shall hold and manage it on their behalf. The right to potable water and water for sanitation is guaranteed as first priority.',
        contentBn: 'দেশের সকল পানির মালিক জনগণ এবং নিরাপদ খাবার পানি ও স্যানিটেশনের অধিকারকে সর্বোচ্চ অগ্রাধিকার প্রদান।',
        simpleExplanation: 'Affirms that access to clean drinking water is a guaranteed priority human right.',
      },
    ],
  },

  // 12. ADMINISTRATIVE AND REGULATORY LAW
  {
    id: 'bd-rti-act-2009',
    title: 'The Right to Information Act, 2009',
    titleBn: 'তথ্য অধিকার আইন, ২০০৯',
    shortTitle: 'RTI Act (তথ্য অধিকার আইন)',
    alternateTitles: ['Act No. XX of 2009', '২০০৯ সালের ২০ নং আইন'],
    enactmentYear: 2009,
    actNumber: 'Act No. XX of 2009',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 36,
    volumeCitation: 'The Bangladesh Code, Volume XXXVI (2007–2009), Act XX of 2009',
    category: 'Administrative & Public Law',
    categorySlug: 'administrative-regulatory',
    subcategories: ['Citizen Access to Public Records', 'Designated Officers (DO)', '20-Day Response Deadline', 'Information Commission Appeals'],
    ministry: 'Information Commission / Ministry of Information',
    keywords: ['right to information', 'rti', 'information commission', 'designated officer', 'section 8', 'তথ্য অধিকার', 'তথ্য কমিশন'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '6th April 2009',
    commencementDate: '20th October 2008',
    lastAmendedYear: 2009,
    overview: 'Empowers citizens to request and obtain official information from government bodies, statutory corporations, and foreign-funded NGOs within strict statutory deadlines (20 working days). Establishes the Information Commission.',
    overviewBn: 'সরকারি, আধা-সরকারি ও এনজিও প্রতিষ্ঠান হতে নাগরিকের তথ্য প্রাপ্তির আইনগত অধিকার এবং তথ্য কমিশন সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1015.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1015',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 6 April 2009',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 37,
    relatedLawIds: ['bd-constitution-1972'],
    sections: [
      {
        number: 'Section 4',
        title: 'Right to Information',
        titleBn: 'তথ্য প্রাপ্তির অধিকার',
        content: 'Subject to the provisions of this Act, every citizen shall have the right to obtain information from any authority, and it shall be the duty of every authority to provide information to the citizen.',
        contentBn: 'এই আইনের বিধান সাপেক্ষে প্রত্যেক নাগরিকের যেকোনো কর্তৃপক্ষ হইতে তথ্য লাভের অধিকার থাকিবে এবং কর্তৃপক্ষ তথ্য প্রদানে বাধ্য থাকিবে।',
        simpleExplanation: 'Guarantees the citizen’s right to access public records and government documentation.',
      },
      {
        number: 'Section 8',
        title: 'Request for Information and 20-Day Delivery Deadline',
        titleBn: 'তথ্য প্রাপ্তির আবেদন ও ২০ কার্যদিবসের মধ্যে তথ্য সরবরাহের সময়সীমা',
        content: 'Any person may apply in writing to the Designated Officer for information. The Designated Officer shall provide the information within twenty working days from the date of receipt of the request.',
        contentBn: 'দায়িত্বপ্রাপ্ত কর্মকর্তা আবেদন প্রাপ্তির ২০ কার্যদিবসের মধ্যে এবং জীবন-মৃত্যুর ক্ষেত্রে ৪৮ ঘণ্টার মধ্যে তথ্য সরবরাহ করবেন।',
        simpleExplanation: 'Sets a strict 20-day limit for public bodies to provide requested information.',
      },
    ],
  },
  {
    id: 'bd-admin-tribunals-1980',
    title: 'The Administrative Tribunals Act, 1980',
    titleBn: 'প্রশাসনিক ট্রাইব্যুনাল আইন, ১৯৮০',
    shortTitle: 'Administrative Tribunals (প্রশাসনিক ট্রাইব্যুনাল)',
    alternateTitles: ['Act No. VII of 1981', '১৯৮১ সালের ৭ নং আইন'],
    enactmentYear: 1980,
    actNumber: 'Act No. VII of 1981',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 19,
    volumeCitation: 'The Bangladesh Code, Volume XIX (1980–1982), Act VII of 1981',
    category: 'Administrative & Public Law',
    categorySlug: 'administrative-regulatory',
    subcategories: ['Civil Servants Service Disputes', 'Pensions & Promotions', 'Disciplinary Appeals', 'Administrative Appellate Tribunal'],
    ministry: 'Ministry of Public Administration / Ministry of Law',
    keywords: ['administrative tribunal', 'civil service', 'government servant', 'pension', 'promotion', 'প্রশাসনিক ট্রাইব্যুনাল', 'সরকারি কর্মচারী'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '5th June 1981',
    commencementDate: '1st September 1982',
    lastAmendedYear: 1997,
    overview: 'Constitutional statute established under Article 117 of the Constitution of Bangladesh, vesting exclusive jurisdiction in Administrative Tribunals over service terms, seniority, pensions, and disciplinary dismissals of persons in the service of the Republic.',
    overviewBn: 'সংবিধানের ১১৭ অনুচ্ছেদের আওতায় সরকারি কর্মচারীদের পদোন্নতি, জ্যেষ্ঠতা, পেনশন ও বরখাস্ত সংক্রান্ত বিরোধের একক ট্রাইব্যুনাল।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-606.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/606',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 5 June 1981',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 13,
    relatedLawIds: ['bd-constitution-1972'],
    sections: [
      {
        number: 'Section 4',
        title: 'Jurisdiction of Administrative Tribunals',
        titleBn: 'প্রশাসনিক ট্রাইব্যুনালের বিচারিক এখতিয়ার',
        content: 'An Administrative Tribunal shall have exclusive jurisdiction to hear and determine applications made by any person in the service of the Republic in respect of the terms and conditions of his service, including pension rights.',
        contentBn: 'প্রজাতন্ত্রের কর্মে নিয়োজিত কর্মচারীদের চাকরির শর্তাবলি, পদোন্নতি ও পেনশনের বিষয়ে মোকদ্দমা বিচারের একক এখতিয়ার।',
        simpleExplanation: 'Bars regular civil courts from hearing government servant employment disputes, reserving them exclusively for Administrative Tribunals.',
      },
    ],
  },
  {
    id: 'bd-general-clauses-1897',
    title: 'The General Clauses Act, 1897',
    titleBn: 'সাধারণ দফা আইন, ১৮৯৭',
    shortTitle: 'General Clauses Act (সাধারণ দফা আইন)',
    alternateTitles: ['Act No. X of 1897', '১৮৯৭ সালের ১০ নং আইন'],
    enactmentYear: 1897,
    actNumber: 'Act No. X of 1897',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 3,
    volumeCitation: 'The Bangladesh Code, Volume III (1882–1897), Act X of 1897',
    category: 'Administrative & Public Law',
    categorySlug: 'administrative-regulatory',
    subcategories: ['Statutory Interpretation', 'Effect of Repeal (Sec 6)', 'Computation of Time (Sec 9)', 'Standard Definitions'],
    ministry: 'Legislative and Parliamentary Affairs Division',
    keywords: ['general clauses', 'statutory interpretation', 'repeal', 'section 6', 'computation of time', 'আইন ব্যাখ্যা', 'বাতিল আইনের কার্যকারিতা'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '11th March 1897',
    commencementDate: '11th March 1897',
    lastAmendedYear: 2012,
    overview: 'The fundamental statute for statutory interpretation in Bangladesh. Standardizes definitions across all enactments, regulates the legal effect of legislative repeals, calculation of time periods, and exercise of statutory executive powers.',
    overviewBn: 'আইনের ব্যাখ্যা, প্রমিত সংজ্ঞা এবং কোনো আইন বাতিল বা প্রতিস্থাপিত হলে তার অতীত অধিকার ও মামলার ওপর ফলাফল নির্ধারণ সংক্রান্ত মূল আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-70.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/70',
    officialGazetteCitation: 'Legislative Enactment Act X of 1897 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 31,
    relatedLawIds: ['bd-constitution-1972'],
    sections: [
      {
        number: 'Section 6',
        title: 'Effect of Repeal',
        titleBn: 'আইন বাতিলের ফলাফল',
        content: 'Where any Act repeals any enactment, then, unless a different intention appears, the repeal shall not: (a) revive anything not in force, (b) affect the previous operation of any enactment, (c) affect any right, privilege, obligation or liability acquired, accrued or incurred under any enactment so repealed, or (d) affect any investigation, legal proceeding or remedy in respect of any such right.',
        contentBn: 'কোনো আইন বাতিল হলেও তার অধীনে ইতিপূর্বে অর্জিত স্বত্ব, দায়িত্ব বা দায়ের ওপর কোনো প্রভাব পড়বে না এবং চলমান বিচার কার্যক্রম অব্যাহত থাকবে।',
        simpleExplanation: 'Core doctrine of statutory repeal: Repealing a law does not extinguish vested legal rights or pending court cases unless explicitly stated.',
      },
    ],
  },

  // 13. PUBLIC HEALTH AND DRUG REGULATION LAW
  {
    id: 'bd-drugs-act-1940',
    title: 'The Drugs Act, 1940',
    titleBn: 'ঔষধ আইন, ১৯৪০',
    shortTitle: 'Drugs Act (ঔষধ আইন)',
    alternateTitles: ['Act No. XXIII of 1940', '১৯৪০ সালের ২৩ নং আইন'],
    enactmentYear: 1940,
    actNumber: 'Act No. XXIII of 1940',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 8,
    volumeCitation: 'The Bangladesh Code, Volume VIII (1940–1946), Act XXIII of 1940',
    category: 'Public Health & Drug Regulation',
    categorySlug: 'public-health-drugs',
    subcategories: ['Adulterated & Misbranded Drugs', 'Drug Inspectors', 'Government Analysts', 'Manufacturing Standards'],
    ministry: 'Directorate General of Drug Administration (DGDA) / Health Services Division',
    keywords: ['drugs act', 'dgda', 'adulterated medicine', 'spurious drug', 'pharmaceutical', 'ঔষধ আইন', 'নকল ওষুধ', 'ড্রাগ প্রশাসন'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '10th April 1940',
    commencementDate: '10th April 1940',
    lastAmendedYear: 2023,
    overview: 'Foundational legislation regulating the import, export, manufacture, distribution, and sale of medicines, active pharmaceutical ingredients (APIs), and preventing adulterated or counterfeit pharmaceutical drugs in Bangladesh.',
    overviewBn: 'ঔষধের মান নিয়ন্ত্রণ, নকল ও ভেজাল ঔষধ উৎপাদন এবং বিক্রয় প্রতিরোধ সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-187.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/187',
    officialGazetteCitation: 'Legislative Enactment Act XXIII of 1940 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 41,
    relatedLawIds: ['bd-drugs-act-2023'],
    sections: [
      {
        number: 'Section 18',
        title: 'Prohibition of Manufacture and Sale of Certain Drugs',
        titleBn: 'ভেজাল ও মানহীন ঔষধ তৈরি ও বিক্রয় নিষিদ্ধকরণ',
        content: 'Prohibits the manufacture for sale, or sell, or stock or exhibit for sale any drug which is not of standard quality, or any misbranded, adulterated or spurious drug.',
        contentBn: 'নকল, ভেজাল বা মানহীন ঔষধ উৎপাদন, সংরক্ষণ ও বিক্রয় সম্পূর্ণ নিষিদ্ধ ও ফৌজদারি অপরাধ।',
        simpleExplanation: 'Strict prohibition against making or selling counterfeit medicines.',
      },
    ],
  },
  {
    id: 'bd-drugs-act-2023',
    title: 'The Drugs and Cosmetics Act, 2023',
    titleBn: 'ঔষধ ও প্রসাধন সামগ্রী আইন, ২০২৩',
    shortTitle: 'Drugs & Cosmetics Act (ঔষধ ও প্রসাধন সামগ্রী আইন)',
    alternateTitles: ['Act No. XLV of 2023', '২০২৩ সালের ৪৫ নং আইন', 'Repealed Drugs (Control) Ordinance 1982'],
    enactmentYear: 2023,
    actNumber: 'Act No. XLV of 2023',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 45,
    volumeCitation: 'The Bangladesh Code, Volume XLV (2022–2023), Act XLV of 2023',
    category: 'Public Health & Drug Regulation',
    categorySlug: 'public-health-drugs',
    subcategories: ['Cosmetics Regulation', 'Medical Devices', 'Life Imprisonment for Adulteration', 'Special Drug Courts'],
    ministry: 'Directorate General of Drug Administration (DGDA) / Ministry of Health',
    keywords: ['drugs and cosmetics', 'dgda', 'cosmetics license', 'medical devices', 'adulterated medicine', 'ঔষধ ও প্রসাধন', 'কসমেটিক্স লাইসেন্স'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '18th September 2023',
    commencementDate: '18th September 2023',
    lastAmendedYear: 2023,
    overview: 'Updated 2023 statute expanding DGDA regulatory oversight over pharmaceuticals, medical devices, and cosmetics. Prescribes up to life imprisonment for manufacturing spurious life-saving medicines and mandates licensing for cosmetic products.',
    overviewBn: 'ঔষধ, চিকিৎসা যন্ত্রপাতি এবং প্রসাধন সামগ্রীর উৎপাদন ও মান নিয়ন্ত্রণে আধুনিক আইন। ভেজাল ঔষধের জন্য যাবজ্জীবন কারাদণ্ডের বিধান।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1439.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1439',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 18 September 2023',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 71,
    relatedLawIds: ['bd-drugs-act-1940'],
    sections: [
      {
        number: 'Section 30',
        title: 'Mandatory Licensing for Cosmetics Manufacture and Import',
        titleBn: 'প্রসাধন সামগ্রী উৎপাদন ও আমদানিতে বাধ্যতামূলক লাইসেন্স গ্রহণ',
        content: 'No person shall manufacture, import, distribute, or sell any cosmetic product without obtaining a license from the Directorate General of Drug Administration.',
        contentBn: 'ড্রাগ প্রশাসনের লাইসেন্স ব্যতীত কোনো প্রসাধন সামগ্রী (কসমেটিক্স) উৎপাদন বা আমদানি করা যাবে না।',
        simpleExplanation: 'Brings cosmetics and skincare products under DGDA safety regulation and licensing.',
      },
    ],
  },
  {
    id: 'bd-tobacco-control-2005',
    title: 'The Smoking and Tobacco Products Usage (Control) Act, 2005',
    titleBn: 'ধূমপান ও তামাকজাত দ্রব্য ব্যবহার (নিয়ন্ত্রণ) আইন, ২০০৫',
    shortTitle: 'Tobacco Control Act (তামাক নিয়ন্ত্রণ আইন)',
    alternateTitles: ['Act No. XI of 2005', '২০০৫ সালের ১১ নং আইন'],
    enactmentYear: 2005,
    actNumber: 'Act No. XI of 2005',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 35,
    volumeCitation: 'The Bangladesh Code, Volume XXXV (2005–2006), Act XI of 2005',
    category: 'Public Health & Drug Regulation',
    categorySlug: 'public-health-drugs',
    subcategories: ['Public Smoking Ban', 'Pictorial Warnings (50%+)', 'Minor Sales Ban', 'Tobacco Advertisement Prohibition'],
    ministry: 'Health Services Division, Ministry of Health and Family Welfare',
    keywords: ['tobacco control', 'smoking ban', 'pictorial warning', 'cigarette advertisement', 'ধূমপান নিয়ন্ত্রণ', 'তামাকজাত দ্রব্য'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '15th March 2005',
    commencementDate: '15th March 2005',
    lastAmendedYear: 2013,
    lastAmendmentAct: 'Act No. XVI of 2013',
    overview: 'Public health legislation banning smoking in public places and transport, prohibiting tobacco advertisements, and mandating 50%+ graphic pictorial health warnings on all cigarette packets.',
    overviewBn: 'পাবলিক প্লেসে ধূমপান নিষিদ্ধকরণ, তামাকজাত দ্রব্যের বিজ্ঞাপন বন্ধ ও প্যাকেটের গায়ে ছবিযুক্ত স্বাস্থ্য সতর্কবার্তা বাধ্যতামূলক করার আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-925.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/925',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 15 March 2005',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 16,
    relatedLawIds: ['bd-environment-conservation-1995'],
    sections: [
      {
        number: 'Section 4',
        title: 'Prohibition of Smoking in Public Places and Public Transport',
        titleBn: 'পাবলিক প্লেস ও গণপরিবহনে ধূমপান নিষিদ্ধকরণ',
        content: 'No person shall smoke in any public place or in any public transport. Any person who contravenes this provision shall be punished with a fine not exceeding three hundred Taka.',
        contentBn: 'হাসপাতাল, শিক্ষাপ্রতিষ্ঠান, বাস, ট্রেন বা পাবলিক প্লেসে ধূমপান করলে অনধিক ৩০০ টাকা জরিমানা প্রদেয়।',
        simpleExplanation: 'Prohibits smoking in shared indoor spaces, government offices, and transit vehicles.',
      },
    ],
  },

  // 14. TELECOMMUNICATIONS, CYBER, AND DIGITAL LAW
  {
    id: 'bd-cyber-security-act-2023',
    title: 'The Cyber Security Act, 2023',
    titleBn: 'সাইবার নিরাপত্তা আইন, ২০২৩',
    shortTitle: 'Cyber Security Act (সাইবার নিরাপত্তা আইন)',
    alternateTitles: ['Act No. XXVII of 2023', '২০২৩ সালের ২৭ নং আইন', 'Repealed Digital Security Act 2018'],
    enactmentYear: 2023,
    actNumber: 'Act No. XXVII of 2023',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 45,
    volumeCitation: 'The Bangladesh Code, Volume XLV (2022–2023), Act XXVII of 2023',
    category: 'Cyber & Technology',
    categorySlug: 'cyber-digital',
    subcategories: ['Critical Information Infrastructure (CII)', 'Cyber Hacking & Identity Theft', 'Cyber Tribunals', 'Bailable Classification'],
    ministry: 'Information and Communication Technology Division',
    keywords: ['cyber security', 'csa', 'hacking', 'identity fraud', 'cyber terrorism', 'cyber tribunal', 'সাইবার নিরাপত্তা', 'হ্যাকিং', 'তথ্যপ্রযুক্তি'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '18th September 2023',
    commencementDate: '18th September 2023',
    lastAmendedYear: 2023,
    overview: 'Statute replacing the 2018 Digital Security Act to penalize cyber attacks against Critical Information Infrastructure (CII), unauthorized digital intrusion, identity fraud, cyber terrorism, and computer hacking.',
    overviewBn: 'গুরুত্বপূর্ণ তথ্য পরিকাঠামোতে বেআইনি প্রবেশ, হ্যাকিং, ডিজিটাল জালিয়াতি ও সাইবার অপরাধ দমনে প্রণীত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1430.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1430',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 18 September 2023',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 60,
    relatedLawIds: ['bd-telecom-act-2001', 'bd-ict-act-2006', 'bd-penal-code-1860'],
    sections: [
      {
        number: 'Section 17',
        title: 'Offence and Punishment for Illegal Access to Critical Information Infrastructure',
        titleBn: 'গুরুত্বপূর্ণ তথ্য পরিকাঠামোতে বেআইনি প্রবেশের শাস্তি',
        content: 'If any person intentionally or knowingly gains access to or causes damage to any Critical Information Infrastructure (CII), he shall be punished with imprisonment up to fourteen years or fine up to one crore Taka or both.',
        contentBn: 'রাষ্ট্রীয় গুরুত্বপূর্ণ কম্পিউটার সিস্টেমে অনধিকার প্রবেশ বা ক্ষতির সৃষ্টি করলে অনধিক ১৪ বছর কারাদণ্ড বা ১ কোটি টাকা অর্থদণ্ড বা উভয় দণ্ডে দণ্ডিত হইবে।',
        simpleExplanation: 'Severe penalties for unauthorized intrusion into banking, power grid, or national identity digital infrastructure.',
        penalty: 'Imprisonment up to 14 years and fine up to 1 Crore Taka',
        isBailable: false,
        isCognizable: true,
      },
      {
        number: 'Section 24',
        title: 'Punishment for Identity Fraud or Impersonation by Digital Means',
        titleBn: 'ডিজিটাল বা ইলেকট্রনিক মাধ্যমে প্রতারণা ও ছদ্মবেশ ধারণের শাস্তি',
        content: 'Whoever intentionally uses any digital or electronic device to impersonate another person or commit fraud shall be punished with imprisonment for a term up to five years or fine up to five lakh Taka or both.',
        contentBn: 'ইলেকট্রনিক মাধ্যমে অন্যের পরিচয় নকল বা মিথ্যা পরিচয় ব্যবহার করে প্রতারণা করলে অনধিক ৫ বছর কারাদণ্ড ও ৫ লক্ষ টাকা অর্থদণ্ড প্রদেয়।',
        simpleExplanation: 'Criminalizes phishing, fake online profiles, and impersonation.',
        penalty: 'Imprisonment up to 5 years or fine up to 5 Lakh Taka',
        isBailable: true,
        isCognizable: true,
      },
    ],
  },
  {
    id: 'bd-telecom-act-2001',
    title: 'The Bangladesh Telecommunication Regulation Act, 2001',
    titleBn: 'বাংলাদেশ টেলিযোগাযোগ নিয়ন্ত্রণ আইন, ২০০১',
    shortTitle: 'Telecom Act (টেলিযোগাযোগ নিয়ন্ত্রণ আইন)',
    alternateTitles: ['Act No. XVIII of 2001', '২০০১ সালের ১৮ নং আইন'],
    enactmentYear: 2001,
    actNumber: 'Act No. XVIII of 2001',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 33,
    volumeCitation: 'The Bangladesh Code, Volume XXXIII (2001–2002), Act XVIII of 2001',
    category: 'Cyber & Technology',
    categorySlug: 'cyber-digital',
    subcategories: ['BTRC Regulatory Powers', 'Telecom Licensing & Spectrum Allocation', 'VoIP Regulation (Sec 73)', 'Lawful Interception'],
    ministry: 'Posts and Telecommunications Division / BTRC',
    keywords: ['telecom act', 'btrc', 'spectrum', 'voip', 'mobile operator', 'টেলিযোগাযোগ', 'বিটিআরসি', 'স্পেকট্রাম'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '16th April 2001',
    commencementDate: '31st January 2002',
    lastAmendedYear: 2010,
    lastAmendmentAct: 'Act No. XXII of 2010',
    overview: 'Statutory framework establishing the Bangladesh Telecommunication Regulatory Commission (BTRC) to regulate mobile operators, ISPs, submarine cables, spectrum allocation, and illegal call routing.',
    overviewBn: 'বিটিআরসি প্রতিষ্ঠা, মোবাইল অপারেটর ও ইন্টারনেট সেবা প্রদানকারীদের লাইসেন্সিং ও স্পেকট্রাম বরাদ্দ সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-867.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/867',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 16 April 2001',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 78,
    relatedLawIds: ['bd-cyber-security-act-2023', 'bd-ict-act-2006'],
    sections: [
      {
        number: 'Section 35',
        title: 'Mandatory Licensing Requirement for Telecommunication Systems',
        titleBn: 'টেলিযোগাযোগ ব্যবস্থার জন্য বাধ্যতামূলক লাইসেন্স গ্রহণ',
        content: 'No person shall establish, maintain, or operate a telecommunication system or provide telecommunication services in Bangladesh without a license issued by the Commission.',
        contentBn: 'কমিশন কর্তৃক প্রদত্ত লাইসেন্স ব্যতিরেকে দেশে কোনো টেলিযোগাযোগ নেটওয়ার্ক বা ইন্টারনেট সেবা পরিচালনা করা যাবে না।',
        simpleExplanation: 'Mandates BTRC licenses for all cellular, satellite, and ISP operations.',
      },
    ],
  },
  {
    id: 'bd-ict-act-2006',
    title: 'The Information and Communication Technology Act, 2006',
    titleBn: 'তথ্য ও যোগাযোগ প্রযুক্তি আইন, ২০০৬',
    shortTitle: 'ICT Act (আইসিটি আইন)',
    alternateTitles: ['Act No. XXXIX of 2006', '২০০৬ সালের ৩৯ নং আইন'],
    enactmentYear: 2006,
    actNumber: 'Act No. XXXIX of 2006',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 35,
    volumeCitation: 'The Bangladesh Code, Volume XXXV (2005–2006), Act XXXIX of 2006',
    category: 'Cyber & Technology',
    categorySlug: 'cyber-digital',
    subcategories: ['Digital Signatures', 'Controller of Certifying Authorities (CCA)', 'Cyber Tribunals', 'Electronic Evidence'],
    ministry: 'ICT Division',
    keywords: ['ict act', 'digital signature', 'cca', 'cyber tribunal', 'electronic record', 'তথ্য ও যোগাযোগ প্রযুক্তি', 'ডিজিটাল স্বাক্ষর'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '8th October 2006',
    commencementDate: '8th October 2006',
    lastAmendedYear: 2013,
    overview: 'Foundational enactment legalizing digital electronic signatures, licensing Certifying Authorities (CCA), and establishing dedicated Cyber Tribunals in Bangladesh.',
    overviewBn: 'ডিজিটাল স্বাক্ষরকে আইনি স্বীকৃতি প্রদান, ইলেকট্রনিক রেকর্ড এবং সাইবার ট্রাইব্যুনাল প্রতিষ্ঠা সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-954.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/954',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 8 October 2006',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 90,
    relatedLawIds: ['bd-cyber-security-act-2023', 'bd-evidence-act-1872'],
    sections: [
      {
        number: 'Section 6',
        title: 'Legal Recognition of Electronic Records',
        titleBn: 'ইলেকট্রনিক রেকর্ডের আইনি স্বীকৃতি',
        content: 'Where any law provides that information or any other matter shall be in writing, such requirement shall be deemed to have been satisfied if such information is rendered or made available in an electronic form.',
        contentBn: 'যেকোনো আইনি নথিপত্রে লিখিত দলিলে তথ্যের ইলেকট্রনিক বা ডিজিটাল ফরম্যাট আইনত সমমর্যাদাসম্পন্ন।',
        simpleExplanation: 'Grants full legal validity to digital contracts and electronic documentation.',
      },
    ],
  },

  // 15. EDUCATION LAW
  {
    id: 'bd-primary-education-1990',
    title: 'The Primary Education (Compulsory) Act, 1990',
    titleBn: 'প্রাথমিক শিক্ষা (বাধ্যতামূলককরণ) আইন, ১৯৯০',
    shortTitle: 'Compulsory Primary Education (বাধ্যতামূলক প্রাথমিক শিক্ষা)',
    alternateTitles: ['Act No. XXVII of 1990', '১৯৯০ সালের ২৭ নং আইন'],
    enactmentYear: 1990,
    actNumber: 'Act No. XXVII of 1990',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 26,
    volumeCitation: 'The Bangladesh Code, Volume XXVI (1990–1991), Act XXVII of 1990',
    category: 'Education & Academic Law',
    categorySlug: 'education-law',
    subcategories: ['Compulsory Schooling (Ages 6-10)', 'Parental Duty', 'Ward Education Committees'],
    ministry: 'Ministry of Primary and Mass Education',
    keywords: ['primary education', 'compulsory schooling', 'child education', 'প্রাথমিক শিক্ষা', 'বাধ্যতামূলক শিক্ষা'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '13th February 1990',
    commencementDate: '13th February 1990',
    lastAmendedYear: 1990,
    overview: 'Mandates free and compulsory primary education for all children aged 6 to 10 across Bangladesh, imposing statutory duties on parents and guardians.',
    overviewBn: '৬ হতে ১০ বছর বয়সী সকল শিশুর জন্য প্রাথমিক শিক্ষা অবৈতনিক ও বাধ্যতামূলক করার আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-734.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/734',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 13 February 1990',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 8,
    relatedLawIds: ['bd-constitution-1972'],
    sections: [
      {
        number: 'Section 3',
        title: 'Compulsory Primary Education for Children',
        titleBn: 'শিশুদের জন্য বাধ্যতামূলক প্রাথমিক শিক্ষা',
        content: 'Every parent or guardian of a child aged between six and ten years shall cause such child to attend a primary educational institution until completion of primary education.',
        contentBn: '৬ হতে ১০ বছর বয়সী প্রত্যেক শিশুকে প্রাথমিক বিদ্যালয়ে প্রেরণ করা অভিভাবকের বাধ্যতামূলক দায়িত্ব।',
        simpleExplanation: 'Requires parents to enroll and keep children in primary school.',
      },
    ],
  },
  {
    id: 'bd-private-university-2010',
    title: 'The Private University Act, 2010',
    titleBn: 'বেসরকারি বিশ্ববিদ্যালয় আইন, ২০১০',
    shortTitle: 'Private University Act (বেসরকারি বিশ্ববিদ্যালয় আইন)',
    alternateTitles: ['Act No. XXXV of 2010', '২০১০ সালের ৩৫ নং আইন'],
    enactmentYear: 2010,
    actNumber: 'Act No. XXXV of 2010',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 37,
    volumeCitation: 'The Bangladesh Code, Volume XXXVII (2010), Act XXXV of 2010',
    category: 'Education & Academic Law',
    categorySlug: 'education-law',
    subcategories: ['Board of Trustees (BOT)', 'UGC Oversight & Approvals', 'Permanent Campus Mandate (Sec 7)', 'Scholarships (3% Quota)'],
    ministry: 'Secondary and Higher Education Division / UGC',
    keywords: ['private university', 'ugc', 'board of trustees', 'permanent campus', 'বেসরকারি বিশ্ববিদ্যালয়', 'ইউজিসি'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '22nd July 2010',
    commencementDate: '22nd July 2010',
    lastAmendedYear: 2010,
    overview: 'Regulatory enactment for establishing and operating private universities in Bangladesh under University Grants Commission (UGC) oversight, mandating permanent campuses, reserve funds, and 3% poor/freedom fighter scholarship quotas.',
    overviewBn: 'বেসরকারি বিশ্ববিদ্যালয় প্রতিষ্ঠা, ট্রাস্টি বোর্ড, স্থায়ী ক্যাম্পাস এবং বিশ্ববিদ্যালয় মঞ্জুরী কমিশনের (ইউজিসি) নিয়ন্ত্রণ সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1044.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1044',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 22 July 2010',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 55,
    relatedLawIds: ['bd-primary-education-1990'],
    sections: [
      {
        number: 'Section 7',
        title: 'Requirement for Permanent Campus Land and Infrastructure',
        titleBn: 'স্থায়ী ক্যাম্পাস ও অবকাঠামো নির্মাণের বাধ্যবাধকতা',
        content: 'Every private university must within the statutory transition period establish its academic activities on its own permanent campus land.',
        contentBn: 'নির্ধারিত সময়ের মধ্যে নিজস্ব জমিতে স্থায়ী ক্যাম্পাস নির্মাণ ও কার্যক্রম পরিচালনা বাধ্যতামূলক।',
        simpleExplanation: 'Requires private universities to transition from rented buildings to permanent campus facilities.',
      },
    ],
  },

  // 16. LOCAL GOVERNMENT LAW
  {
    id: 'bd-union-parishad-2009',
    title: 'The Local Government (Union Parishad) Act, 2009',
    titleBn: 'স্থানীয় সরকার (ইউনিয়ন পরিষদ) আইন, ২০০৯',
    shortTitle: 'Union Parishad Act (ইউনিয়ন পরিষদ আইন)',
    alternateTitles: ['Act No. LXI of 2009', '২০০৯ সালের ৬১ নং আইন'],
    enactmentYear: 2009,
    actNumber: 'Act No. LXI of 2009',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 36,
    volumeCitation: 'The Bangladesh Code, Volume XXXVI (2007–2009), Act LXI of 2009',
    category: 'Local Government & Municipal Law',
    categorySlug: 'local-government',
    subcategories: ['Rural Governance', 'Chairman & Ward Members', 'Birth & Death Registration', 'Village Courts Oversight'],
    ministry: 'Local Government Division (LGD)',
    keywords: ['union parishad', 'local government', 'village court', 'up chairman', 'ward member', 'ইউনিয়ন পরিষদ', 'স্থানীয় সরকার'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '15th October 2009',
    commencementDate: '15th October 2009',
    lastAmendedYear: 2024,
    overview: 'Regulates rural local government administration across Bangladesh\'s 4,500+ Union Parishads. Defines election rules, civic functions (birth/death registration, village sanitation, roads), taxation, and Village Courts.',
    overviewBn: 'গ্রামীণ স্থানীয় সরকার ব্যবস্থা, ইউনিয়ন পরিষদের কার্যাবলি, ট্যাক্স ও গ্রামীণ বিরোধ নিষ্পত্তি সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1033.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1033',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 15 October 2009',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 116,
    relatedLawIds: ['bd-pourashava-act-2009', 'bd-city-corp-2009'],
    sections: [
      {
        number: 'Section 47',
        title: 'Functions of Union Parishad',
        titleBn: 'ইউনিয়ন পরিষদের কার্যাবলি',
        content: 'Union Parishads are responsible for maintaining rural roads, drainage, birth and death records, public health sanitation, and disaster relief.',
        contentBn: 'গ্রামীণ অবকাঠামো রক্ষা, জন্ম-মৃত্যু নিবন্ধন, জনস্বাস্থ্য ও দুর্যোগ ব্যবস্থাপনা ইউনিয়ন পরিষদের দায়িত্ব।',
        simpleExplanation: 'Core civic administrative duties of rural local government.',
      },
    ],
  },
  {
    id: 'bd-pourashava-act-2009',
    title: 'The Local Government (Pourashava) Act, 2009',
    titleBn: 'স্থানীয় সরকার (পৌরসভা) আইন, ২০০৯',
    shortTitle: 'Pourashava Act (পৌরসভা আইন)',
    alternateTitles: ['Act No. LVIII of 2009', '২০০৯ সালের ৫৮ নং আইন'],
    enactmentYear: 2009,
    actNumber: 'Act No. LVIII of 2009',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 36,
    volumeCitation: 'The Bangladesh Code, Volume XXXVI (2007–2009), Act LVIII of 2009',
    category: 'Local Government & Municipal Law',
    categorySlug: 'local-government',
    subcategories: ['Urban Municipalities', 'Mayors & Councillors', 'Holding Tax Assessment (Sec 98)', 'Town Planning'],
    ministry: 'Local Government Division (LGD)',
    keywords: ['pourashava', 'municipality', 'mayor', 'holding tax', 'councillor', 'পৌরসভা', 'পৌর কর'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '6th October 2009',
    commencementDate: '6th October 2009',
    lastAmendedYear: 2024,
    overview: 'Regulates municipal governance in urban Pourashavas throughout Bangladesh. Governs mayoral powers, town planning, building permits, waste management, water supply, and municipal holding tax.',
    overviewBn: 'পৌরসভা সমূহের নাগরিক সেবা, গৃহ কর নির্ধারণ, বর্জ্য ব্যবস্থাপনা ও নগর পরিকল্পনা সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1030.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1030',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 6 October 2009',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 128,
    relatedLawIds: ['bd-union-parishad-2009', 'bd-city-corp-2009'],
    sections: [
      {
        number: 'Section 50',
        title: 'Civic Responsibilities and Public Health Services',
        titleBn: 'পৌরসভার নাগরিক দায়িত্ব ও জনস্বাস্থ্য সেবা',
        content: 'Every Pourashava shall ensure urban sanitation, water drainage, road lighting, and building permit compliance.',
        contentBn: 'পৌর এলাকায় বিশুদ্ধ পানি সরবরাহ, সড়ক বাতি ও ভবন নির্মাণ তদারকি পৌরসভার মূল কাজ।',
        simpleExplanation: 'Mandatory public utility responsibilities of municipal councils.',
      },
    ],
  },
  {
    id: 'bd-city-corp-2009',
    title: 'The Local Government (City Corporation) Act, 2009',
    titleBn: 'স্থানীয় সরকার (সিটি কর্পোরেশন) আইন, ২০০৯',
    shortTitle: 'City Corporation Act (সিটি কর্পোরেশন আইন)',
    alternateTitles: ['Act No. LX of 2009', '২০০৯ সালের ৬০ নং আইন'],
    enactmentYear: 2009,
    actNumber: 'Act No. LX of 2009',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 36,
    volumeCitation: 'The Bangladesh Code, Volume XXXVI (2007–2009), Act LX of 2009',
    category: 'Local Government & Municipal Law',
    categorySlug: 'local-government',
    subcategories: ['Metropolitan Governance', 'City Mayors & Ward Councillors', 'Metropolitan Holding Tax', 'Urban Master Plans'],
    ministry: 'Local Government Division (LGD)',
    keywords: ['city corporation', 'dhaka mayor', 'chattogram city', 'holding tax', 'urban governance', 'সিটি কর্পোরেশন', 'মেয়র', 'কাউন্সিলর'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '15th October 2009',
    commencementDate: '15th October 2009',
    lastAmendedYear: 2024,
    overview: 'Governs metropolitan administration across all City Corporations in Bangladesh (Dhaka North, Dhaka South, Chattogram, Rajshahi, Khulna, Sylhet, Barishal, Rangpur, Gazipur, Narayanganj, Cumilla, Mymensingh).',
    overviewBn: 'ঢাকা, চট্টগ্রাম সহ সকল মহানগর সিটি কর্পোরেশনের মেয়র, কাউন্সিলর এবং নাগরিক সেবা প্রশাসন সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1032.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1032',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 15 October 2009',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 127,
    relatedLawIds: ['bd-pourashava-act-2009', 'bd-union-parishad-2009'],
    sections: [
      {
        number: 'Section 41',
        title: 'Metropolitan Functions of City Corporations',
        titleBn: 'সিটি কর্পোরেশনের মহানগরীয় কার্যাবলি',
        content: 'City Corporations shall manage major urban drainage, public health, traffic coordination, waste management, and trade licensing.',
        contentBn: 'মহানগরে বর্জ্য নিষ্কাশন, ট্রেড লাইসেন্স প্রদান ও নাগরিক সুবিধা উন্নয়ন সিটি কর্পোরেশনের দায়িত্ব।',
        simpleExplanation: 'Metropolitan governance and municipal trade licensing powers.',
      },
    ],
  },

  // 17. IMMIGRATION, CITIZENSHIP, AND NATIONALITY LAW
  {
    id: 'bd-citizenship-act-1951',
    title: 'The Citizenship Act, 1951',
    titleBn: 'নাগরিকত্ব আইন, ১৯৫১',
    shortTitle: 'Citizenship Act (নাগরিকত্ব আইন)',
    alternateTitles: ['Act No. II of 1951', '১৯৫১ সালের ২ নং আইন'],
    enactmentYear: 1951,
    actNumber: 'Act No. II of 1951',
    actType: 'Act of Parliament',
    era: 'pakistan-era',
    volumeNumber: 10,
    volumeCitation: 'The Bangladesh Code, Volume X (1951–1955), Act II of 1951',
    category: 'Immigration & Citizenship Law',
    categorySlug: 'immigration-citizenship',
    subcategories: ['Citizenship by Birth (Sec 3)', 'Citizenship by Descent (Sec 5)', 'Naturalization (Sec 9)', 'Deprivation (Sec 16)'],
    ministry: 'Security Services Division, Ministry of Home Affairs',
    keywords: ['citizenship act', 'nationality', 'naturalization', 'birthright citizenship', 'descent', 'নাগরিকত্ব আইন', 'জাতীয়তা'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '13th April 1951',
    commencementDate: '13th April 1951',
    lastAmendedYear: 2008,
    overview: 'Foundational statute governing acquisition of citizenship by birth (Jus Soli), descent (Jus Sanguinis), registration, and naturalization in Bangladesh.',
    overviewBn: 'জন্মসূত্রে, বংশানুক্রমে এবং নিবন্ধনের মাধ্যমে বাংলাদেশের নাগরিকত্ব লাভ ও অবসানের মূল আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-244.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/244',
    officialGazetteCitation: 'Legislative Enactment Act II of 1951 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 22,
    relatedLawIds: ['bd-citizenship-po-1972', 'bd-passport-act-1920', 'bd-foreigners-act-1946'],
    sections: [
      {
        number: 'Section 3',
        title: 'Citizenship by Birth',
        titleBn: 'জন্মসূত্রে নাগরিকত্ব',
        content: 'Every person born in Bangladesh after the commencement of this Act shall be a citizen of Bangladesh by birth.',
        contentBn: 'এই আইনের পর বাংলাদেশে জন্মগ্রহণকারী প্রত্যেক ব্যক্তি জন্মসূত্রে বাংলাদেশের নাগরিক গণ্য হইবে।',
        simpleExplanation: 'Grants birthright citizenship to persons born on Bangladesh soil.',
      },
      {
        number: 'Section 5',
        title: 'Citizenship by Descent',
        titleBn: 'বংশসূত্রে নাগরিকত্ব',
        content: 'A person born after the commencement of this Act shall be a citizen of Bangladesh by descent if his father or mother was a citizen of Bangladesh at the time of his birth.',
        contentBn: 'বিদেশে জন্ম নেওয়া কোনো শিশুর পিতা বা মাতার একজন বাংলাদেশী নাগরিক হইলে সে বংশসূত্রে নাগরিকত্ব লাভ করিবে।',
        simpleExplanation: 'Provides citizenship to children born abroad to Bangladeshi parents.',
      },
    ],
  },
  {
    id: 'bd-citizenship-po-1972',
    title: 'The Bangladesh Citizenship (Temporary Provisions) Order, 1972',
    titleBn: 'বাংলাদেশ নাগরিকত্ব (অস্থায়ী বিধান) আদেশ, ১৯৭২',
    shortTitle: 'Citizenship Order 1972 (নাগরিকত্ব আদেশ)',
    alternateTitles: ['President’s Order No. 149 of 1972', '১৯৭২ সালের ১৪৯ নং রাষ্ট্রপতির আদেশ'],
    enactmentYear: 1972,
    actNumber: 'P.O. No. 149 of 1972',
    actType: 'President’s Order',
    era: 'bangladesh-era',
    volumeNumber: 15,
    volumeCitation: 'The Bangladesh Code, Volume XV (1971–1973), P.O. No. 149',
    category: 'Immigration & Citizenship Law',
    categorySlug: 'immigration-citizenship',
    subcategories: ['Liberation War Citizenship', 'Deemed Citizens (Art 2)', 'Dual Nationality (Art 2B)', 'Dual Citizenship Certificates'],
    ministry: 'Security Services Division, Ministry of Home Affairs',
    keywords: ['citizenship order', 'dual nationality', 'dual citizenship', 'expatriate bangladeshi', 'দ্বৈত নাগরিকত্ব', 'নাগরিক সনদ'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '15th December 1972',
    commencementDate: '26th March 1971',
    lastAmendedYear: 1978,
    overview: 'Historical presidential order defining citizenship for permanent residents of Bangladesh on 25 March 1971, and regulating Dual Citizenship Certificates for expatriate Bangladeshis living abroad.',
    overviewBn: '১৯৭১ সালের ২৫ মার্চ বাংলাদেশে বসবাসকারী ব্যক্তিদের নাগরিকত্ব স্বীকৃতি এবং প্রবাসী বাংলাদেশীদের দ্বৈত নাগরিকত্ব সনদ প্রদানের আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-428.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/428',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 15 December 1972',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 8,
    relatedLawIds: ['bd-citizenship-act-1951', 'bd-passport-act-1920'],
    sections: [
      {
        number: 'Article 2B',
        title: 'Dual Nationality for Expatriate Bangladeshis',
        titleBn: 'প্রবাসী বাংলাদেশীদের দ্বৈত নাগরিকত্ব গ্রহণের অধিকার',
        content: 'The Government may grant a Dual Citizenship Certificate to any person who is a citizen of Bangladesh and who has also acquired the citizenship of specified foreign countries (e.g. UK, USA, Canada, Australia, EU).',
        contentBn: 'যুক্তরাজ্য, যুক্তরাষ্ট্র বা অনুমোদিত দেশের নাগরিকত্ব গ্রহণকারী প্রবাসী বাংলাদেশীদের দ্বৈত নাগরিকত্ব বহাল রাখার অধিকার।',
        simpleExplanation: 'Authorizes dual nationality for Bangladeshi diaspora members residing in North America, UK, Europe, and Australia.',
      },
    ],
  },
  {
    id: 'bd-passport-act-1920',
    title: 'The Passport Act, 1920',
    titleBn: 'পাসপোর্ট আইন, ১৯২০',
    shortTitle: 'Passport Act (পাসপোর্ট আইন)',
    alternateTitles: ['Act No. XXXIV of 1920', '১৯২০ সালের ৩৪ নং আইন'],
    enactmentYear: 1920,
    actNumber: 'Act No. XXXIV of 1920',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 5,
    volumeCitation: 'The Bangladesh Code, Volume V (1909–1920), Act XXXIV of 1920',
    category: 'Immigration & Citizenship Law',
    categorySlug: 'immigration-citizenship',
    subcategories: ['Entry into Bangladesh', 'Valid Travel Documents', 'Immigration Arrest Powers (Sec 4)'],
    ministry: 'Security Services Division / Department of Immigration and Passports (DIP)',
    keywords: ['passport act', 'immigration', 'travel document', 'border control', 'পাসপোর্ট আইন', 'বহিরাগমন'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '9th September 1920',
    commencementDate: '9th September 1920',
    lastAmendedYear: 2012,
    overview: 'Regulates requirements for valid passports and travel documents for persons entering Bangladesh across land, air, and sea immigration checkpoints.',
    overviewBn: 'বাংলাদেশে প্রবেশের সময় বৈধ পাসপোর্ট ও ভ্রমণ দলিল প্রদর্শনের বাধ্যবাধকতা এবং পাসপোর্ট জালিয়াতি প্রতিরোধ সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-124.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/124',
    officialGazetteCitation: 'Legislative Enactment Act XXXIV of 1920 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 6,
    relatedLawIds: ['bd-foreigners-act-1946', 'bd-citizenship-act-1951'],
    sections: [
      {
        number: 'Section 3',
        title: 'Power to Make Rules Requiring Valid Passports for Entry',
        titleBn: 'বাংলাদেশে প্রবেশের জন্য পাসপোর্ট প্রদর্শনের বাধ্যবাধকতা',
        content: 'The Government may make rules requiring that persons entering Bangladesh shall be in possession of valid passports and visas.',
        contentBn: 'বৈধ পাসপোর্ট ও ভিসা ব্যতীত দেশে প্রবেশ নিষিদ্ধ।',
        simpleExplanation: 'Mandates official passports and valid visas for all border crossings.',
      },
    ],
  },
  {
    id: 'bd-foreigners-act-1946',
    title: 'The Foreigners Act, 1946',
    titleBn: 'বিদেশী নাগরিক আইন, ১৯৪৬',
    shortTitle: 'Foreigners Act (বিদেশী আইন)',
    alternateTitles: ['Act No. XXXI of 1946', '১৯৪৬ সালের ৩১ নং আইন'],
    enactmentYear: 1946,
    actNumber: 'Act No. XXXI of 1946',
    actType: 'Act of Parliament',
    era: 'british-era',
    volumeNumber: 8,
    volumeCitation: 'The Bangladesh Code, Volume VIII (1940–1946), Act XXXI of 1946',
    category: 'Immigration & Citizenship Law',
    categorySlug: 'immigration-citizenship',
    subcategories: ['Foreign Nationals Regulation', 'Visa Overstay Penalties (Sec 14)', 'Deportation Orders', 'Immigration Detention'],
    ministry: 'Security Services Division / Special Branch Immigration',
    keywords: ['foreigners act', 'visa overstay', 'deportation', 'illegal entry', 'foreign national', 'বিদেশী নাগরিক', 'ভিসা মেয়াদোত্তীর্ণ'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '23rd November 1946',
    commencementDate: '23th November 1946',
    lastAmendedYear: 2012,
    overview: 'Provides state executive powers to regulate the entry, stay, movement, visa overstay penalties, detention, and deportation of foreign nationals in Bangladesh.',
    overviewBn: 'বিদেশি নাগরিকদের আগমন, অবস্থান, ভিসার মেয়াদোত্তীর্ণের শাস্তি ও বহিষ্কার (Deportation) সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-212.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/212',
    officialGazetteCitation: 'Legislative Enactment Act XXXI of 1946 (Adopted via Act VIII of 1973)',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 19,
    relatedLawIds: ['bd-passport-act-1920', 'bd-citizenship-act-1951'],
    sections: [
      {
        number: 'Section 14',
        title: 'Penalties for Contravention of Visa Orders or Illegal Stay',
        titleBn: 'ভিসার শর্ত লঙ্ঘন বা অবৈধ অবস্থানের শাস্তি',
        content: 'If any person contravenes the provisions of this Act or of any order made thereunder, he shall be punished with imprisonment for a term which may extend to five years and shall also be liable to fine.',
        contentBn: 'ভিসার মেয়াদ শেষ হওয়ার পর অবৈধভাবে অবস্থান করলে অনধিক ৫ বছর কারাদণ্ড ও অর্থদণ্ড প্রদেয়।',
        simpleExplanation: 'Imposes up to 5 years imprisonment and deportation for unauthorized visa overstays.',
      },
    ],
  },
  {
    id: 'bd-overseas-employment-2013',
    title: 'The Overseas Employment and Migrants Act, 2013',
    titleBn: 'বৈদেশিক কর্মসংস্থান ও অভিবাসী আইন, ২০১৩',
    shortTitle: 'Overseas Employment Act (অভিবাসী আইন)',
    alternateTitles: ['Act No. XLVIII of 2013', '২০১৩ সালের ৪৮ নং আইন'],
    enactmentYear: 2013,
    actNumber: 'Act No. XLVIII of 2013',
    actType: 'Act of Parliament',
    era: 'bangladesh-era',
    volumeNumber: 39,
    volumeCitation: 'The Bangladesh Code, Volume XXXIX (2013–2014), Act XLVIII of 2013',
    category: 'Immigration & Citizenship Law',
    categorySlug: 'immigration-citizenship',
    subcategories: ['Recruiting Agencies (RL)', 'Migrant Worker Welfare', 'Illegal Visa Fraud Penalties (Sec 31)', 'BMET Oversight'],
    ministry: 'Ministry of Expatriates’ Welfare and Overseas Employment / BMET',
    keywords: ['overseas employment', 'migrant workers', 'bmet', 'recruiting agency', 'visa fraud', 'বৈদেশিক কর্মসংস্থান', 'অভিবাসী শ্রমিক', 'রিক্রুটিং এজেন্সি'],
    jurisdiction: 'Bangladesh',
    jurisdictionCode: 'BD',
    status: 'In Force',
    enactmentDate: '27th October 2013',
    commencementDate: '27th October 2013',
    lastAmendedYear: 2023,
    overview: 'Comprehensive legislation safeguarding the rights of Bangladeshi migrant workers, licensing and regulating recruitment agencies (BAIRA / RL holders), preventing visa fraud, human trafficking, and exorbitant migration costs.',
    overviewBn: 'প্রবাসী শ্রমিকদের অধিকার সুরক্ষা, রিক্রুটিং এজেন্সির লাইসেন্সিং এবং ভুয়া ভিসা ও অতিরিক্ত অভিবাসন ব্যয় প্রতিরোধ সংক্রান্ত আইন।',
    officialSource: 'Bangladesh Code (bdcode.gov.bd)',
    sourceUrl: 'http://bdlaws.minlaw.gov.bd/act-1120.html',
    mirrorSourceUrl: 'https://bdcode.gov.bd/act/1120',
    officialGazetteCitation: 'Bangladesh Gazette Extraordinary, 27 October 2013',
    importDate: '2026-08-20T00:00:00Z',
    lastVerifiedDate: '2026-08-26T00:00:00Z',
    integrityStatus: 'fully-verified',
    totalSectionsCount: 49,
    relatedLawIds: ['bd-passport-act-1920', 'bd-labour-act-2006'],
    sections: [
      {
        number: 'Section 19',
        title: 'Rights of Migrant Workers and Standard Employment Contracts',
        titleBn: 'অভিবাসী শ্রমিকের অধিকার ও কাজের চুক্তিপত্র',
        content: 'Every migrant worker has the right to a clear, authenticated employment contract specifying wages, accommodation, working hours, and medical benefits prior to departure.',
        contentBn: 'বিদেশে গমনের পূর্বে নিয়োগকারী দেশের ভাষা ও স্পষ্ট শর্ত সংবলিত কর্মচুক্তিপত্র প্রাপ্তির অধিকার।',
        simpleExplanation: 'Requires authenticated employment agreements to protect outbound workers.',
      },
      {
        number: 'Section 31',
        title: 'Penalties for Illegal Recruitment and Fraudulent Visa Promises',
        titleBn: 'অবৈধ নিয়োগ ও ভুয়া ভিসার প্রলোভন দেখানোর শাস্তি',
        content: 'Whoever without a valid recruiting license recruits or promises overseas employment to any person through fraud or deceit shall be punished with imprisonment up to ten years and fine.',
        contentBn: 'লাইসেন্সবিহীন আদম ব্যবসা বা ভুয়া ভিসায় অর্থ আত্মসাৎ করিলে অনধিক ১০ বছর কারাদণ্ড ও অর্থদণ্ড প্রদেয়।',
        simpleExplanation: 'Imposes up to 10 years imprisonment for unauthorized recruiting agencies and visa scammers.',
        penalty: 'Imprisonment up to 10 years and fine',
        isBailable: false,
        isCognizable: true,
      },
    ],
  },
];
